### ISSUE TITLE
Probleme mit abschließen von Ernteaufträgen!

### ISSUE THREAD

**Issue by Nidi81** [Mmtrx/FS22_BetterContracts#100]
Hallo
Ich weiss nicht ob es an den mod bettercontract liegt oder allgemein am Spiel! 
Wir haben das Problem das Grasaufträge jeden tag neu generiert werden! Wir spielen mit Season 2 Tage Pro Monat und M+ und es werden Grasaufträge JEDEN TAG neu generiert was absolut unrealistisch das jeden Tag das Gras komplett neu vollständig ausgewachsen ist ist meiner Meinung nach!

Desweiteren haben wir das Problem das Ernteaufträge wie zum Beispiel Hafer gerade so abgeschlossen werden können obwohl ich das schon reduziert habe mit der Version 1.2.7.0 auf 85% Quote!

Ich hab es jetzt nur mal so hier angemerkt, wie gesagt ich weiss nicht ob es was mit dem MOD zu tun hat!

MFG

**Comment by Mmtrx** [comment]
Moin,
welche Karte?
Und heißt jeden Tag neue Grasaufträge, dass ihr auf einem Feld das Gras mäht und es am nächsten Tag wieder die volle Wachstumsstufe hat?

**Comment by Nidi81** [comment]
Wir spielen auf der Landersum Map!

Ja teilweise wachsen die Grasflächen schon nach einem Tag wieder nach und nicht erst wie standard nach 1 Monat, aber ich glaube so wie ich das von meinen Spielern gehört habe ist das zu 99 Prozent der Map geschuldet und liegt nicht am BetterContract Mod!

Auch bei den Ernteaufträgen sieht es wohl so aus das die Erträge zu gering sind weil wir ja mit PF und auch M+ spielen das die aufträge nicht abgeschlossen werden können weil einfach zu wenig ertrag ist! ich musste das auf 80 Prozent runterdrehen in der neuen Einstellung im Bettercontract mod das man Ernteaufträge abschließen kann was natürlich die Grasaufträge zu sehr begünstigt! Weil da habe ich das Problem wenn ich im BC Mod die Einstellung runterdrehe auf 80% der erfüllbaren Menge braucht man nur 30% der Ballen abliefern und der Auftrag ist erfüllt und ich weiss nicht wie man das im mod ändern könnte das die Grasmissionen da extra gerechnet werden!

Also ich würde mir wünschen falls das machbar ist das für Grasmissionen mal in Zukunft als Update eine extra einstellung gibt wo man Grasaufträge die erfüllbare Menge auch anpassen kann und auch bei der Faule Farmer Einstellung Grasmssionen eine eigene Kategorie sind nur so als Idee falls das umsetzbar wäre oder angedacht ist!

LG Mario

**Comment by Mmtrx** [comment]
Hi,
ja Maps können eigene Wachstums-Regeln definieren.

Idee mit der getrennten Einstellung für Ballenmissionen ist ok, kommt ggf in einem nächsten Update. Im Moment ist der Erfolgsfaktor für Ballenaufträge immer 3% kleiner als der für sonstige Erntemissionen. Im Basegame also 
- Standard 93 %
- Ballen 90%

Deswegen würde mich wundern, wenn ihr bei 80% Standard auf 50 % Ballen kommt 😉.
Du kannst den Erfolgsfaktor (Prozent abzuliefernde Menge) für Ballen selbst einstellen mit 
```
	BaleMission.FILL_SUCCESS_FACTOR =  0.80
```
Zeile einfügen in file betterContracts.lua, Funktion `function BetterContracts:onMissionInitialize()`.
Wie man die Prozentwerte noch niedriger setzen kann, steht in Thread #98.
