### ISSUE TITLE
Latest patch broke a feature

### ISSUE THREAD

**Issue by TheWhiteRussian** [Mmtrx/FS22_BetterContracts#101]
After the latest update yesterday, the contract info no longer appears in the vehicle tooltip on the bottom right of the screen when you hover your mouse over the vehicle. The vehicle no longer says it belongs to (harvest 58) for example. Reverting the version one back fixes it. No other mods installed.

**Comment by Mmtrx** [comment]
That info is  only shown if **Details** (on the contracts page) is on.
![fsScreen_2023_02_12_09_50_21](https://user-images.githubusercontent.com/86842734/218301646-1310c857-2483-4f10-a8d7-253afbae6fab.png)

**Comment by TheWhiteRussian** [comment]
It is
