### ISSUE TITLE
Vorschlag: Getrennte Anzeige Fortschritt Ernten und Liefern

### ISSUE THREAD

**Issue by 0scarZulu** [Mmtrx/FS22_BetterContracts#102]
Hallo :) 
wäre es möglich bei Ernteaufträge in der Übersicht eine getrennte ANzeige sichtbar zu machen für die Feldarbeit an sich und für die Prozentanzeige wie viel man bereits abgeliefert hat? Aktuell ist ja nur der Gesamtfortschritt sichtbar. Ich denke jedoch eine graphische Anzeige mit 2 Balken wird nicht möglicht sein. Ober Feldarbeit und unten drunter Lieferung. Ja ich weiß das man es über Details sehen kann :D 
![image](https://user-images.githubusercontent.com/78980660/218511436-d9b7fa91-9d11-4cd6-8533-bf715ca3bf7a.png)

**Comment by Mmtrx** [comment]
Moin,
grundsätzlich ist ja alles möglich - nur ne Frage der Programmierung 😀.
Ich denk mal drüber nach..

**Comment by 0scarZulu** [comment]
Cool Danke :)

**Comment by Mmtrx** [comment]
Erster Test sieht ganz gut aus:
![fsScreen_2023_02_20_16_19_33](https://user-images.githubusercontent.com/86842734/220145165-0d822ed1-67d4-4395-a30a-de8623ca03d2.png)

**Comment by H4nnib4l22** [comment]
Das sieht Klasse aus!!

**Comment by 0scarZulu** [comment]
Stark das es geklappt hat und du es umgesetzt hast!!

**Comment by Mmtrx** [comment]
Testversion könnt ihr hier laden: [v1.2.7.3](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.7.3).

**Comment by 0scarZulu** [comment]
Danke für die klasse Arbeit. Wäre es aber Möglich die Anzeige auch zu sehen wenn man nicht die Details eingeblendet hat?

**Comment by Mmtrx** [comment]
Hi Oscar,
würd ich gern so lassen wie es jetzt ist, denn
- bei Details aus sollte der Standard Auftrags-Screen angezeigt werden, da einige Spieler BetterContracts nur wegen der zusätzlichen Aufträge / unbegrenzter Auftragsannahme nutzen
- den Gesamtfortschritt des Auftrags sieht man nur im Standard Screen
- auch alle anderen Zusatz-Anzeigen verschwinden bei Details aus
