### ISSUE TITLE
Keine Saat Missionen 

### ISSUE THREAD

**Issue by MeRida2104** [Mmtrx/FS22_BetterContracts#103]
Hi 👋 Wir haben auf unserem Dedi Server das Problem, dass wir trotz aktiviertem lazy NPC (Saat ist auch auf true) keine Saat Missionen erhalten. Die KI arbeitet diese vollständig ab ohne was übrig zu lassen. 

Wir setzen die neueste Version deines Mods ein. Ist dir da was bekannt?

Beste Grüße
MeRida

**Comment by Mmtrx** [comment]
Moin,
auf welcher Karte? Hat die einen angepassten Wachstumskalender?

Ansonsten bitte mal eine log.txt hier hochladen 😉

**Comment by MeRida2104** [comment]
Hi,

reiche ich morgen gerne mal nach. Bin heut nicht mehr aufm Server.

Zu deinen Fragen: Wir spielen auf der Ostseeküste 22 und ja, die hat einen angepassten Wachstumskalender. Bspw kann man im März noch mal einen Monat lang Weizen drillen.

Gibt es damit bekannte Probleme?

**Comment by MeRida2104** [comment]
Hi @Mmtrx,

sorry meine Rückmeldung hat etwas länger gedauert. Leider sind auch in der Ansaatzeit September, Oktober und November keinerlei Aufträge für Saat reingerutscht.

Ich habe dir mal die Log meines Clients und die Log des Server hochgeladen. Kannst du damit etwas anfangen?
[Server_Log.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/10849134/Server_Log.txt)
[Client_log.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/10849135/Client_log.txt)

**Comment by Mmtrx** [comment]
Moin,
konnte in deinen Logs jetzt auf Anhieb nix finden. Könnte ein Statistikproblem sein: LazyFarmer / npcSow = true bedeutet, dass in 50% der Fälle, wenn laut Growth-Kalender und Feldstatus Säen möglich wäre, der NPC Farmer darauf verzichtet und es als Vertrag ausschreibt. Wenns dumm kommt (und ggf sowieso nur wenig Felder zur Saat bereit sind), gibt's vielleicht mal längere Zeit keine Saat-Aufträge.

Ihr könntet mal versuchen, die Statistik zugunsten Verträge zu verschieben. Dazu muss man im Mod, Datei `betterContracts.lua` in den Zeilen
```
	self.npcProb = {
		harvest = 1.0,
		plowCultivate = 0.5,
		sow = 0.5,
		fertilize = 0.9,
		weed = 0.9,
```
sow = 1.0 setzen.

**Comment by MeRida2104** [comment]
Hi, danke für deine Analyse :) Da morgen bei uns auf dem Server März ist und dann die Ansaatzeit wieder ansteht, würde ich das heute einspielen. Ich melde mich dann wieder :)

**Comment by Mmtrx** [comment]
Hi,
ja 1.0 heißt 100 % Wahrscheinlichkeit, dass der NPC Farmer das Feld in Ruhe lässt.

**Comment by PapaTim68** [comment]
Moin,
ich habe ein ähnliches, evtl. das gleiche Problem. Eine Symptomatik, die ich noch bemerkt habe, ist, dass beim Refreshen der Aufträge für wenige Millisekunden Auftrage hinzugefügt werden. Ebenfalls mit Lazy NPC, als wenn die Aufträge ausgeschrieben werden und sofort wieder verschwinden, weil von jemandem (bin alleine auf dem Server) sie annimmt oder sie am Ende der ansaat Zeit nicht mehr existieren.
Grüße,
PapaTim68

**Comment by PapaTim68** [comment]
Okay hab gesehen das ich noch nen backup von nicht zu weit zurück hatte. Hier Client/Server Log:
[log_server.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/10949305/log.txt)

[log_client.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/10949306/log.txt)

Außerdem noch ein kurzes Video.
https://youtu.be/sihoMQYVilU
Zum Ende hin ist es sehr gut Sichtbar.

Ebenfalls mit allem hier auf 1, probiert, kein unterschied.
`self.npcProb = {
		harvest = 1.0,
		plowCultivate = 0.5,
		sow = 0.5,
		fertilize = 0.9,
		weed = 0.9,`

**Comment by PapaTim68** [comment]
Moin,
ich muss schauen, ob ich noch ein Savebackup von Februar habe, inzwischen ist das Save im Mai.
Zum Thema welche Saat Aufträge, Baumwolle ist auf der NF ab Februar zur Aussaat bereit, und ich erinnere mich auch das die Aufträge aufblinken und danach auf der Map Felder Baumwolle gesät bekommen haben.
Ich werde nachher noch mal nach dem Save schauen und mich danach nochmal melden.

**Comment by MeRida2104** [comment]
Hi @Mmtrx, das Problem besteht leider nach wie vor. Wir haben extrem wenig Saatmissionen und wenn welche auftauchen, sind sie relativ schnell weg. Die Werte unter self.npcProb stehen alle auf 1.0, dennoch sind Saatmissionen extrem rar. Düngemissionen betrifft dies übrigens ebenfalls. Obwohl auf 1.0, düngt die KI iwann von selbst und die Aufträge werden innerhalb eines ingame Monats weniger.

**Comment by Mmtrx** [comment]
Hm - hier ist mal ein kleines Tool zum Verfolgen der Missionen, unabhängig von BC.
Einfach als Mod installieren, und laufen lassen (wie @Timmeey86 sagt, mit 2000x oder 5000x). Dann kann man in der Log sehen, wann z.B. welche Saatmissionen erzeugt wurden, wann die KI sie gemacht (und damit wieder gelöscht) hat.
[MissionLog.zip](https://github.com/Mmtrx/FS22_BetterContracts/files/11340884/MissionLog.zip)

**Comment by Timmeey86** [comment]
Alles klar, werde ich mal machen. Eventuell werde ich das auch auf unseren vier Servern rein packen, die kommen allerdings nur einmal alle 36 Tage im März an

**Comment by PapaTim68** [comment]
Hier einmal zwei Logs im SP mit dem Server Save jeweils 1 Jahr mit x20.000 Geschwindigkeit.
Beide mit dem aktuellen Git Realese.
[log_newest_Version.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/11341455/log_newest_Version.txt)
Das zweite Log mit `self.npcProb` alles auf 1.0
[log_modTo10.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/11341459/log_modTo10.txt)
Hier der Wachstumskalender falls notwendig, auf der aktuellen NF oG.
![grafik](https://user-images.githubusercontent.com/29522870/234810092-30d23139-d5e8-4653-a2a9-80e521aba238.png)
![grafik](https://user-images.githubusercontent.com/29522870/234810142-bc7d6cb1-edab-4a94-b03f-f6cd1f006517.png)

Am Rande eine Auffälligkeit evtl. beeinflusst evtl. nicht wir haben nie Kalkmissionen, obwohl der Mod vorhanden ist.

**Comment by Timmeey86** [comment]
@PapaTim68 Habt ihr evtl Roller-Missionen und Kalk-Missionen aktiv? Wir haben festgestellt, dass der Roller Mod die Kalk-Missionen verhindert

**Comment by PapaTim68** [comment]
Jup sind beide aktive und Roller Missionen kommen auch von Zeit zu Zeit.

**Comment by Mmtrx** [comment]
Hm, ein paar Erkenntnisse aus deinen Logs:
- Kalkmissionen sind zwar selten, werden aber erzeugt:
```
 Jun 1, 10:00: field  71          OAT       lime mission generated
 Jun 2, 13:00: field  43       CANOLA       lime mission generated
 Jun 2, 13:00: field  44       CANOLA       lime mission generated 
```
Eine existierende (nicht aktive) Pflug-/ Grubber-/ Säh-Mission verhindert das Erzeugen einer Kalkmission für dieses Feld. Aber nicht, dass die KI es zwischendurch kalkt..
Dass der Walzmissionen-Mod Kalkaufträge verhindert, konnte ich bei meinen Tests auf Elmcreek nicht feststellen.
- Sähmissionen sind manchmal nur kurz verfügbar:
```
 Aug 1, 05:00: field  54       CANOLA        sow mission generated
 Aug 1, 14:00: field  54       CANOLA sowed 
 Aug 1, 14:00: field  54        sow mission deleted
 Aug 3, 02:00: field  54       CANOLA  fertilize mission generated
```
Hätte man also die Mission zwischen 5:00 und 14:00 annehmen müssen..
Diese hier waren fast alle 2 Monate verfügbar (jeweils bis Ende der Sähperiode):
```
 Sep 1, 00:00: field  66       BARLEY        sow mission generated
 Sep 1, 01:00: field  68        WHEAT        sow mission generated
 Sep 1, 02:00: field  69       BARLEY        sow mission generated
 Sep 1, 02:00: field  32        SPELT        sow mission generated
 Sep 1, 02:00: field  56        SPELT        sow mission generated
 Sep 1, 04:00: field  70          RYE        sow mission generated
 Sep 1, 05:00: field  24          RYE        sow mission generated
 Sep 1, 18:00: field  53        SPELT        sow mission generated
 Feb 1, 01:00: field  59       COTTON        sow mission generated
 Mär 1, 00:00: field  70          OAT        sow mission generated
 Mär 1, 00:00: field  29        ONION        sow mission generated
 Mär 1, 00:00: field  58    SUNFLOWER        sow mission generated
 Mär 1, 02:00: field  68       COTTON        sow mission generated
 Mär 1, 02:00: field  32    SUNFLOWER        sow mission generated
 Mär 1, 02:00: field  69 WHITECABBAGE        sow mission generated
```
- Düng-, Kalk-, Spritz- und Jäte-Missionen werden vom Game zwar das ganze Jahr über erzeugt, aber im Winter dann sofort wieder gelöscht (daher die vielen Log-Einträge von Dez - Feb).

Fazit: das ganze Missionssystem ist halt sehr dynamisch, und kann daher selbst bei gleichem Ausgangsspielstand ganz unterschiedliche Entwicklungen nehmen (wie @Timmeey86's Tests gezeigt haben). Fast wie in der richtigen Landwirtschaft 😉.

**Comment by PapaTim68** [comment]
Das sind interessante Erkenntnisse.
Könnte das häufige/schnelle drücken der Missionen Akutaliserungs-Taste evtl. zum "Problem" von hier:

> Hätte man also die Mission zwischen 5:00 und 14:00 annehmen müssen..

 beitragen.
In der Hinsicht, dass das Aktualisieren nicht nur neue Mission erzeugt, wie es zu erwarten wäre, sondern auch bestehende  Missionen „weiter ticken“ lässt. Also eine eh schon kurze Verfügbarkeit weiter reduziert.

Andere Sache. Sind große Unterschiede zwischen dem `self.npcProb` auf 1.0 und nicht zu erkennen? Wenn das Setzen auf 1.0 die Missionssitutation verbessert, wäre evtl. die Veränderung der Ingame Settings für den LazyNPC, weg von einem simplen True/False zu einer Einstellmöglichkeit für die Wahrscheinlichkeitswerte eine mögliche Vorgehensweise.

**Comment by Mmtrx** [comment]
Du hast schon recht, "Aktualisieren" ("X" = Neue Verträge) erzeugt nur neue Missionen. Das Weiterticken der übrigen erfolgt ganz normal im basegame durch den (beschleunigten) Zeitlauf. Eigentlich brauchst du "X" gar nicht zu drücken, da alle 3 ingame Stunden sowieso versucht wird, neue Missionen zu erzeugen.

Ein paar mehr Missionen werden bei den self.ncProb Werten auf 1.0 schon erzeugt. Allerdings hab ich gesehen, dass die KI Säh- und Erntemissionen selbst macht (und sie damit löscht) - das sollte bei 1.0 eigentlich nicht passieren.
Hast du auch auf der BC settings page alle Sub-Schalter (Ernten, Säen, Düngen, ...) auf `aktiviert` stehen?

**Comment by PapaTim68** [comment]
> Hast du auch auf der BC settings page alle Sub-Schalter (Ernten, Säen, Düngen, ...) auf `aktiviert` stehen?

Ja alle auf aktiviert. Ich meinte nur in der Hinsicht das wir am Monatsanfang Missionen aktualisieren und alle annehmen.
Da ich es häufig hatte, dass Missionen dann nur aufgeblitzt sind, kam meine Vermutung mit dem weiter ticken.

**Comment by Timmeey86** [comment]
Hier mal ein erster Log Output von unserem Server (nur der relevante Teil.
Leider habe ich wohl den Debug Modus nicht eingeschaltet sodass von Better Contracts selbst kein Output kam.

```
2023-05-03 06:08 Mar 1, 00:00: field  52       BARLEY sowed 
2023-05-03 06:08 Mar 1, 00:00: field 223          OAT sowed 
2023-05-03 06:08 Mar 1, 00:00: field 103       BARLEY sowed 
2023-05-03 06:08 Mar 1, 00:00: field 139       BARLEY sowed 
2023-05-03 06:08 Mar 1, 00:00: field 199       BARLEY sowed 
2023-05-03 06:09 dataS/character/animals/wild/deer/deerAdult.i3d (28.93 ms)
2023-05-03 06:09 Mar 1, 00:00: field  94       COTTON sowed 
2023-05-03 06:09 Mar 1, 00:00: field  30       BARLEY sowed 
2023-05-03 06:09 dataS/character/animals/wild/deer/deerAdult.i3d (28.63 ms)
2023-05-03 06:10 Mar 1, 00:00: field 184       BARLEY sowed 
2023-05-03 06:10 Mar 1, 00:00: field 175        WHEAT sowed 
2023-05-03 06:10 Mar 1, 00:00: field  59        WHEAT sowed 
2023-05-03 06:10 Mar 1, 00:00: field   9          OAT sowed 
2023-05-03 06:10 Mar 1, 00:00: field 143    SUGARBEET sowed 
2023-05-03 06:10 Mar 1, 00:00: field 146       COTTON sowed 
2023-05-03 06:10 Mar 1, 00:00: field 218          OAT sowed 
2023-05-03 06:11 Mar 1, 00:00: field 178       BARLEY sowed 
2023-05-03 06:11 Mar 1, 00:00: field 198          OAT sowed 
2023-05-03 06:11 Mar 1, 00:00: field 105       BARLEY sowed 
2023-05-03 06:11 Mar 1, 00:00: field 136       BARLEY sowed 
2023-05-03 06:11 Mar 1, 00:00: field 130       COTTON sowed 
2023-05-03 06:11 Mar 1, 00:00: field  48        WHEAT sowed 
2023-05-03 06:11 dataS/character/animals/wild/deer/deerAdult.i3d (28.56 ms)
2023-05-03 06:11 Mar 1, 00:00: field 151    SUGARBEET sowed 
2023-05-03 06:11 Mar 1, 00:00: field 201       BARLEY sowed 
2023-05-03 06:12 Mar 1, 00:00: field  97       BARLEY sowed 
2023-05-03 06:12 Mar 1, 00:00: field  35        WHEAT sowed 
2023-05-03 06:12 Mar 1, 00:00: field   8       BARLEY sowed 
2023-05-03 06:12 Mar 1, 00:00: field 166          OAT sowed 
2023-05-03 06:12 Mar 1, 00:00: field 224       COTTON sowed 
2023-05-03 06:12 Mar 1, 00:00: field  63    SUGARBEET sowed 
2023-05-03 06:12 Mar 1, 00:00: field  78        WHEAT sowed 
2023-05-03 06:12 Mar 1, 00:00: field 162    SUGARBEET sowed 
2023-05-03 06:13 Mar 1, 00:00: field  80       BARLEY sowed 
2023-05-03 06:13 Mar 1, 00:00: field 148       BARLEY sowed 
2023-05-03 06:13 Mar 1, 00:00: field  36        WHEAT sowed 
2023-05-03 06:14 Mar 1, 00:00: field 153    SUGARBEET sowed 
``` 

Wie man sehen kann wurden um 0 Uhr ingame Zeit sofort sehr viele Felder gesät (Das ist der erste Output vom Logging Mod im ganzen Log file). Wodurch das ausgelöst wurde ist natürlich eine interessante Frage.

Die normale Missionsgenerierung, die auf 2h Intervall steht ist erst um 1 Uhr ingame Zeit angesprungen, d.h. das hier war wohl etwas anderes?

Interessant ist auch das die Log Ausgaben mit 0 Uhr ingame Zeit auf viele Echtzeit-Minuten verteilt sind

**Comment by PapaTim68** [comment]
Läuft euer Server evtl., auch wenn niemand verbunden ist und auf 1x Geschwindigkeit?
Die Idee frage, kommt daher, dass das log um 06:12 Echtzeit erstellt wurde.
Das könnte darauf hindeuten, dass die Simulation bei Abwesenheit von Spielern nicht korrekt oder anders funktioniert was dieses komische Verhalten erklärt.

**Comment by Timmeey86** [comment]
Ja, die Server laufen durch, auf 1x und 3 Tage/Monat, und 6h "Offset" zur UTC Zeit

**Comment by MeRida2104** [comment]
Bei uns ebenfalls!

**Comment by Timmeey86** [comment]
Der Server lief seit 4 Uhr, die Log Einträge müssten gegen 0-1 Uhr ingame gewesen sein

**Comment by Mmtrx** [comment]
Hm,
die NPC Aktionen auf ihren Feldern werden von der ingame Funktion `FieldManager:updateNPCField(fieldToUpdate, true)` gesteuert, die sich jede 0.5 sec ein NPC-feld ansieht, und (mit einer gewissen Wahrscheinlichkeit) eine zulässige Aktion (Ernten, Düngen, ..) ausführt. 
Bei allen Aktionen heißt die Abfrage im Code immer 
```
... if <field conditions allow action> and math.random() < 0.xx then
   -- initiate the NPC action on field
```
Nur beim Säen fehlt der `math.random()` Teil. D.h. sowie die Bedingung "Feld leer und Pflanzperiode der geplanten Frucht hat begonnen" erfüllt ist, erzeugt die Funktion eine Sä-Aktion durch NPC. Danach löscht sie eine etwa vorhandene Sä-Mission auf dem selben Feld. BC verhindert (mit der durch `npcProb.sow` angegebenen Wahrscheinlichkeit) nur dieses Löschen. In deinem Fall sind ja aber noch gar keine Sä-Missionen erzeugt worden.

Ich werd also in BC die `updateNPCField`() mal etwas überschreiben..

In der Zwischenzeit kannst du mal probieren, das MIssion Generation Intervall auf 1 Stunde zu stellen, damit vielleicht auch um 0:00 schon ein paar Sä-Missionen erzeugt werden können.

**Comment by Timmeey86** [comment]
@Mmtrx Das erklärt, warum ich das lokal nicht reproduzieren konnte, und ich habe das auch eben überprüft:

Wenn ich bis auf Mitternacht gehe und dann auf 1x Geschwindigkeit schalte, kann ich sehen, wie alle 1-5 Sekunden ein Feld gesät wird.
Wenn ich auf 360x oder höher schalte, passiert das nur bei 1-2 Feldern und dann werden Missionen generiert, wonach nur noch selten gesät wird (ich habe Default settings, also nicht Faktor 1.0)

Sieht ja fast nach Giants Bug aus, dass dort der `random()` Check fehlt. Ich fürchte auch, dass du da außer überschreiben nicht viel Wahl haben wirst..

**Comment by MeRida2104** [comment]
Hallo @Mmtrx ,

ich hoffe, du kannst uns bei diesem Thema weiterhelfen. Gibt es vielleicht eine Lösung, die innerhalb deines Ermessensspielraums liegt? Die Sache mit den fehlenden Missionen ist ziemlich ärgerlich für uns (ohne dir die Schuld zu geben, da es ja nicht an deinem Mod liegt).

Danke im Voraus!

**Comment by Mmtrx** [comment]
Moin, ihr könnt nun mal den neuesten [update ](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.8.7) probieren. Wenn lazyNPC aktiv ist, machen die NPC Farmer nix bis Mittags des ersten Tags im Monat. So dass man ein paar Stunden Zeit hat, sich die Sä-Aufträge zu sichern..

**Comment by MeRida2104** [comment]
Ist erledigt, funktioniert sehr gut :)
