### ISSUE TITLE
Balling mission going to wrong unloading point

### ISSUE THREAD

**Issue by jeje3537** [Mmtrx/FS22_BetterContracts#109]
Playing on Somewhere in Thuringia III I sometime have contracts where I have to make hay bales and then deliver them to the BGA bunkers which doesn't accept hay. The map is using "FS22_Lizard_Modular_BGA" as placeables.

**Comment by Mmtrx** [comment]
Are you using Maize+? I've heard that sometimes that mod changes a silage baling contract (sellpoint BGA) to hay baling. See also #77

**Comment by jeje3537** [comment]
I use Maize plus, but I don't think issue #77 is what's causing my problem as my mission is hay mission from the start and doesn't change at all, but sometimes the unloading point (BGA) doesn't accept hay by default.

**Comment by Timmeey86** [comment]
We sometimes get that too, on Somewhere in Thuringia, but also on other maps, with Maize Plus active.
What usually happens though is that the text says "ted and bale", but the contract actually comes with a bale wrapper.
As long as we always check what kind of equipment we get and ignore the text, we have always been fine so far.
This happened both with and without better contracts, though.

**Comment by jeje3537** [comment]
I'll check next time and see if I unload silage instead of hay as requested, the contract fulfills or not.
For now I edited the modular Bga mod to accept hay in bunkers but that's not the better solution.

**Comment by Mmtrx** [comment]
Seems like this is a Maize+ issue, since it also happens w/o BC.

**Comment by MeRida2104** [comment]
Ich habe mich dazu im MaizePlus Discord informiert. Das Problem liegt im MaizePlus und wird in den nächsten Tagen per Modupdate behoben!

**Comment by MeRida2104** [comment]
Update ist da

https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=253528&title=fs2022
