### ISSUE TITLE
feature request: missionvehicles Speicherort

### ISSUE THREAD

**Issue by bobo6** [Mmtrx/FS22_BetterContracts#111]
Hallo Mmtrx,

wäre es möglich die missionsVehicles.xml an einem anderen Ort zu Speicher als im Mod selber. 

Als Beispiel wie in der Config von AD als Bestandteil des Save Game Ordners.

So muss der Mod nicht immer bei Änderungen oder nötigen Punkten angepasst werden. 

Damit könnte auch der Hash erhalten bleiben vom Mod selber.

Beste Grüße
EWW_Bobo

**Comment by Mmtrx** [comment]
Hi,
welche missionVehicles meinst du denn? Im Mod gibts unter dem **Ordner** `missionVehicles`  die basegame.xml und die sample_userDefined.xml. Die Fahrzeuge aus basegame.xml benutzt die Mod zusätzlich zu den Standard-Missionsfahrzeugen aus dem basegame.
Benutzt du eine eigene userDefined.xml?

**Comment by bobo6** [comment]
Ja hätte ich dazu schreiben können habe angefangen eine user defined zu machen. Wollte sie dann ggf zur HoF2022 zur Verfügung stellen. Ggf löst es das Problem mit all dem ganzen Chaos was die Mission vehicles angeht

**Comment by Mmtrx** [comment]
Moin,
Klar, das baue ich in den nächsten Update ein. Die userDefined. XML kann die Mod dann auch im Savegame Ordner suchen.

Chaos mit Missionsfahrzeugen entsteht dadurch, dass die Leute Mods und dlc ein- und ausschalten, und dann das selbe SaveGame wieder laden. Das ändert die Liste der verfügbaren Missionsfahrzeuge🤓

**Comment by bobo6** [comment]
super, vielen dank. Hoffen wir mal das Problem wird dadurch behoben :)

**Comment by Mmtrx** [comment]
Hm,
ist doch nicht ganz so einfach, weil die Fahrzeugliste ja zwischen Server und Clients identisch sein muss. (Für die in map, dlcs und mods enthaltenen missionVehicles.xml wird das ja vom Spiel überprüft.)
Der Client in einem MP Spiel kann aber nicht das savegame directory des Servers sehen.

Also, für SP kann ich deinen Vorschlag umsetzen. Für MP müsstest du dann dafür sorgen, dass alle Clients eine Kopie der userDefined.xml auf der Platte haben. Sagen wir z.B. unter`modSettings/BetterContracts/userDefined.xml`

**Comment by bobo6** [comment]
das sollte so nicht das Problem sein man kann ja eine Anleitung schreiben wie man es installiert. Wenn er es auf dem Server dann genauso stark überschreibt wie auf dem Client dann ist das Problem definitiv gelöst. Die Tests die ich gemacht habe zeigten mir auf das nichts dazu gemacht wird. Keine DLC oder auch Mods. Somit wäre es ja eine Kleinigkeit das ganze in ein Server bzw. Savegame einzubinden. Zu mindestens aus meiner Sicht.

**Comment by Mmtrx** [comment]
is fertig: [v1.2.7.5](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.7.5)

**Comment by bobo6** [comment]
dankeschön, dann geht es nun ans testen ich gebe dir natürlich eine Rückmeldung :)
