### ISSUE TITLE
Six figures reward numbers are "merged" with details mode on

### ISSUE THREAD

**Issue by SnakeManPMC** [Mmtrx/FS22_BetterContracts#113]
When browsing contracts list with details mode on, a large reward numbers in the 100,000 range will merge these numbers together, see attached screenshot.

![FS22-Better-Contracts-Reward-Merge-2023-03-02](https://user-images.githubusercontent.com/8061426/222517115-f068ae18-232d-4dbc-88a6-b556d223807e.jpg)

Its very hard to read the list of $123,456$123,456 formatting style :)

I don't have example screenshot of MILLIONS range, (yeah I've seen few of those) but what I recall it goes one number further which causes further overlapping of digits. Very hard to read indeed.

I always assumed this is giants GUI issue which cannot be fixed, but decided to create issue ticket anyways since perhaps you guys only play on small terrains with tiny fields and never seen contract with reward on the six figures range.

What am I saying? Please add at least one empty character/digit formatting between contract reward numbers.

**Comment by Mmtrx** [comment]
Absolutely valid issue! 
I will see what can be done to fix this. E.g. just shift the first reward no. somewhat to the left.. Or decrease the font, if number is greater 100,000 .. 🧐

**Comment by SnakeManPMC** [comment]
Would it be possible to \n linefeed first reward number, so it would be:
$123,456
$123,456
format style, there is room on the selected contract line and would fix that merging issue right away.

If that is possible, then maybe you could even add a small text description like "Reward" for the first and for second "You get" or "Actual Pay" or simply "Profit" etc whatever would be the proper english term for it, as the second number is for example on harvest contracts much bigger than reward as you can sell excess grain and in fertilizing contracts much lower as you have to pay for product.

Maybe like:
Reward: $123,456
You Get: $123,456

**Comment by Mmtrx** [comment]
Here is a test version for you:
[FS22_BetterContracts.zip](https://github.com/Mmtrx/FS22_BetterContracts/files/11030499/FS22_BetterContracts.zip)
Moved first reward no. to the left a bit, and numbers > 100k will be formatted as "kilo Dollars".

If I get positive feedback from you, this will be integrated in the next official BC release 😉

**Comment by SnakeManPMC** [comment]
Sorry I was busy this whole week, first day I had any time to do computer chores was today saturday.

**Comment by Mmtrx** [comment]
..seems to work ok.
