### ISSUE TITLE
Fertilizer contracts appear multiple times

### ISSUE THREAD

**Issue by Timmeey86** [Mmtrx/FS22_BetterContracts#114]
On our multiplayer servers set to 3 day months at 1x speed, we wrote down all the contracts all of the farms on Somewhere in Thuringia III did through an ingame year.
We noticed that fertilizer contracts appeared several times for every field, usually about 2-3 times, on some fields even up to 6 times. We added Better Contracts around the beginning of that ingame year so we have our suspicion this is related to the mod.

Is this intended behavior? Without the mod, we are pretty sure we would only be able to fertilize each field once per year

**Comment by Timmeey86** [comment]
Some more info about this: We are using Precision Farming, and that could be related.
Is there any way to efficiently debug an issue like this? If you tell me how, I could do the testing/debugging

**Comment by Mmtrx** [comment]
Hi, du sprichst ja deutsch, also:
PF kann schon das Verhalten ändern. Außerdem könnten 2-3 Düngemissionen innerhalb einer Wachstumsperiode durchaus auftreten, je nach Anzahl Düngestufen der Map. Die Logik der ingame Missionsgenerierung hab ich ja schon in #117 erklärt.
Ob eine Düngemission erzeugt werden kann, wird mit folgender Methode geprüft:
```
function FertilizeMission.canRunOnField(field, sprayFactor, fieldSpraySet, fieldPlowFactor, limeFactor, maxWeedState, stubbleFactor, rollerFactor)
...
	if fruitDesc == nil then -- nix angesät
		return false
	end
	if fruitDesc.minHarvestingGrowthState == 2 and fruitDesc.maxHarvestingGrowthState == 2 and fruitDesc.cutState == 3 then
		return false -- Frucht is Gründünger
	end
	if fieldSpraySet then -- Feld wurde gerade gedüngt
		return false
	end
	if sprayLevelMaxValue <= sprayLevel then -- höchste Düngestufe erreicht
		return false
	end
	if maxWeedState == 2 or maxWeedState == 3 then
		return false -- Unkraut mitel oder groß
	end
	local maxGrowthState = FieldUtil.getMaxGrowthState(field, fruitType)
	if maxGrowthState == 0 or fruitDesc.minHarvestingGrowthState <= maxGrowthState then
		return false -- Frucht noch nicht gewachsen oder schon erntereif
	end

	return true, FieldManager.FIELDSTATE_GROWING, maxGrowthState
end
```

**Comment by Timmeey86** [comment]
Alles klar. Ich schätze es liegt dann daran, dass sprayLevel irgendwie nicht richtig erhöht, oder wieder zurück gesetzt wurd (durch welchen Mod auch immer).

Hier ist ein Beispiel der aktuellen Map. Auf Feld 13 und 30 wurde z.B. schon zwei mal gedüngt, aber das Feld ist noch hellblau.
![grafik](https://user-images.githubusercontent.com/10223149/227786420-f73d1d87-488e-4084-adc6-ae727c0fa3ed.png)

Wenn ich mir mit Field Debug von Easy Dev den Zustand anschaue, erhalte ich folgende Werte sowohl für Felder, die schon zweimal, und Felder die nur einmal gedüngt wurden:
![grafik](https://user-images.githubusercontent.com/10223149/227787104-fae6e9cd-8b8f-4342-b7f8-fdf7d639d856.png)

Sollte da nicht "fertilizer 2" gesetzt sein, wenn schon zweimal gedüngt wurde?

**Comment by Timmeey86** [comment]
Bzw bei einem anderen Feld habe ich gerade beobachtet, dass "fertilizer 2" zunächst auf 9 Stand (mit Radius 1m). Nach akzeptieren einer Düngemission, wurde wieder auf "fertilizer 1" auf 9 gesetzt (und "fertilizer 2 auf 0"). Woran kann das liegen?

**Comment by Mmtrx** [comment]
Wenn das Feld Düngestufe 2 hat (fertilizer 2 auf 9), sollte gar keine Düngemission erzeugt werden (vorausgesetzt deine map hat 2 Düngestufen, und nicht 3).

Interessant wäre, ob das auch ohne PF passiert.
