### ISSUE TITLE
BCUserDefined.xml Map abhänig machen

### ISSUE THREAD

**Issue by Cassy-Blair** [Mmtrx/FS22_BetterContracts#115]
Aktuell ist es ja so, daß die **BCUserDefined.xml** in den Ordner **"FarmingSimulator2022\modSettings"** eingefügt werden muß, was dazu führt, daß die **BCUserDefined.xml** für alle Maps gültig ist. Wenn ich nun aber **Map A** mit der **BCUserDefined.xml** spielen möchte und **Map B** oder **Map C** usw. **nicht** mit der **BCUserDefined.xml** spielen möchte, dann muß ich jedesmal erst die **BCUserDefined.xml** löschen und später wieder neu einfügen. Hilfreicher wäre es hier, wenn die **BCUserDefined.xml** in Unterordner für die jeweils aktivierte Map abgelegt werden würde

Als Beispiel wie ich mir das vorgestellt habe hier mal wie es bei Courseplay gelöst ist für die jeweiligen Kurse auf verschiedenen Maps
![grafik](https://user-images.githubusercontent.com/87262647/223093626-42593e04-d75f-4454-8851-3e2e985cf4ea.png)

**Comment by Mmtrx** [comment]
is integrated in latest [release](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.7.6).
