### ISSUE TITLE
Ernte Missionen 

### ISSUE THREAD

**Issue by Fendt939** [Mmtrx/FS22_BetterContracts#117]
Hallo 

Wir spielen schon etwas länger mit dem Mod Better Contracts auf der Hof 22 vom Hot online Team. Seit der Neuen Version von Better Contracts haben wir folgendes Problem:

- Erntemissionen werden nicht generiert wobei Felder erntereif sind, einige Zeit später wird das Erntereife Feld als Pflug mission 
generiert

z.b. Feld 117 ist mit Sonnenblumen erntereif mann hat auch den Zeitpunkt zum ernten dieser Fruchtart, aber sobald man auf aktualisieren klickt wird die 117 als Pflugmission generiert! Wir haben den Generationsintervall deshalb von stündlich auf 3 stunden hochgestellt aber der Fehler tritt immernoch auf.

Woran liegt das?

MfG

[log.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/10967345/log.txt)

**Comment by Timmeey86** [comment]
Gleicher Effekt auf "Irgendwo in Thüringen III", allerdings auch schon mit älteren Versionen von Better Contracts: Im September z.B. 3 Erntemissionen und 40+ Pflugmissionen auf erntereifen Feldern. Der Effekt tritt allerdings auf unseren Servern mit Attingham Park und Brzozowka nicht auf. Evtl ist das ein Map-Effekt, der von Better Contracts verstärkt wird.

**Comment by Fendt939** [comment]
> Gleicher Effekt auf "Irgendwo in Thüringen III", allerdings auch schon mit älteren Versionen von Better Contracts: Im September z.B. 3 Erntemissionen und 40+ Pflugmissionen auf erntereifen Feldern. Der Effekt tritt allerdings auf unseren Servern mit Attingham Park und Brzozowka nicht auf. Evtl ist das ein Map-Effekt, der von Better Contracts verstärkt wird.

Okay also bin ich schonmal net der einzige ja habe mal das Team der Map angeschrieben aber die meinten es läge am better Contracts und soll somit hier mal den Modder anschreiben. Aber danke das du das gleiche problem hast

**Comment by Mmtrx** [comment]
Hm,
kann das was mit dem neuen patch 1.9 zu tun haben? Aber @Timmeey86 sagt ja, dass er das auch schon früher beobachtet hat.

Ich nehm mal an, dass ihr lazy Farmer und Ernten auf "aktiviert" habt.

Um den Fehler ggf einzugrenzen: könntet ihr mal je einen screenshot
- vorher (erntereifes Feld, noch nicht als Mission verfügbar) und 
- nachher ("X" auf Vertragsmenu -> neue Verträge erzeugen) 

hier hochladen?

**Comment by Fendt939** [comment]
> Hm, kann das was mit dem neuen patch 1.9 zu tun haben? Aber @Timmeey86 sagt ja, dass er das auch schon früher beobachtet hat.
> 
> Ich nehm mal an, dass ihr lazy Farmer und Ernten auf "aktiviert" habt.
> 
> Um den Fehler ggf einzugrenzen: könntet ihr mal je einen screenshot
> 
> * vorher (erntereifes Feld, noch nicht als Mission verfügbar) und
> * nachher ("X" auf Vertragsmenu -> neue Verträge erzeugen)
> 
> hier hochladen?

klar können wir oder ich das machen um das Problem zu schildern

**Comment by Fendt939** [comment]
Also ich habe das bei mir auf der Map Hof 22 getestet alzu lange musste ich garnicht mal warten.

Feld 100 ist erntereif s.h. Screenshots wird aber als Pflüge missionen generiert!

Naja mit dem neuen Patch glaube ich nicht da wir auch vorher seit deiner neusten Verson und in den Vorgängern auch schon solche probleme hatten

![Screenshot (52)](https://user-images.githubusercontent.com/43754864/225015013-347a35f3-5bd6-44e0-8d77-0104cde06e5d.png)
![Screenshot (53)](https://user-images.githubusercontent.com/43754864/225015033-50bbef63-54bf-46ce-8db8-bd4bd8f8682a.png)
![Screenshot (54)](https://user-images.githubusercontent.com/43754864/225015042-de52dcad-89cf-4cd2-b9ce-ebc205ffa317.png)
![Screenshot (55)](https://user-images.githubusercontent.com/43754864/225015052-3ac5f798-5b3e-4790-86f6-4cf0bd728228.png)
![Screenshot (56)](https://user-images.githubusercontent.com/43754864/225015054-50135f94-7b1f-46dd-b59d-32eb1aca41df.png)
![Screenshot (57)](https://user-images.githubusercontent.com/43754864/225015062-1d43430a-5aa6-432c-859e-888266682917.png)
![Screenshot (58)](https://user-images.githubusercontent.com/43754864/225015072-453b4888-b759-4379-9115-b05ffcc56060.png)

**Comment by Mmtrx** [comment]
Danke für die Screenshots. Ich würde mal Faule Farmer anschalten, und den Unterpunkt Ernten. Außerdem bitte Debug anschalten, ist direkt eine Zeile über Faule Farmer.

Im Basisspiel ist ja bekannt, dass es nur wenig Ernteaufträge generiert, insbesondere für zusätzliche Fruchtsorten. Interessant wäre auch zu testen, ob ihr ohne die Mod mehr Ernteaufträge bekommt.

**Comment by Fendt939** [comment]
> Danke für die Screenshots. Ich würde mal Faule Farmer anschalten, und den Unterpunkt Ernten. Außerdem bitte Debug anschalten, ist direkt eine Zeile über Faule Farmer.
> 
> Im Basisspiel ist ja bekannt, dass es nur wenig Ernteaufträge generiert, insbesondere für zusätzliche Fruchtsorten. Interessant wäre auch zu testen, ob ihr ohne die Mod mehr Ernteaufträge bekommt.

Okay werden wil mal so einstellen mal schaun ob es funktioniert. 

Vielen Dank

**Comment by Mmtrx** [comment]
@Timmeey86,
geht leider nicht. Die mod macht keine eigene Missionsgenerierung, sondern startet nur die Routine des Basegame. mit der Aufträge generiert werden. Zum Testen kann man auf der Konsole `bcFieldGenerateMission n` eingeben, (n ist die Feldnr). Debug muss dazu bei Spielstart eingeschaltet sein, also vorher einschalten, speichern, neu starten.

**Comment by Fendt939** [comment]
Hallo 

Ich sollte mich ja nochmal mit dem Test melden, und zwar mit den einstellungen die du mir geschrieben hattest ist es genauso. 
Log habe ich mit angehängt Debug modus war auch aktiv, vllt hilft es dir den Fehler zu finden. 

MfG
[log.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/10984576/log.txt)


![Screenshot (64)](https://user-images.githubusercontent.com/43754864/225442660-3a5feda9-a941-4b42-bb2a-8b16c223a651.png)
![Screenshot (65)](https://user-images.githubusercontent.com/43754864/225443563-efba4714-c3ce-40d1-823e-a1cddbe908d2.png)
![Screenshot (66)](https://user-images.githubusercontent.com/43754864/225443921-294d0111-1a64-4d5b-b95c-3e91d129ff1d.png)
![Screenshot (67)](https://user-images.githubusercontent.com/43754864/225444121-60e5a2f4-4481-4242-9d71-ec88c9892c40.png)
![Screenshot (68)](https://user-images.githubusercontent.com/43754864/225444302-ae711deb-c6b1-4ea4-9b38-d2ef255ccc08.png)
![Screenshot (69)](https://user-images.githubusercontent.com/43754864/225445070-54f7c3a0-4c55-4131-9894-7fafb9fbc0e0.png)
![Screenshot (70)](https://user-images.githubusercontent.com/43754864/225445299-c592fcd7-c495-498b-9573-c5f543822939.png)

**Comment by Mmtrx** [comment]
Hm, könnte daran liegen, dass die Felder in deinen Beispielen alle nicht gepflügt sind. Die Basegame-Funktion zum Erzeugen von Aufträgen macht in etwa folgendes:

für alle Felder (in random Reihenfolge):
- wenn Feld einem Spieler gehört oder Feld schon eine Mission hat --> nächstes Feld
- probier der Reihe nach. einen Auftrag folgendes Typs zu erzeugen:
 		2 plow
		3 cultivate
		4 sow
		5 harvest
		6 weed
		7 spray
		8 fertilize
- wenn max Anzahl Aufträge oder max Anzahl Versuche erreicht --> Ende

D.h. wenn der Generator ein Feld mit "Pflügen notwendig" erwischt, erzeugt er eine Pflug-Mission und geht weiter zum nächsten Feld.
Wie die Situation "erntereifes/ ungepflügtes Feld" entstehen konnte, weiß ich nicht. Du kannst mal versuchen, das zu reparieren, imdem du (vor der Neugenerierung der Aufträge) das Beispielfeld mit EasyDev auf gepflügt setzt:
1. "Feldfrucht festlegen" Haken klicken
![fsScreen_2023_03_16_08_25_24](https://user-images.githubusercontent.com/86842734/225545452-9d19871f-6cd7-447b-910a-a023e6fcdefa.png)
Dann:
![117plow](https://user-images.githubusercontent.com/86842734/225545589-a4183a56-745d-4163-89e0-d4ed228b6e7f.png)

PS: Um neue Aufträge zu erzeugen, musst du nicht vorher immer alle löschen ("C"), sonden kannst mit "X" immer neue dazu generieren (bis zur Maximalzahl Aufträge).

**Comment by Fendt939** [comment]
Hallo 

Dankeschön ich habe das jetzt mal so gemacht wie du es sagtest und siehe da es werden nur noch Erntereife Felder generiert, habe alle Felder auf gepflügt gesetzt und weizen auf Erntereif und es kommen nur Erntemissionen. D.h. wir müssten bei uns auf dem Server mal alle Felder auf gepflügt setzten ? dann sollte das funktionieren?

**Comment by Mmtrx** [comment]
Ja, das sollte auf jeden Fall helfen.
Wie gesagt, normalerweise tritt dies gar nicht auf, auch nicht auf einem neu gestarteten Spielstand mit der Hof 22😉

**Comment by Fendt939** [comment]
> Ja, das sollte auf jeden Fall helfen. Wie gesagt, normalerweise tritt dies gar nicht auf, auch nicht auf einem neu gestarteten Spielstand mit der Hof 22😉

Okay ja vllt. liegt es auch an irgendein Mod weiß ich nicht. Wir werden das mal so machen und falls das geholfen hat ist es klasse andernfalls würde ich mich erneut bei dir melden. 

Danke das du das Problem gleich angenommen hast und eine Lösung gefunden hast. 

MfG

**Comment by Timmeey86** [comment]
> Die Basegame-Funktion zum Erzeugen von Aufträgen macht in etwa folgendes:

Das erklärt einiges, ich meinte nämlich, den Zustand auch schonmal im Basegame (auf einer Mod Map) gehabt zu haben.
Wäre es grundsätzlich möglich, sich in die Überprüfung für die Missionen einzuklinken, um z.B. bei der Abfrage, ob Pflügen möglich ist, false zurück zugeben, wenn das Feld erntereif ist?

**Comment by Mmtrx** [comment]
Wäre grundsätzlich natürlich möglich. Man müsste die komplette Methode `MissionManager:generateNewFieldMission(field)` überschreiben. So etwas macht man als Script-Modder allerdings äußerst ungern.

**Comment by Timmeey86** [comment]
Ich war so naiv zu glauben dass es sowas wie  `:isPlowingPossible(field)` oder ähnlich geben würde 😂

**Comment by Mmtrx** [comment]
Mach ich dann mal zu hier.
