### ISSUE TITLE
Mehrere Aufträge angenommen 

### ISSUE THREAD

**Issue by Fendtfan84** [Mmtrx/FS22_BetterContracts#119]
Hey habe auf der irgendwo in Thüringen 3 v.2.0 
Mehrere Aufträge angenommen eingestellt sind 4 Aufträge gleichzeitig.
Better Contracts version 1.2.7.5
Es war noch ein Grubber Auftrag aktiv.
Dann noch 3 dünge Aufträge angenommen, davon wurde nur der letzte als aktiv geführt. 
Dieser konnte auch nur ausgeführt und abgeschlossen werden.
Die anderen beiden Düngeraufträge sind nicht mehr zu finden.
Ist das ein Problem bezüglich dem fs22?
Die log sende ich später wenn ich wieder am PC bin.
[LOG](https://gist.github.com/Fendtfan84/71f9cda88b459f90865d410d8030e8b1)

**Comment by Fendtfan84** [comment]
Genau hat noch 3 Düngeraufträge angenommen.
Die zwei sind sofort verschwunden und nur der dritte ist zum ausführen geblieben.
Das Spiel wurde nicht verlassen.

**Comment by Mmtrx** [comment]
.. expired
