### ISSUE TITLE
Calculated harvest number (to deliver) is incorrect since last FS patch

### ISSUE THREAD

**Issue by Jagerone** [Mmtrx/FS22_BetterContracts#12]
In last FS patch they fixed how much you have to deliver from harvesting job - it is now much more and only a little bit you get to keep. When you display how much you still have to deliver for the job, this number is too low now (for about 4% of the job). So when I deliver the number of Liters you predict, the contract is 96% done and the rest is counted as negative in the mod.

**Comment by Jagerone** [comment]
FS22 1.3.1.0, Mod version 1.2.0.2

**Comment by Mmtrx** [comment]
Hi,
That was fixed in latest mod release https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.3.0
