### ISSUE TITLE
New contracts display bug

### ISSUE THREAD

**Issue by westor7** [Mmtrx/FS22_BetterContracts#121]
Hello,

When i click on `New contracts` button 2 times , the 1st one it doesn't doing anything but in the 2nd it gives me the ability to Accept a contract that is not listed, also borrow items button is either available, of course there is an error in console.

![](https://i.imgur.com/bttgKGu.jpeg)

- Thanks!

**Comment by Mmtrx** [comment]
Hi, I can look into that. Could you pls upload your log, and maybe also a zip of the savegame folder?

**Comment by Mmtrx** [comment]
.. expired
