### ISSUE TITLE
AI worker start errors on tedder

### ISSUE THREAD

**Issue by westor7** [Mmtrx/FS22_BetterContracts#122]
Hello,

I was trying to set an AI worker to start tedder on a field and then errors occurred, i stopped it manually because the errors were flooding the console.

Log.txt file: [log.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/11149574/log.txt)

- Thanks

**Comment by Mmtrx** [comment]
Hi,
the message `dataS/scripts/vehicles/ai/AIVehicleUtil.lua(403) : attempt to perform arithmetic on local 'rotMax' (a nil value)
` looks as if s.th. is wrong with the tractor (or the tedder) you're trying to make the helper work with.
Is one of them (tractor / tool) a mod?
Does this happen also with basegame tractors / tedders?

**Comment by Mmtrx** [comment]
.. expired
