### ISSUE TITLE
Lazy NPC - plowing/cultivate

### ISSUE THREAD

**Issue by Slain9178** [Mmtrx/FS22_BetterContracts#123]
Hi Mmtrx,

I would like to ask if it would be possible to add a separate setting for plowing in the Lazy NPC menu? After completing the corn, potato and sugar beet harvest missions, the "need to plow" status disappears and only the cultivation mission for that field appears in the contracts menu. Or better, maybe try to add script with something like "force plow after root crops"? But I guess splitting cultivation and plowing would be still necessary?

Thank you so much for your amazing work with developing this incredible mod.

**Comment by Mmtrx** [comment]
Hi,
sure a separate setting just for plowing is possible, will think about that for next update. 
I had not recognized that fields with a completed corn/ potato/sugar beet harvest mission get plowed automatically. Hm, interesting..

**Comment by Mmtrx** [comment]
"Harvested root crops force plowing" is not a rule in the base game. In the latest [version](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.8.3) of BC you can switch that on.

I left the plow/ cultivate switch, because with the above option enough plowing missions will be generated (if lazyNPC/ plowCultivate switch is on).

**Comment by Gordon-Dry** [comment]
It seems the setting "bc_forcePlow" resets to "false" every time I load the savegame.

**Comment by Mmtrx** [comment]
Thank you for testing. Seems I forgot to update my save function with the new settings.😬
Will correct that tomorrow😀

**Comment by Gordon-Dry** [comment]
For some reason the state of forcePlow is still not saved (or read when loading) with v1.2.8.4

**Comment by Gordon-Dry** [comment]
... and it triggers a call stack, I just fround it:
```
2023-10-10 17:48   Error (G:/Admin/Documents/My Games/FarmingSimulator2022/savegame1/FS22_BetterContracts.xml): Failed to validate xml path 'BetterContracts#ferment' for 'BetterContracts'. Path not registered.
2023-10-10 17:48 LUA call stack:
  dataS/scripts/xml/XMLFile.lua (384) : printCallstack
  dataS/scripts/xml/XMLFile.lua (255) : getValueType
  =G:/Admin/Documents/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/betterContracts.lua (248) : getValue
  =G:/Admin/Documents/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/betterContracts.lua (619) : readconfig
  =[C] (4294967295)
  =G:/Admin/Documents/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/scripts/RoyalMod.lua (314) : xpcall
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  =G:/Admin/Documents/My Games/FarmingSimulator2022/mods/FS22_SeeBales/scripts/RoyalMod.lua (314) : BaseMissionloadMapFinished
  dataS/scripts/FSBaseMission.lua (1689) : loadMapFinished
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/i3d/I3DManager.lua (175) : asyncCallbackFunction
2023-10-10 17:48   Error (G:/Admin/Documents/My Games/FarmingSimulator2022/savegame1/FS22_BetterContracts.xml): Failed to validate xml path 'BetterContracts#forcePlow' for 'BetterContracts'. Path not registered.
2023-10-10 17:48 LUA call stack:
  dataS/scripts/xml/XMLFile.lua (384) : printCallstack
  dataS/scripts/xml/XMLFile.lua (255) : getValueType
  =G:/Admin/Documents/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/betterContracts.lua (249) : getValue
  =G:/Admin/Documents/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/betterContracts.lua (619) : readconfig
  =[C] (4294967295)
  =G:/Admin/Documents/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/scripts/RoyalMod.lua (314) : xpcall
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  =G:/Admin/Documents/My Games/FarmingSimulator2022/mods/FS22_SeeBales/scripts/RoyalMod.lua (314) : BaseMissionloadMapFinished
  dataS/scripts/FSBaseMission.lua (1689) : loadMapFinished
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/i3d/I3DManager.lua (175) : asyncCallbackFunction
2023-10-10 17:48   Warning: [BetterContracts] ferment:setValue() called with nil value
2023-10-10 17:48   Warning: [BetterContracts] forcePlow:setValue() called with nil value
```

**Comment by Mmtrx** [comment]
Sorry, I should have tested yesterdays hotfix myself. I also needed to add the 2 new settings to the `registerXML()` function (in betterContracts.lua).
Here's the 2nd [hotfix](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.8.5). Please test again.

**Comment by Gordon-Dry** [comment]
Works now. If the values are not yet in the xml the values have to be set again, but this time it works when loading.

**Comment by rohne83** [comment]
Is this feature still caring about the setting whether plowing is required at all? I always turn that off of course, so in my savegames neither me nor the NPCs never have to use the plow.
The logic of Giants to force plowing after some crops is totally unrealistic.

**Comment by Mmtrx** [comment]
Ja, das base game setting "Pflügen nötig" wird natürlich berücksichtigt😉.
