### ISSUE TITLE
Field Prices Not Discounted

### ISSUE THREAD

**Issue by razmachaz69** [Mmtrx/FS22_BetterContracts#124]
Hi,

Not sure if anyone else has this issue but field prices say they are discounted (E.g $98k to $64k - 35% discount) but when I click to buy it, it says 'Do you want to buy for $98k.

So its showing it *should* be discounted but its not actually letting me pay that for it?

No other mods affecting field prices installed.
![image](https://user-images.githubusercontent.com/130298327/230779079-34a3551d-fe73-495c-9679-4fbb7c66b9ee.png)

**Comment by Mmtrx** [comment]
Are you using the latest Version [1.2.6.7](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.7.6) ?
That sounds like an old bug, #88 .

**Comment by razmachaz69** [comment]
Im using the one through the in game menu, looks like its the older version 1.2.6.2!
