### ISSUE TITLE
Impossible to undertake a plowing contract

### ISSUE THREAD

**Issue by uded** [Mmtrx/FS22_BetterContracts#126]
Tested with multiple custom maps and equipment - it allows me to start plowing, but there is no visible result or progress with the contract. Happy to provide debug or any other information, but need some guidance with that.

**Comment by Mmtrx** [comment]
Hi,
can you replicate that with a basegame plow?

**Comment by uded** [comment]
Yes, all plows give me the same result. Regardless if they are coming from the mod hub or the original in-game equipment. Also, I've tested it on maps downloaded from different sources (West End, Landdownunda, Edgewater Sask) and one of the included maps (Haut-Beyleron).

**Comment by uded** [comment]
Removing all mods fixes the problem, so it does seem like a conflict. Unfortunately warnings or errors, makes it difficult to debug.

**Comment by Mmtrx** [comment]
I don't know the length of your mod list. One good method to isolate mod conflicts is to successively half the list. Then start up game, see if error still there, continue halving the remaining mod list. So you can rather quickly narrow it down.
