### ISSUE TITLE
Missis nach 1ms weg

### ISSUE THREAD

**Issue by AK-Baldow** [Mmtrx/FS22_BetterContracts#128]
Hi,
Ich mal wieder. Da zurzeit fast alle Missis nach 1ms weg sind (Ka welche). Spritzen und Düngen halten länger.
Wäre es nicht möglich eine Option einzubauen wo die Missis Automatisch annimmt ohne extra ins Menü zugehen.
Also missi da und gleich angenommen. 

Gruß Baldow

So nach paar versuchen:
Spritzen, Düngen, Säen, Unkraut bekämpfen (Striegeln), Gras mähen  ------ Bleiben länger
Pflügen, Grubbern, Kalken (mit deinem Mod)  ---- verschwinden sofort.

Ernte Missis ist wie bekannt, wenn erntereif und muss gepflügt werden verfault es. Ohne pflügen ist Ernten länger verfügbar.

**Comment by Mmtrx** [comment]
Ist das noch akut? Falls ja, den Issue bitte wieder öffnen
