### ISSUE TITLE
Request for enhancement stone collection missions

### ISSUE THREAD

**Issue by LawAcidFlash** [Mmtrx/FS22_BetterContracts#13]
Hello Mmtrx,

here an idea for enhancement.
You think it would be possible to add "Stone collection" missions to the game?

We are playing with stones on our dedicated and the npc fields are full with stones and we never got missions to remove them.

I kow there must be a logic to see if stone option is on or off and to check if there are stones on the field and so on.
But maybe you know how to solve this.

Best regards and a nice Easter Festival.

**Comment by Mmtrx** [comment]
I can look into that - but it'll take some time ..
