### ISSUE TITLE
Danish transl

### ISSUE THREAD

**Issue by Michaelbjerg21978** [Mmtrx/FS22_BetterContracts#130]

**Comment by Michaelbjerg21978** [comment]
I translateted your great mod to danish.
[l10n_da.zip](https://github.com/Mmtrx/FS22_BetterContracts/files/11277581/l10n_da.zip)

**Comment by Mmtrx** [comment]
Danke!
Will integrate that in next Release.

**Comment by Mmtrx** [comment]
Done. Is in Rel 1.2.7.9. As well as ModHub.
