### ISSUE TITLE
Insta Ferment 240cm PackedBales 

### ISSUE THREAD

**Issue by Mmtrx** [Mmtrx/FS22_BetterContracts#131]
(Continues discussion from #118)
@sashaman,
Also dem packed 240 bale `isMissionBale = true` zu setzen, wenn der Multipack D14 ihn ablegt, reicht nicht, da der PackedBale `supportsWrapping` auf false hat.
![missionBale](https://user-images.githubusercontent.com/86842734/233418753-79aea24d-547f-4418-a354-14ba09c11ad0.png)
Wenn ich das auf true setze, lässt er sich zwar wickeln, aber die ganze Gärmechanik springt nicht an.

Meine Tests zeigen auch, dass der Kuhn SW4014 von M+ zwar einen "normalen" 240er Grasballen wickelt, aber weder einen kleinen 120er, noch den 240er PackedBale.

Bist du sicher, dass du aus einem 240 **PackedBale** schon mal Silage gemacht hast? Und welchen M+ fillType hatte der (Frischgras, Gras aufbereitet, Gras angewelkt)?

**Comment by sashaman** [comment]
120er kenn ich kein gerät das die wickeln kann, hat bisher wohl noch niemand gemodded :P
aber der m+ multipack legt gras/getreideschwad/etc 240 packedBales ab, die der m+ sw4014 wickelt. 
nach dem aufschneiden dieser 240er hat man einzelne, vergorene 120er. 

das funktioniert aber für missionen nur begrenzt, weil bei heu machts keinen unterschied, die kann man problemlos für missionen abliefern weil sie ja nicht gewickelt/vergoren werden. 
der multipack legt jetzt aber isMissionBale false ab, deshalb vergären die gras/silage ballen nicht instant und man könnte die mission erst nach der gärzeit abschließen

**Comment by sashaman** [comment]
![image](https://user-images.githubusercontent.com/1388895/233684726-8febf63b-07de-458c-afa4-ab5dcfc3ca02.png)
![image](https://user-images.githubusercontent.com/1388895/233684749-e137b12a-d0dd-4069-8629-a2c86795d47b.png)
![image](https://user-images.githubusercontent.com/1388895/233684770-b8b1f9da-a38e-4926-a18f-0d677c7404e9.png)
![image](https://user-images.githubusercontent.com/1388895/233684797-62c9dcf0-8276-454b-9a80-d02bf6600806.png)
![image](https://user-images.githubusercontent.com/1388895/233684821-ea95fbb0-ef5e-4ed3-9495-f47cefa1c741.png)
![image](https://user-images.githubusercontent.com/1388895/233684846-995951a1-352e-4963-ae4e-0fa7d8f42edf.png)

**Comment by Mmtrx** [comment]
Ok, jetzt hab ich's glaub ich. Du kannst ja mal die letzte [Version](https://github.com/Mmtrx/FS22_BetterContracts/commit/39cdcbd5cd687159d7668d079947652f92af559c) testen. Release mach ich dann erst mit dem nächsten update, Zippen kanst du ja wahrscheinlich selbst 😉 

Allerdings macht die Mod beim Erzeugen des PackedBale  im arcusin Multipack nur dann `missionBale`an, wenn mindestens einer der kleinen 120er Bales auch ein missionBale war. Bei Getreideschwad wird das schwierig, denn es gibt die Ballenmissionen ja nur für Grasfelder, oder?

**Comment by sashaman** [comment]
für gras vollkommen ausreichend, 
allerdings beim entladen vom multipack logspam :(
```
Error: Running LUA method 'update'.
dataS/scripts/vehicles/specializations/BaleLoader.lua(2346) : attempt to index local 'balePlace' (a nil value)

```

**Comment by Mmtrx** [comment]
Ok, seh ich mir an. Kannst du mal die ganze Log hochladen, oder zumindest plus/ minus 20 Zeilen um die Fehlermeldung?

**Comment by sashaman** [comment]
da is sonst nix, gar nix.... 
ballen ablegen ZACK BÄM BUMM

**Comment by sashaman** [comment]
habs jetzt nochmal probiert. 
der hat jetzt entgeladen, und etwa 2-3 sekunden danach error
![image](https://user-images.githubusercontent.com/1388895/233779596-c4868e6d-aab7-449e-961a-e678534894cc.png)
![image](https://user-images.githubusercontent.com/1388895/233779603-48e30799-7383-425e-8dbb-6236d09d8b87.png)
[log.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/11301135/log.txt)

**Comment by Mmtrx** [comment]
Ok, hab einen einfacheren Weg gefunden. Man muss aber den Multipack von Maize+ (oder von BC 😉) zum Erzeugen der packedBales nehmen: [Fix](https://github.com/Mmtrx/FS22_BetterContracts/commit/f63d7e1bd1bf432a2536f643f9ff8cd7a0846919)

**Comment by sashaman** [comment]
perfetto! absolutely fabulous! großartig! 
funktioniert bis jetzt anstandslos. 
ich danke dir von herzen <3 
🥇
