### ISSUE TITLE
Field Progress question

### ISSUE THREAD

**Issue by mrPassion78** [Mmtrx/FS22_BetterContracts#132]
like the pic. shows, 
![InkedfsScreen_2023_04_17_14_44_02](https://user-images.githubusercontent.com/40406761/233855464-f06f6314-e5b5-4cec-bcee-2191e5d6736e.jpg)
it gives a percentage of field progress, and i found out that, unless it is at 100%, i cannot complete my mission, 
Even after delivering the needed crops, it will not let me complete it.
I had to cheat and reset the field to the state of harvested in order to get it to work.
i have set my delivery percentage to 94%, and with the combine harvesting, there is always some crops left standing, and not worth turning around for.
Is there a way to deactivate this fieldprogress or at least adjust it so it maches the setting for the delivery of goods?

**Comment by Mmtrx** [comment]
Hi,
that's how the basegame harvest mission completion is defined:
- complete the field to 100%  -> this gives 80% total mission completion
- deliver 94% (or whatever value you chose in BC settings) -> gives the other 20% of total mission completion

Normally, it shouldn't be a problem to harvest / mow the complete field (even if you leave some crop in the corners). If you are saying that field completion is only about 60%, although you harvested most of the field, there must be s.th. wrong with the field definition (happens sometimes with mod maps).

There currently is (and frankly will be) no way to soften the 100 field completion requirement. The contracts should remain sort of challenging.

**Comment by mrPassion78** [comment]
hi there, thnx for explaining it. , and the field progress bar was stuck at 99 or 98% even after i deliverd all the goods needed, and after cheating the field to the harvest state, i could  get the hard earned money for it.. LOL.
i will play more missions on the map Somewhere in Thuringia 3 By Kastor, and see what commes out of it.. 
Again thnx so much for the answer and ofcourse the mod itself.
