### ISSUE TITLE
feature request have v 1.2.7.8

### ISSUE THREAD

**Issue by NathanS-8500** [Mmtrx/FS22_BetterContracts#133]
Hey, Mmtrx, I am in love with Better Contracts for FS22. I have zero issues with it. Thing of it is, this release allows for instant fermenting of wrapped silage bales. I'm one of those players that likes to play realistically or unrealistically. I looked everywhere in this version for a way to revert back to base game silage bales that need to ferment from 0 - 100% to be silage. Even rooted around in the files a little looking for an identifier to change to get base game silage bales back. My feedback is this.

For us players that like to switch up gameplay and play how we want, I think this Better Contracts mod ought to have a setting in the Better Contracts settings tab called

Instant fermenting and a button beside it saying On or Off. Code in the FS22_BetterContracts.xml that is created for savegames when mod is loaded in could show something like this:

<BetterContracts ...>
  <lazyNPC ...>
  <instantFermenting="true"/>
  <generation interval.../>
<BetterContracts>

When instant fermenting is on, it shows ="true". When it's off, ="false=.

Could you see what you could do about implementing this? I still like the idea of waiting on bales to ferment, but don't want to lose access to all updates and changes thus far to the mod. If this were added, I would get that version of the mod in a hurry.

**Comment by Mmtrx** [comment]
Hi @NathanS-8500,
thanks for your feedback. You are aware that the wrapped grass bales do not "insta-ferment" automatically? Only if you manually touch them with the "R" key. (So it's up to you to wait for the standard fermenting time, or use the shortcut.)

I will consider your suggestion anyhow, to make this customizable via the BC settings page.

**Comment by NathanS-8500** [comment]
Hey, Mmtrx, sorry for my delayed reply, but I now see what you meant by the shortcut to instant-ferment silage bales. I think my whole deal out of this was I was running a different previous version of the mod and wasn't seeing it anywhere. But now that I have v 1.2.7.8 back, I can choose to let the bales ferment themselves, or use the instant-ferment shortcut. My suggestion from earlier can still be on your list to further update and change the mod. I would definitely get it if the change was adapted and put into the BC settings page. But thanks anyhow. You can close my issue as I am done with it after you read.
