### ISSUE TITLE
Feldkäufe mit Rabatt Fehler

### ISSUE THREAD

**Issue by Fendtfan84** [Mmtrx/FS22_BetterContracts#134]
Hallo,
auf der The Valley The Old Farm Map kommt bei der BC Einstellung Feldkäufe mit Rabatt folgende Fehler Meldung:
Error Runing LUA Method mouseEvent.
Wenn ich in BC die Einstellung Rabatt für Feldkäufe deaktiviere kommt kein Fehler in der Log.
Ich hoffe dieses Problem lässt sich beheben.
Den ohne deinen BC Mod machen mir die Missionen keinen Spaß.
Anbei [die log](https://gist.github.com/Fendtfan84/bbd474c2b5ffc9e2478005f403c3b496) benutze BC 1.2.7.8.

**Comment by Mmtrx** [comment]
Hi,
da hast du tatsächlich noch n echten Programmierfehler gefunden! Probiers mal hiermit: 
[FS22_BetterContracts.zip](https://github.com/Mmtrx/FS22_BetterContracts/files/11334275/FS22_BetterContracts.zip)
Wenns das behebt, kommt der Fix ins nächste Reease.

**Comment by Mmtrx** [comment]
Close = falsche Taste 😕

**Comment by Fendtfan84** [comment]
> Hi, da hast du tatsächlich noch n echten Programmierfehler gefunden! Probiers mal hiermit: [FS22_BetterContracts.zip](https://github.com/Mmtrx/FS22_BetterContracts/files/11334275/FS22_BetterContracts.zip) Wenns das behebt, kommt der Fix ins nächste Reease.

Hey vielen Dank für den schnellen fix. Der Fehler ist mit der von dir angefügten Version behoben.
Vielen Dank für deine Hilfe und den Support.
Wenn du in Zukunft Betatester benötigst helfe dir gerne.

Schöne Grüße vom glücklichen FendtFan aus Südhessen
