### ISSUE TITLE
Kleinere Rabatt Schritt größen

### ISSUE THREAD

**Issue by PapaTim68** [Mmtrx/FS22_BetterContracts#136]
Es wäre schön, wenn es kleinere Schritt Größen für den Rabatt auf Felder geben könnte.
So ist momentan der kleinste Rabatt 25% nach minimal 5 Auftragen erreicht.
Also bei einem Feld nach ~1Jahr mit Bearbeitung aller Missionen der maximal Rabatt erreicht ist.
Es wäre schön, wenn die Prozentschritte für einen solchen Rabatt evtl. auf 1% Schritte reduziert werden, während die Anzahl der Missionen um den maximalen Rabatt zu erhalten erhöht werden.

**Comment by Mmtrx** [comment]
Moin,
das kannst du relativ einfach ändern: in Datei scripts/settings.lua ab Zeile 191 statt
```
		{name = "discPerJob",
		values = {.05,.08,.11,.14},
		texts = {"5 %","8 %","11 %","14 %", },
		default = 1,
```
folgendes eintragen:
```
		{name = "discPerJob",
		min = .01, max = .14, increment = .01, unit = true,
		default = 1,
```
Anzahl der max für Rabatt gezählten Missionen kannst du im nächsten Abschnitt `{name = "discMaxJobs",
` entsprechend erhöhen.

**Comment by Mmtrx** [comment]
Ja klar, kommt ins nächste Release 😉
