### ISSUE TITLE
Plowing and more 

### ISSUE THREAD

**Issue by Michaelj15** [Mmtrx/FS22_BetterContracts#137]
Hi Mmtrx,

It's me again ;)
After a lot of pleasured farming with the contacts mod I have some new ideas and questions. I know we get a lot for your hard work, so it's just a suggestion, no pressure at all :)

I have played with some different settings, especially with the extra reward option in the settings menu. It's a big step forward to set the reward a little bit higher, but maybe it's possible to have a separate correction on each mission type reward. When I calculate the hire prices in real life, the plow contracts are not correct. With plowing it takes a lot more time to finish a field, so the hire hours of the worker are a lot more. Maybe it's possible to set these rewards higher? 

Another idea is maybe for the new swathing mod.
https://www.farming-simulator.com/mod.php?lang=en&country=nl&mod_id=267323&title=fs2022

 With the swathing mod, it's now possible to harvest some grain fruits and swath these fruits again with a swather. Like they do in Canada and country's like that, for a higher field rate. Unfortunately it's not possible to use the mod with a contract mission. Is there a possibility to make a code to use this separate swathing mod? I have noted the author of the swathing mod, but he doesn't have any idea to make this work. I remember it wasn't even possible to pickup swath with a forage wagon a year ago in a harvest mission, but after a new mod it was possible. Maybe you could use some of this codec? 
https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=223930&title=fs2022

Third question is to make a extra filter to sort all contracts from highest price to lowest. I know it's already possible to sort contracts in the net profit tab, but this isn't always the real profit. For example when you have bought already a lot of fertilizer, you just want the highest contracts for a big profit. In this case you don't want to filter but just see to highest contacts on top of the screen. 

Fourth question, keep doing what you do, and keep to good updates coming :)

**Comment by Mmtrx** [comment]
Ok,
that's 3 suggestions for future enhancements. I will consider them - thanks for your ideas!

**Comment by Mmtrx** [comment]
Ok, done. See v1.2.8.0.
The plow mission reward is "hard-coded": `PlowMission.REWARD_PER_HA = 2800` (base game value was 2100). You can adjust that yourself by editing line 591 in betterContracts.lua 😀

**Comment by Michaelj15** [comment]
Wow thank you :)
Have to take a holiday tomorrow I'm afraid 😂
