### ISSUE TITLE
[MP] Rabatt wird nicht vermindert

### ISSUE THREAD

**Issue by PapaTim68** [Mmtrx/FS22_BetterContracts#138]
Moin,

wir haben gerade auf dem dedicated Server ein neues Feld gekaut und wie in #135 angesprochen funktioniert das "Zrücksetzen" des Rabatts nicht. Anderes Feld des gleichen NPCs hat immer noch den 25% Rabatt, wie bei uns als Maximum eingestellt.
![grafik](https://github.com/Mmtrx/FS22_BetterContracts/assets/29522870/5dc6d534-e57e-4ecb-a9a1-1d31b5eef419)
Hier die Rabatt-Einstellungen.

Ist momentan nicht kritisch, aber evtl nice, wenn gefixed werden könnte.

Grüße,
Tim

**Comment by Mmtrx** [comment]
Hm- konnte ich auf meinem Test Dedi nicht nachstellen, da funktioniert das Zurücksetzen der "Anzahl erfolgreiche Jobs". 

Kannst du mal prüfen, wie hoch die Anzahl vor und nach dem Kauf war? Die Zahl wird im Vertrags-Menu unter dem Bild des NPC angegeben, wenn (D)etails an ist:
![138](https://github.com/Mmtrx/FS22_BetterContracts/assets/86842734/81968bd8-2950-43e4-88db-859a2ce2c744)

Falls ihr also theoretisch vorher 11 Jobs für diesen NPC gemacht habt, reduziert der erste Feldkauf die Jobzahl auf 6. Damit gibt's aber immer noch 5 x 5% für den zweiten Kauf, und danach habt ihr noch ein "Guthaben" von 1 Job für diesen NPC.

**Comment by PapaTim68** [comment]
Ahh okay, ja das wird es sein. Wir haben sehr viele Aufträge gemacht. Diese Mechanik ist evtl. etwas schlecht erklärt dann. Ich wäre davon ausgegangen das es auf 0 Erfolgreicher auftrage und 0% Rabat sinkt nach einem Feld kauf.

**Comment by Mmtrx** [comment]
Ok, ich denk mal drüber nach, ein paar Hilfetexte einzubauen. Da könnte man das dann etwas ausführlicher erklären.
