### ISSUE TITLE
Dummes Equipment

### ISSUE THREAD

**Issue by SirGarnet** [Mmtrx/FS22_BetterContracts#139]
Hi Mmtrx,

BetterContracts erstellt immer wieder Aufträge mit inkompatibler Hardware. Besonders beliebt beim Algorithmus ist wohl die Kombination siehe der angefügten Bilder. 

1. Mähwerkshänger inkompatibel
2. Zugmaschine & Anhänger inkompatibel

![20230525190604_1](https://github.com/Mmtrx/FS22_BetterContracts/assets/3258297/03a49adb-267e-48a0-a910-b706c81f2419)
![20230525190616_1](https://github.com/Mmtrx/FS22_BetterContracts/assets/3258297/f52cf425-0b78-4f96-a3c5-d1ac63af9ba8)

Nette Aufträge sind auch: Rübenroder mit 45 m³ Volumen und einen Anhänger zum Abfahren mit 17 m³ und Ziel extrem weit weg, so das man mehr auf den Abfahrer wartet als alles andere.

**Comment by Mmtrx** [comment]
Moin,

die Fahrzeug-Kombos wählt das Spiel beim Erzeugen einer Mission aus einer vorab definierten Liste aus (missionVehicles.XML). 
Manche Karten definieren eigene Listen, manche Mods auch.
Kannst du mal deine log.txt hochladen, und ggf. auch die missions.xml aus dem entsprechenden savegame Ordner?

**Comment by SirGarnet** [comment]
Sobald ich mal wieder eine der komischen Kombination bekommen, werde ich dir die Daten zukommen lassen.

**Comment by SirGarnet** [comment]
Eine Frage noch, die missionVehicles.XML hab ich im FS22 Ordern nirgendwo gefunden, wird diese zu Laufzeit erstellt oder fehlt diese bei mir dann einfach.

**Comment by Mmtrx** [comment]
Die vom basegame ist (verschlüsselt) enthalten in dataS.gar. 
Manche mod maps bringen eine eigene mit, irgendwo in ihrer zip🤓

**Comment by tomy852** [comment]
Hallo, bei mir hab ich öfters das Problem das bei Siloballenmissionen der Xerion 4500 mit der Kongskilde Mäherkombi zur verfügung gestellt wird. Der Xerion hat aber leider gar keine Frontzapfwelle 🙁.
Spiele auf der Erlengrat von Giants.

**Comment by Mmtrx** [comment]
.. expired
