### ISSUE TITLE
Display Issue on Harvest Contracts

### ISSUE THREAD

**Issue by cwattyeso** [Mmtrx/FS22_BetterContracts#142]
Playing with Better Contracts mod this week and notice that on Harvest Contracts it's not display the Percentage Complete value for the Harvest Mission. In the Contact Screen the amount Delivered or Delivery Progress bar increases with each trailer of crop I deliver for the contract, but the Harvest Percentage bar never displays above 0%

<img width="1920" alt="2023-06-25 (1)" src="https://github.com/Mmtrx/FS22_BetterContracts/assets/13921716/e13db79b-c5b8-4522-8475-29cf8caf591e">

**Comment by Mmtrx** [comment]
Did you drive a combine across Field 8 yet? 
Because it‘s possible to start a contract with delivery of crops from elsewhere. 

If yes, is it a Mod (combine/ header )?

**Comment by cwattyeso** [comment]
Yes I harvested 3/4 of the field so far. Harvester is the vanilla in game John Deere X9 with it's in game header.

**Comment by Mmtrx** [comment]
Hm, I will need your log file please, to investigate.
Is this an MP game?

**Comment by cwattyeso** [comment]
No it's single player game. I'll grab a log file next time I'm in game. I have experienced this on two separate maps now, is it an issue if you play with mod maps rather then the Giants ones?

**Comment by cwattyeso** [comment]
Please find attached a log file from after a session today where I did a Corn Harvest Contract and again the whole contract Field Progress remained 0 and only Delivered Progress increased with each trailer delivered until suddenly Contract Complete.

[log.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/11984436/log.txt)

**Comment by Mmtrx** [comment]
Thanks for the log. 

Problem is incompatibility with FS22_HarvestMissionFix. They intercept the field completion info, and BC does not receive that info. You can see the field completion % though, by pressing right-shift-#.
![fsScreen_2023_07_08_09_11_13](https://github.com/Mmtrx/FS22_BetterContracts/assets/86842734/2dced8ea-8f8b-4857-9221-02d4dfb29c70)

**Comment by cwattyeso** [comment]
Ahhh thank you. I'll remove that incompatible mod then from use in the future.
