### ISSUE TITLE
[Suggestion] Allow to take straw from contracts

### ISSUE THREAD

**Issue by goldenshoes** [Mmtrx/FS22_BetterContracts#143]
Was thinking maybe we could get option to allow picking up contracts straw along with Better contracts mod instead of having separate mod installed?

**Comment by Mmtrx** [comment]
Thanks for suggestion. I think I'll integrate that in next rel. Should not be much effort..

**Comment by goldenshoes** [comment]
Thank you ^^

**Comment by westor7** [comment]
There is a mod that is doing that already: https://www.farming-simulator.com/mod.php?lang=fr&country=be&mod_id=223930&title=fs2022

Just mentioning in case you add this feature too then check for conflicts.

**Comment by coatsy35** [comment]
Ideally separate contracts so its not part of the harvest contract (So if you don't want to do it you don't' have too), is that possible?

**Comment by Mmtrx** [comment]
On 2nd thought, I'd rather leave things as they are:
- Players have the choice to install either one or both mods (FS22_CollectStrawAtMissions, FS22_BetterContracts)
- Btw, FS22_CollectStrawAtMissions _allows_ you to pick up the straw, of course you don't have to 😉 
- Btw2, did you know that the author of FS22_CollectStrawAtMissions is one of Giants Lead Developers?
