### ISSUE TITLE
New update regarding Forage Harvesters?

### ISSUE THREAD

**Issue by Derethevil** [Mmtrx/FS22_BetterContracts#144]
You wrote that you can now use Forage Harvesters to use for the new Göweil Stationary Balers.
Though once i use them, the bales still come out unfermented. 
I do see the option to ferment them by hand, but i feel awful to use it, since in my eyes it is a cheat, not a fix.

Or is something not working properly still?

**Comment by Mmtrx** [comment]
No, it works as designed (as you describe it).

Problem with a stationary baler is: how can it decide if a bale it produces is for a mission? The normal balers do that by checking their location when producing a bale: if it's on a field with a currently active mission, they produce a "mission bale" (insta fermented).

**Comment by Derethevil** [comment]
Okay. Still a bit confused. So even with the new update, the new stationary baler just doesn't work? Even if i plant it on the field that is to be worked on?
Or is it meant to work?

Only reason it just doesn't work is that i still have the mission active from before the update. Maybe with the next cycle?

**Comment by TobiHH78** [comment]
It works, but you have to wait until bales are fermented.

**Comment by Mmtrx** [comment]
yep - or use the "Insta-Ferment" key (R) from the F1 Menu.

**Comment by Mmtrx** [comment]
I added Göweil mission bales to my new pre-release version 1.2.8.0:
[FS22_BetterContracts.zip](https://github.com/Mmtrx/FS22_BetterContracts/files/12248378/FS22_BetterContracts.zip)
If you put the stationary baler on a field with an active bale mission, it should produce ready fermented silage bales.

**Comment by Mmtrx** [comment]
Please use latest [Release](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.8.0)
