### ISSUE TITLE
Maissilage Missionen hinzufügen

### ISSUE THREAD

**Issue by zinni97** [Mmtrx/FS22_BetterContracts#145]
Erstmal danke für den exzellenten Mod, bereichert das Spiel für mich ungemein!

Gäbe es eine Möglichkeit das Feature Maissilage Missionen implementieren? Das hat Giants ja leider versäumt..

Naheliegenderweise ohne das abladen und fermentieren im Silo. Aber eventuell wäre es möglich einfach den Filltype Chaff an einer Verkaufsstelle abzuladen wie die anderen Missions Schüttgüter?

Laut meinem limitierten Scripting Wissen könnte das einigermassen "einfach" machbar sein oder?

Bin nicht sicher ob der Vorschlag schon gemacht wurde, habe die geschlossenen Requests durchsucht und nichts gefunden, aber falls ich hier eine alte Leier thematisiere entschuldige ich mich. 

Danke fürs anschauen, Cheers!

**Comment by Mmtrx** [comment]
Ist n guter Vorschlag, Umsetzung seh ich mir gerade an. Schätze aber, dass das ne eigene Mod wird, so wie Kalk- und Walz-Missionen.

**Comment by Mmtrx** [comment]
Hab ich fertig, bin grad am Testen.. 😎

**Comment by zinni97** [comment]
Du Legende, danke! Leute wie du machen das Spiel zu dem was es ist, danke für deine Arbeit!
Falls du Hilfe fürs testen brauchen kannst bin ich dafür gerne zu haben. 

Wann denkst du ist der release? Freue mich auf jeden Fall auf den Mod.

**Comment by Mmtrx** [comment]
Guckst du [hier](https://github.com/Mmtrx/FS22_ChaffMission/releases/tag/v1.0.0.0). 😉
