### ISSUE TITLE
Sowing missions looping after finish

### ISSUE THREAD

**Issue by westor7** [Mmtrx/FS22_BetterContracts#146]
Hello,

I noticed a bug when i was playing an older map too but now it's clear happening again, it seems when i have finished sowing a field and then the rolling state the missions then re-appearing the same mission for sow again. i think here there is a bug somewhere.

Version: `1.2.7.9`
Log.txt: [log.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/12145923/log.txt)

![](https://i.imgur.com/AxWtVb0.jpeg)

Settings:

![settings 1](https://i.imgur.com/plJ7vDG.jpeg)

![settings 2](https://i.imgur.com/6BTGYL1.jpeg)

- Thanks!

**Comment by westor7** [comment]
This might be related because of https://github.com/tn4799/RollerMission/issues/4

**Comment by Mmtrx** [comment]
I could not reproduce on a std map. 
Does this happen all the time, i.e. can you always reproduce that with your savegame? Then I'd like you to upload a zip of your savegame3 folder.

Also, after completing the rolling mission (and not yet collected the pay), could you stand on the field and look at the field status info: should show fruit type, growth state 1.
Then you collect the pay in contracts menu, and watch the field status again: has the growth state / fruit type changed?

**Comment by westor7** [comment]
Sorry for late response, i have report that bug in RollerMission git too, and i provide a video there how is that happening, the thing is that if i disable the BetterContracts mod this loop bug is not happening, so my thought is that BetterContracts is not compatible with RollerMissions.

**Comment by Mmtrx** [comment]
Identified as bug in RollerMission mod. Will be handled over there.
