### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by BigDBudda** [Mmtrx/FS22_BetterContracts#15]
Hi, just a question. is it possible to change the money you get as reward. some jobs only give like 800€ for plow. for playing in realtime with i small plow it´s to low reward.

Thanks for an anwser :)

**Comment by Mmtrx** [comment]
Hi,
that's possible (copied from an earlier answer/ if you don't understand German, pls let me know): 

Lohn für Ernteaufträge wird berechnet aus reward/ha, Feldgröße, Schwierigkeitsgrad. Am einfachsten erhöht man den ersten Wert. Die Konstante dafür heißt
`HarvestMission.REWARD_PER_HA_WIDE = 1500` (für Getreide) und 
`HarvestMission.REWARD_PER_HA_SMALL = 4800` für Kartoffeln, Zuckerrüben, Zuckerrohr.
Diese Zeilen kannst du z.B. bei der function BetterContracts:onMissionInitialize (in Datei betterContracts.lua) einfach dazufügen, und die Werte entsprechend erhöhen.

**Comment by BigDBudda** [comment]
Hi,
danke dir für die schnelle Antwort. Werde ich mal probieren.

**Comment by BigDBudda** [comment]
Hi Mmtrx, also ich habe mir mal alle Konstanten für die Aufträge raus gesucht und an der stelle hinzugefügt wie beschrieben. Allerdings generiert er nun nur noch 1 Auftrag wenn ich auf neue Verträge drücke.

**Comment by BigDBudda** [comment]
> Hi Mmtrx, also ich habe mir mal alle Konstanten für die Aufträge raus gesucht und an der stelle hinzugefügt wie beschrieben. Allerdings generiert er nun nur noch 1 Auftrag wenn ich auf neue Verträge drücke.

sry hat sich erledigt. habe einmal geschlafen nun sind Verträge wieder da
