### ISSUE TITLE
Sow missions are not working

### ISSUE THREAD

**Issue by westor7** [Mmtrx/FS22_BetterContracts#152]
Hello,

It seems that the sow mission is not working, i have not seen any errors in console, but i will upload the log.txt and the savegame so you can look up where is the problem, the progress bar is always in 0% even if the field has at least 50% complete of sow.

Savegame: [savegame1.zip](https://github.com/Mmtrx/FS22_BetterContracts/files/12302883/savegame1.zip)
Log.txt: [log.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/12302861/log.txt)
Map: `Neverland`

Images:

![FarmingSimulator2022Game_2023-08-09_15-58-07](https://github.com/Mmtrx/FS22_BetterContracts/assets/3636159/3faeed5d-0e95-434c-abeb-6695ada14eb1)

------------------

![FarmingSimulator2022Game_2023-08-09_15-58-22](https://github.com/Mmtrx/FS22_BetterContracts/assets/3636159/933906c0-6fdd-47cc-8903-8b65985b646c)

- Thanks!

**Comment by Mmtrx** [comment]
Hm - I think the base game doesn't offer grass sowing missions.

Does this also happen when BC is disabled?
Does it happen on other (grain / potato / sugar-beet) sow missions?

**Comment by westor7** [comment]
> Does this also happen when BC is disabled?

Idk haven't try that yet, i noticed that this is too rare triggering, the only thing that i know for sure is that this is happening in what ever map and is only effecting sowing.

> Does it happen on other (grain / potato / sugar-beet) sow missions?

No.

If it is too hard to catch that bug (also its not 100% sure that is BC bug, maybe something is conflicting there) then just close this issue and leave it. I've send the `savegame1` folder and all the debugging info i could.

**Comment by Mmtrx** [comment]
Couldn't find anything in your log / savegame data. But I verified that fruitType GRASS is never used for a sow mission. So this is probably a side effect from additional fruit types in the mod map: the generated mission is for - say - carrots, but the text in the contract tells you to sow grass.
