### ISSUE TITLE
Suggestion: Lock-in NPC field ownership

### ISSUE THREAD

**Issue by clubpetey** [Mmtrx/FS22_BetterContracts#153]
I like the ability to get discounts on land based on how many missions you do for an NPC.  However, the game randomizes the associations between fields and NPCs every time you load the game.  So if you are trying to do mission for a specific NPC to get a price reductions on a specific field. Re-loading the game ruins your progress.

The suggestion is to store the field-to-npc associations during first load, and ever time the game is re-loaded, reset the associations as they were on first load.

NOTE: this applies to fields not owned by a player, obviously.

**Comment by Mmtrx** [comment]
Hi Pete,

absolutely true. I realized that a while ago, and will implement your suggestion in next release.

**Comment by Mmtrx** [comment]
Done, see [v1.2.8.2](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.8.2)

**Comment by noque-lind** [comment]
It does not really seem like this is working, do i need to enable something somewhere?

**Comment by Gordon-Dry** [comment]
@noque-lind check the `farmland.xml` inside your savegame folder.
Does the lines contain an entry `npcIndex="X"` where X is obviously any number?

**Comment by noque-lind** [comment]
@Gordon-Dry  Yes it does. However it seems like it is recreated each time i load the savegame (or maybe when i save).


farmland.xml (last modified 15:54):

`<?xml version="1.0" encoding="utf-8" standalone="no"?>
<farmlands>
    <farmland id="1" farmId="0" npcIndex="10"/>
    <farmland id="2" farmId="0" npcIndex="1"/>
    <farmland id="3" farmId="0" npcIndex="7"/>
    <farmland id="4" farmId="0" npcIndex="3"/>
    <farmland id="5" farmId="0" npcIndex="10"/>
    <farmland id="6" farmId="0" npcIndex="3"/>
    <farmland id="7" farmId="0" npcIndex="5"/>
    <farmland id="8" farmId="0" npcIndex="15"/>
    <farmland id="9" farmId="0" npcIndex="11"/>
    <farmland id="10" farmId="0" npcIndex="3"/>
    <farmland id="11" farmId="0" npcIndex="3"/>
    <farmland id="12" farmId="0" npcIndex="15"/>
    <farmland id="13" farmId="0" npcIndex="5"/>
    <farmland id="14" farmId="0" npcIndex="1"/>
    <farmland id="15" farmId="0" npcIndex="3"/>
    <farmland id="16" farmId="0" npcIndex="8"/>
    <farmland id="17" farmId="0" npcIndex="1"/>
    <farmland id="18" farmId="1" npcIndex="11"/>
    <farmland id="19" farmId="1" npcIndex="6"/>
    <farmland id="20" farmId="1" npcIndex="8"/>
    <farmland id="21" farmId="0" npcIndex="2"/>
    <farmland id="22" farmId="0" npcIndex="10"/>
    <farmland id="23" farmId="0" npcIndex="11"/>
    <farmland id="24" farmId="0" npcIndex="14"/>
    <farmland id="25" farmId="0" npcIndex="9"/>
    <farmland id="26" farmId="0" npcIndex="2"/>
    <farmland id="27" farmId="0" npcIndex="11"/>
    <farmland id="28" farmId="0" npcIndex="3"/>
    <farmland id="29" farmId="0" npcIndex="1"/>
    <farmland id="30" farmId="0" npcIndex="14"/>
    <farmland id="31" farmId="0" npcIndex="15"/>
    <farmland id="32" farmId="0" npcIndex="3"/>
    <farmland id="33" farmId="0" npcIndex="1"/>
    <farmland id="34" farmId="0" npcIndex="5"/>
    <farmland id="35" farmId="0" npcIndex="5"/>
    <farmland id="36" farmId="0" npcIndex="4"/>
    <farmland id="37" farmId="0" npcIndex="11"/>
    <farmland id="38" farmId="0" npcIndex="3"/>
    <farmland id="39" farmId="0" npcIndex="1"/>
    <farmland id="40" farmId="0" npcIndex="14"/>
    <farmland id="41" farmId="0" npcIndex="6"/>
    <farmland id="42" farmId="0" npcIndex="10"/>
    <farmland id="43" farmId="0" npcIndex="4"/>
    <farmland id="44" farmId="0" npcIndex="10"/>
    <farmland id="45" farmId="0" npcIndex="13"/>
    <farmland id="46" farmId="0" npcIndex="2"/>
    <farmland id="47" farmId="0" npcIndex="1"/>
    <farmland id="48" farmId="0" npcIndex="1"/>
    <farmland id="49" farmId="1" npcIndex="12"/>
    <farmland id="50" farmId="0" npcIndex="4"/>
    <farmland id="51" farmId="0" npcIndex="6"/>
    <farmland id="52" farmId="0" npcIndex="3"/>
    <farmland id="53" farmId="0" npcIndex="12"/>
    <farmland id="54" farmId="0" npcIndex="1"/>
    <farmland id="55" farmId="0" npcIndex="8"/>
    <farmland id="56" farmId="0" npcIndex="2"/>
    <farmland id="63" farmId="0"/>
</farmlands>
`

farmland.xml (last modified 16:04):

<?xml version="1.0" encoding="utf-8" standalone="no"?>
<farmlands>
    <farmland id="1" farmId="0" npcIndex="8"/>
    <farmland id="2" farmId="0" npcIndex="13"/>
    <farmland id="3" farmId="0" npcIndex="9"/>
    <farmland id="4" farmId="0" npcIndex="9"/>
    <farmland id="5" farmId="0" npcIndex="5"/>
    <farmland id="6" farmId="0" npcIndex="7"/>
    <farmland id="7" farmId="0" npcIndex="10"/>
    <farmland id="8" farmId="0" npcIndex="6"/>
    <farmland id="9" farmId="0" npcIndex="8"/>
    <farmland id="10" farmId="0" npcIndex="6"/>
    <farmland id="11" farmId="0" npcIndex="10"/>
    <farmland id="12" farmId="0" npcIndex="4"/>
    <farmland id="13" farmId="0" npcIndex="8"/>
    <farmland id="14" farmId="0" npcIndex="3"/>
    <farmland id="15" farmId="0" npcIndex="1"/>
    <farmland id="16" farmId="0" npcIndex="8"/>
    <farmland id="17" farmId="0" npcIndex="3"/>
    <farmland id="18" farmId="1" npcIndex="3"/>
    <farmland id="19" farmId="1" npcIndex="13"/>
    <farmland id="20" farmId="1" npcIndex="8"/>
    <farmland id="21" farmId="0" npcIndex="6"/>
    <farmland id="22" farmId="0" npcIndex="7"/>
    <farmland id="23" farmId="0" npcIndex="6"/>
    <farmland id="24" farmId="0" npcIndex="13"/>
    <farmland id="25" farmId="0" npcIndex="1"/>
    <farmland id="26" farmId="0" npcIndex="8"/>
    <farmland id="27" farmId="0" npcIndex="5"/>
    <farmland id="28" farmId="0" npcIndex="3"/>
    <farmland id="29" farmId="0" npcIndex="2"/>
    <farmland id="30" farmId="0" npcIndex="14"/>
    <farmland id="31" farmId="0" npcIndex="9"/>
    <farmland id="32" farmId="0" npcIndex="9"/>
    <farmland id="33" farmId="0" npcIndex="2"/>
    <farmland id="34" farmId="0" npcIndex="14"/>
    <farmland id="35" farmId="0" npcIndex="5"/>
    <farmland id="36" farmId="0" npcIndex="6"/>
    <farmland id="37" farmId="0" npcIndex="10"/>
    <farmland id="38" farmId="0" npcIndex="3"/>
    <farmland id="39" farmId="0" npcIndex="14"/>
    <farmland id="40" farmId="0" npcIndex="2"/>
    <farmland id="41" farmId="0" npcIndex="4"/>
    <farmland id="42" farmId="0" npcIndex="8"/>
    <farmland id="43" farmId="0" npcIndex="11"/>
    <farmland id="44" farmId="0" npcIndex="8"/>
    <farmland id="45" farmId="0" npcIndex="12"/>
    <farmland id="46" farmId="0" npcIndex="6"/>
    <farmland id="47" farmId="0" npcIndex="9"/>
    <farmland id="48" farmId="0" npcIndex="13"/>
    <farmland id="49" farmId="1" npcIndex="2"/>
    <farmland id="50" farmId="0" npcIndex="1"/>
    <farmland id="51" farmId="0" npcIndex="12"/>
    <farmland id="52" farmId="0" npcIndex="2"/>
    <farmland id="53" farmId="0" npcIndex="11"/>
    <farmland id="54" farmId="0" npcIndex="11"/>
    <farmland id="55" farmId="0" npcIndex="15"/>
    <farmland id="56" farmId="0" npcIndex="10"/>
    <farmland id="63" farmId="0"/>
</farmlands>

**Comment by Gordon-Dry** [comment]
Just a reminder, please copy and paste including intends and linme breaks, you cannot tell me that your xml file really looks like this.

**Comment by noque-lind** [comment]
@Gordon-Dry  Apologies, i have edited the formatting of my previous answer.

**Comment by Gordon-Dry** [comment]
btw I just needed a yes or no, not a full quote of the file.
But what ever, the log.txt could be helpful.
