### ISSUE TITLE
Suggestion - Stop certain machines from being used & dual wheels

### ISSUE THREAD

**Issue by coatsy35** [Mmtrx/FS22_BetterContracts#157]
I play on UK maps a lot and huge american lorries and long trailers are often selected, as are tractors on dual wheels for trailer work and combines on duals, none of which always suit and fit UK/European style maps. Would it be possible to have settings to stop certain machines being used, or turn off the system selecting dual wheels would be a start...

**Comment by Mmtrx** [comment]
Lease equipment is (within certain boundaries) randomly selected when a new contract is generated by the game. Possible equipment combos per contract type are defined in the missionVehicles.xml files (there can be some of these, in mod maps and mod vehicles or script mods, BC brings one as well).

There is a possibility in BC to define your own missionVehicles.xml, so you have total control of what vehicles with what configurations (e.g. wheels) are defined for the game to choose from. A bit complicated, but if you want to try it, here is a [tutorial ](https://www.youtube.com/watch?v=nKIUxVh8l2g).
