### ISSUE TITLE
Suggestion: toggle "cheats" like instant-fermenting of bales on/off in game options

### ISSUE THREAD

**Issue by Gordon-Dry** [Mmtrx/FS22_BetterContracts#158]
So those cheaty keybinds don't exist anymore and so are not listed in input HUD anymore.

At least put them to the debug mode, so if the debug mode is off then those go away.

**Comment by Mmtrx** [comment]
Good point, will realize it within next release here.

**Comment by Mmtrx** [comment]
Done, see [v1.2.8.2](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.8.2)

**Comment by Gordon-Dry** [comment]
Thanks
