### ISSUE TITLE
Harvesting mission can't be completed

### ISSUE THREAD

**Issue by mas1701** [Mmtrx/FS22_BetterContracts#159]
I'm playing on the "Niedersachsen 2022" (NDS 22) map, v1.6 (NDS Modding) on FS22 dedicated server (owned, not rented)

I cannot successfully complete any sunflower harvesting contract. They always end up with about 2/3rds completed field work (60-70%) and 100% delivery.

I haven't experienced this bug with other missions/contracts so far.

However, I removed cotton and sugarcane from the map, as they usually don't grow in Europe. This should of course not change anything else, these fruit type are just disabled.

Any idea?

(From log:
Available mod: (Hash: 84ed19ef81ee34574e4790a35bdb0059) (Version: 1.2.7.9) FS22_BetterContracts

I recently removed Dynamic Field Prices because of incompatibilities, but it hasn't helped here.)

**Comment by mas1701** [comment]
Unfortunately, I have to add, that maize contracts are also affected. Same as with sunflowers. Delivery complete, but the fieldwork is not. Although it's empty.

**Comment by Mmtrx** [comment]
Hm, maybe your editing the fruit types changed the relation between fruit type index and its Description. So the total harvest gain per ha is off. 

If you install the Additional Field Info Mod, you could check the Max total gain (when standing on the contract Field), and compare that with the amount requested by the contract. 

For further analysis pls enable Debug on the BC settings page, start a corresponding harvest contract, and then upload your complete log.txt here.

**Comment by mas1701** [comment]
Thanks for your response and hint. I'll see what I can find out. I just installed Additional Field Info.

Regarding disabling fruits, I did NOTE REMOVE the entries from maps_fruitTypes.xml. Instead, I DID set them to showOnMap="false" and useForFieldJob="false":

```
<fruitType name="sugarCane" shownOnMap="false" useForFieldJob="false">
...
<fruitType name="cotton" shownOnMap="false" useForFieldJob="false">
...

```

Previously existing Sugarcame and Cotton are still visible on fields, but you can no longer do anything with them, except for ploughing the field, removing them. Therefore, I would not expect any fruit type index to change at all. Otherwise, the fields with those fuit types should show some other fruit instead.

**Comment by mas1701** [comment]
Hi again,

it took some time, but here we are. I harveted a maize field and sure enough, the contract did not complete. But then I found three mod errors in log.txt I hadn't noticed before. Even more surprising, these mods were working fine despite the errors. It seems that these mods became somewhat incompatible with the latest FS22 patches.

To eliminate the risk of false results, I disabled these three mods and started a second harvest contract. This time, a large field of sunflowers. The log seems to be free from mod errors, so I think this is a usable test result.

I'll add the screenshots here. But to summarize, the field work ended up at 69% and the delivery progress completed at 100%. I even had some additional sunflowers left.

Please, have a look into this.

Thanks.
![Image67](https://github.com/Mmtrx/FS22_BetterContracts/assets/30816569/4414c134-9ad8-4295-959d-9809837f75ff)
![Image68](https://github.com/Mmtrx/FS22_BetterContracts/assets/30816569/9ed351e1-b110-4e25-b918-a80f29058faf)
![Image69](https://github.com/Mmtrx/FS22_BetterContracts/assets/30816569/9123b3c6-cd26-402a-916c-7d36e640c597)
![Image70](https://github.com/Mmtrx/FS22_BetterContracts/assets/30816569/19c05b83-17a3-467a-812d-7572fb7bab32)
![Image71](https://github.com/Mmtrx/FS22_BetterContracts/assets/30816569/86e46023-839f-4967-8602-3c40975da9d8)
[log.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/12567801/log.txt)

**Comment by mas1701** [comment]
Hi,

wie kommst Du nur drauf, dass ich Deutsch kann? Niemals durch die Screenshots, oder!?

Ich bin der Sache heute noch mal nachgegangen und es ist leider so:
Die betroffenen Verträge scheitern auch ohne Better Contracts.

Ich kann mich an Forenbeiträge erinnern, in denen das reklamiert und später (angeblich) von GIANTS gepatcht wurde. Aber was ist, wenn der Fehler durch den Editor in die Map kommt und mit der Map zusammen gespeichert wird, wenn man darin die Felder erstellt? Dann würde sich der alte Fehler auch in eine neue Version übertragen. Fragt sich nur, ob sich das mit dem aktuellen Editor, mit dem ich mich nicht auskenne, auch beheben ließe.

Die aktuellere NDS (2.x) hatte ich mal probiert, damit gab es Probleme. Vielleicht geht es mit einer ganz frischen, müsste ich ausprobieren. Da aber das Savegame nicht kompatibel sein soll, wären viele Stunden auf der NDS 1.6 verloren. Bin nicht scharf drauf.

Danke jedenfalls für Deine Unterstützung.

Grüße!

**Comment by mas1701** [comment]
Hallo noch mal,

die Erntemissionenen für Mais und Sonnenblumen funktionieren auch in der neuesten NDS-Version 2.0.3 nicht. Ich habe mit viel Mühe alles auf diese Map-Version portiert, soweit das möglich war (Feldstatus z.B. nicht, wohl aber Feldbesitz), musste viel umbauen (weil jetzt vorgebaute Höfe da sind), aber hinsichtlich der Erntemissionen hat sich dadurch leider nichts verbessert. Für den Moment fallen damit Mais-/Sonnenblumen-Ernteaufträge weg.

Mir ist aber auch aufgefallen, dass ich oft unsinnige Missionen generiert bekomme. So bekomme ich immer wieder "Pflügen"-Aufträge für Felder, die intakt und erntereif sind. Nehme ich so einen Vertrag an, wird das Feld sofort zu einem "verfault/verdörrt" Feld. Ist das Better Contracts oder LS22 selbst? Auch andere Missionen ändern teilweise den Feldstatus, z.B. von abgeerntet zu einer frühen Wachstumsstufe (neu angesäht). Kannst Du dazu was sagen? Ich denke, so sollte das nicht sein, es sollten nur sinnvolle Verträge angeboten werden, die zum Feldstatus passen.

Grüße
Mark
