### ISSUE TITLE
Scripting question, no issue

### ISSUE THREAD

**Issue by SpiderTash** [Mmtrx/FS22_BetterContracts#16]
Love your Better Contracts, and I made a Contracts mod also, but just an improved Contracts Plus, nothing as good as yours.  My question is, I am making maps with larger fields, and so "Large" contract vehicles can be too small for some of the fields.  I looked through your code and see you reference small, medium, large fields, but is there anyway to actually create a extra large or double extra large field sizes through script?  I do have some programming knowledge, but not a lot.
Thank you

**Comment by Mmtrx** [comment]
Hi,
the small/med/large fields categories are implicit in the games mission vehicle system. Would be quite an effort to increase that with an additional category.

An easier way for you to define bigger vehicles/ equipment (in the "large" category) would be to  change the file `sample_userDefined.xml` in missionVehicles dir of BetterContracts. See instructions at the beginning of that file.

**Comment by SpiderTash** [comment]
That is what i figured, but i was hopeful there was a way.  Thank you

**Comment by SpiderTash** [comment]
OK, one more question just because something popped into my head.  So as your mod grabs the field size, would there be a way to take the number of acres, and then create new field sizes for contracts in script.  So say if it is over 100 acres, it overrides the base game contact field sizes and creates a new "xlarge" field size when looking for equipment to use?

**Comment by Mmtrx** [comment]
Ja, That's what I meant with some effort (implementing a 4th field size category). Problem is that the mission generation procedure is within the std game luas, and not in my mod.
So one would have to augment those functions (by Utils.appendedFunction etc), to make use of the new field category, and the corresponding array of mission vehicles.
Give me some time, and I will think about it ..

**Comment by SpiderTash** [comment]
Thank you very much, I just did a simple search through the game files trying to find how and where the field sizes we set and couldn't find them.  I will wait, thank you for your time on this.

**Comment by SpiderTash** [comment]
Thank you, that is going to be what I do as I am currently working on a 4x map and not having any fields less than 5, but probably larger.  Med being 10-20 more than likely.  Thank you very much for your help.  Will update you when I try this, but it will be a while.
