### ISSUE TITLE
Straw swath issues

### ISSUE THREAD

**Issue by s4dnz** [Mmtrx/FS22_BetterContracts#160]
I was havestering contract that allow straw swath, I has the mod that allow collect straw at mission. I saved game that had straw swath on it and number of field was still flashing (Havestered is finished).
Collect sraw at misson that I used: https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=223930&title=fs2022

Few day passby, I load it, the field reset it, and I lost straw swath and unable access to bales the straw on contract field. It's annoyed me, because I lost straw for animals need.
![issues2](https://github.com/Mmtrx/FS22_BetterContracts/assets/104271391/6e19383d-c335-4bdc-af87-9f4c9d5e3914)
![issuse](https://github.com/Mmtrx/FS22_BetterContracts/assets/104271391/63425d0a-a41c-4a6b-bde2-75ba5462c06f)
![issuse1](https://github.com/Mmtrx/FS22_BetterContracts/assets/104271391/51f39e99-7150-41f4-a012-7c112c8b388e)

**Comment by Mmtrx** [comment]
Hi,
I think that's a known Giants issue: If you leave any finished contract open (i.e. do not collect the pay) when leaving the game, on next start the contract will be "auto-finished", and you loose access to the contract Field. You also loose any leased mission vehicles. 

Therefore, always remove any straw  (or grass/hay on a bale mission) from a completed contract field, before leaving the game.
