### ISSUE TITLE
[BUG]: Lime mission stops growing a field

### ISSUE THREAD

**Issue by westor7** [Mmtrx/FS22_BetterContracts#161]
Hello,

I was able to reproduce the bug while i was trying hard to see how is possible a field to stop growing and after spending few hours i noticed that when i am taking a Lime mission and i finish it when i click on Collect to get the money from that contract then the field is stopping from growing, the crop is still there but is never growing up, i took a short video to show you how is that possible, i'm here if you need any other detail. Also i checked the log.txt and there is not any error there, this is an IMPORTANT bug and seems happening always when taking a Lime contract its totally destroying and stopping its grow.

**UPDATE**: Even if i try to Cancel the contract (without click on Collect) it's also bugging.

Video (25MB): https://ufile.io/v9i1w61c

- Thanks!

**Comment by Mmtrx** [comment]
Ok,
I have started looking into this. Do you happen to know the field's status BEFORE you started liming? Like harvested/stubble, or plowed/sown?

And yes, the "lime finished field 20" is a debug msg from BC. I'd also appreciate to see your complete log.

**Comment by westor7** [comment]
> Ok, I have started looking into this. Do you happen to know the field's status BEFORE you started liming? Like harvested/stubble, or plowed/sown?
> 

Is this screenshot what you want?

![FarmingSimulator2022Game_2023-09-13_00-53-55](https://github.com/Mmtrx/FS22_BetterContracts/assets/3636159/70625fc4-7871-40fd-a30b-2940a8430aee)

**Comment by westor7** [comment]
> Ok, think I have found a fix (didn't test very much with PF yet). Please give this a try (will have some debug msgs in the log): [FS22_LimeMission.zip](https://github.com/Mmtrx/FS22_BetterContracts/files/12665599/FS22_LimeMission.zip)

Ok i have tested my savegame using your new fixed version, the bug is still there and is not fixed, here is the [log.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/12671498/log.txt)

**Comment by Mmtrx** [comment]
Hi,
I forgot to mention: field 20 (and maybe other fields that you started a lime mission on) is corrupted in your savegame. You can repair that with EDC:
- stand on field 20, hit F12
- select field from the left menu
- change Fruit to _Potatoes_ (or whatever was on that field)
- verify that Growth is on _Sown_, and
- (optional) set Plowed To _Yes_
![fsScreen_2023_09_21_14_26_39](https://github.com/Mmtrx/FS22_BetterContracts/assets/86842734/5f8b7bf9-f1ef-44a8-ac5c-9623c579872e)
![fsScreen_2023_09_21_14_26_59](https://github.com/Mmtrx/FS22_BetterContracts/assets/86842734/cf98b24d-62a2-4a7c-bdff-e7452b050e2e)
![fsScreen_2023_09_21_14_31_51](https://github.com/Mmtrx/FS22_BetterContracts/assets/86842734/b5b9e62a-51f6-426d-a7c1-d09ac30a05a8)

**Comment by Gordon-Dry** [comment]
I just want to say that I had one lime mission yet since I started my new save and I went to that field to check it, it's growing as ususal.
It shows all info on the HUD, incl. PF.

**Comment by westor7** [comment]
Ok i made a new game, fully tested this bug and seems is being fixed, the growing state is now not being stopped.

Thanks for the fix.

**Comment by Mmtrx** [comment]
Thanks for testing. The official new update is [here](https://github.com/Mmtrx/FS22_LimeMission/releases/tag/v1.1.0.0) (without debug log messages).

Other messages in your log come from mod FS22_3rdPerson:
```
  dataS/scripts/sounds/SoundManager.lua (1115) : playSample
  dataS/scripts/player/PlayerModel.lua (875) : playSample
  dataS/scripts/player/Player.lua (2419) : setSoundParameters
  =D:/Documents/My Games/FarmingSimulator2022/mods/FS22_3rdPerson/thirdPerson.lua (398) : updateSound
```
