### ISSUE TITLE
Kein Abschließen der Missionen mehr möglich

### ISSUE THREAD

**Issue by JSGER** [Mmtrx/FS22_BetterContracts#166]
Ich benutze den Hotfix 2. Bin also aktuell

2023-10-11 09:44 Error: Running LUA method 'mouseEvent'.
C:/Users/Joche/Documents/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/scripts/options.lua:576: attempt to index field 'conf' (a nil value)

Zusatz: Dünger Missionen funktionieren. Ernte Missionen nicht.

**Comment by Gordon-Dry** [comment]
Dann hast du vermutlich noch nicht die notwendigen Einträge in der
`Documents\My Games\FarmingSimulator2022\savegameX\FS22_BetterContracts.xml`
in der Zeile 2 `<BetterContracts ...` müssen auch die beiden Einträge
`ferment="false" forcePlow="true" ` stehen. Ob "true" oder "false" ist egal, aber die Einträge müssen da sein.

**Comment by JSGER** [comment]
Hab die beiden Einträge nachgetragen, aber der Fehler bleibt.

**Comment by Gordon-Dry** [comment]
Hmm. Also entweder hast du dann einen bisher unentdeckten Bug entdeckt - oder es ist wieder ein neuer hinzugekommen, weil ein alter behoben wurde.
Ich kann es momentan nicht testen, weil ich in der aktuellen Phase keine solchen Missionen angeboten bekomme.

**Comment by Mmtrx** [comment]
Mist, hier hab ich mich echt nicht mit Ruhm bekleckert. Die Variable heißt config, nicht conf. Werd ich heut abend noch reparieren..

**Comment by JSGER** [comment]
Kein Problem. Ich bin dir trotzdem Dankbar. Ist schließlich deine private Zeit die du der Allgemeinheit schenkts.

**Comment by Mmtrx** [comment]
Ok, war nur ne Kleinigkeit, [3. hotfix](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.8.5a)

**Comment by Mmtrx** [comment]
Ok, war nur ne Kleinigkeit, [3. hotfix](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.8.5a)
