### ISSUE TITLE
Feature request - Maximum contracts per farm in a specific period in MP

### ISSUE THREAD

**Issue by Daesed-Dazed** [Mmtrx/FS22_BetterContracts#168]
Brilliant mod, thank you so much for it. 

I currently run a MP server with several farms but to keep it balanced between farms that can play a lot and those who can't I have had to ban contracts. It would be super handy if there was a way to limit the maximum amount of contracts that a farm could complete in a specific time period such as a day/month/year. 

Another handy feature would be to completely disallow leased equipment on contracts forcing the farms to either invest in equipment or only do contracts that they have the gear for. 

These are just some suggestions and if they're not of interest to you I completely understand, thanks for the great mod, and have a good one!

**Comment by Mmtrx** [comment]
Will think about it.
In the meantime, some suggestions:
- as admin you can hit M on the BC details page, showing active contracts for all farms. This was requested by another MP admin, where players were "hoarding" contracts.
- you could turn on hard mode, and set the amount of jobs required before leasing to max.  (Currently 7, but you can edit line 180 in scripts/settings.lua in the mods zip folder.

**Comment by Mmtrx** [comment]
Please try last [update](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.8.7).

**Comment by Daesed-Dazed** [comment]
Works brilliant thank you! Really appreciate it.
