### ISSUE TITLE
Dedi Server, Standbild  v1.2.8.5a

### ISSUE THREAD

**Issue by DEKoelle** [Mmtrx/FS22_BetterContracts#174]
habe vorhin die v1.2.8.5a auf den Dedi Server gepackt,und habe die NF Marsch OG V 3.7.1 gestartet, nach em Start kam und drauf gedrückt habe , habe ich nur ein Standbild und wenn ich ESC drücke , komme ich zwar ins Menü, kann aber nichts weiter machen, in SP funktioniert alles. Habe mal den Häcksel-Aufträge mod raus genommen, damit geht die neue Version von Better Contracks

**Comment by Mmtrx** [comment]
Die erste Version (modHub) von FS2_ChaffMissions war nicht immer MP-fähig. Versuch mal [diese](https://github.com/Mmtrx/FS22_ChaffMission/releases/tag/v1.0.2.0).

**Comment by Mmtrx** [comment]
Hat sich wohl erledigt..
