### ISSUE TITLE
ChaffMissions/BetterContracts modhub update request

### ISSUE THREAD

**Issue by Senapsbread** [Mmtrx/FS22_BetterContracts#175]
I've been using your mods with a couple of friends, but ChaffMissions isn't working with the version of BetterContractgs that is on Modhub and we can't use any later updates that isn't on modhub because one of us is playing thru GeforceNow. 

Is there a specific reason the modhub version of Better Contracts isn't updated or is that something that could possibly happen?

**Comment by Mmtrx** [comment]
Yes, will send next release to modhub when all open issues here are fixed. Shouldn't take too long 🤓

**Comment by zakoattak0** [comment]
Any update on when BetterContracts / ChaffMissions will be updated / Added to the mod-hub?

**Comment by Mmtrx** [comment]
BC v1.2.8.7 has just started testing with Giants modhub team. Should be avail from modhub within next 10 days.

**Comment by zakoattak0** [comment]
Awesome thanks!

**Comment by Mmtrx** [comment]
1.2.8.7 is on modhub now.
