### ISSUE TITLE
FS22_ChaffMission/chaffMission.lua:102: attempt to index a nil value

### ISSUE THREAD

**Issue by PanPluto** [Mmtrx/FS22_BetterContracts#179]
Hello, I'm playing with the seasons option, after uploading the latest version of better contract and chaff mission, I get this error and the contracts menu freezes

FS22_ChaffMission/chaffMission.lua:102: attempt to index a nil value
![image](https://github.com/Mmtrx/FS22_BetterContracts/assets/148870270/1e3185dc-5a4d-4926-aa1c-fa79b324155a)

**Comment by Mmtrx** [comment]
Hi,
can you pls attach you complete log,.txt here?
