### ISSUE TITLE
5120x1440

### ISSUE THREAD

**Issue by AK-Baldow** [Mmtrx/FS22_BetterContracts#18]
Hi, I've been using the mod for a while. But since the beginning I have a distorted image at a resolution of 5120x1440.

**Comment by AK-Baldow** [comment]
![5120x1440](https://user-images.githubusercontent.com/110068570/181381983-436f1906-81fe-4bc6-bc24-1e15cec42939.jpg)

**Comment by Mmtrx** [comment]
Oha,
mit so einer Auflösung hab ich das leider nicht getestet (hab auch kein Equipment dafür :-)
Schickst du mir mal zum Vergleich einen screenshot vom Verträge-Menu ohne den Mod? Dann seh ich mir mal die Mechanik mit den erweiterten Auflösungen an..

**Comment by AK-Baldow** [comment]
![fsScreen_2022_07_29_22_48_01](https://user-images.githubusercontent.com/110068570/181841067-31ba2055-5275-476d-af59-92330d35e6fb.jpg)

würde es ja selber machen aber so gut bin ich in LUA auch nicht. kann nur Kleinigkeiten ändern.

**Comment by DerKleineDucky** [comment]
Hallo, ich habe das selbe Problem mit einer Auflösung von 3840x1080, also dürfte es am Seitenverhältnis von 21:9 liegen.
![20220731170058_1](https://user-images.githubusercontent.com/110531876/182575764-d0dffb81-82c8-45a9-a0be-6519ffeebf67.jpg)
Dies ist nur ein Ausschnitt aus der Mitte für die besser Lesbarkeit.

Eine Idee, woran es liegen könnte?

**Comment by MoritzT** [comment]
Hier auch das Problem bei 5120x1440
![image](https://user-images.githubusercontent.com/1623958/184544662-051700ae-c09c-4c41-89a5-ee2102d61b81.png)

**Comment by throsten** [comment]
Bei mir ist es mit 3840x1600 auch "verbogen".
![fsScreen_2022_08_15_07_55_50b](https://user-images.githubusercontent.com/96873819/184619140-96b66ec8-2425-46cc-937c-1afb9b752dd8.jpg)

**Comment by Mmtrx** [comment]
Fixed in latest [Relese](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.4.0).
I could only test with lower resolutions (1280x1024, 1400x1050), so please verify with your monster screens ;)

**Comment by AK-Baldow** [comment]
![Unbenannt](https://user-images.githubusercontent.com/110068570/185186907-886872e5-0a9c-48f4-bf14-58a2fb192f27.jpg)

Jetzt passt es perfekt. Dankeschön

**Comment by MoritzT** [comment]
Passt!
![image](https://user-images.githubusercontent.com/1623958/185356294-dba81a5c-da37-4583-92dc-707f63b68330.png)
