### ISSUE TITLE
Trotz 70% Ernteerwartung kein Abschluß der Aufträge!

### ISSUE THREAD

**Issue by LSMT-elMatador** [Mmtrx/FS22_BetterContracts#181]
Auf der Lands of Italy kann ich keine Aufträge mehr abschließen. Obwohl Die Liefererwartung der Aufträge auf 70% steht wird kein Auftrag mehr fertig. Alle beenden bei 97% und 81% Liefererwartung!

**Comment by LSMT-elMatador** [comment]
BC Version 2.8.5a

**Comment by Mmtrx** [comment]
Hm, Ernteaufträge? Welche Frucht?
Kannst du mal die log.txt hier anhängen, und vielleicht auch einen screen shot?

**Comment by LSMT-elMatador** [comment]
War jede Frucht, Alles was mit Drescher zu tu hat.
Log kann ich im Moment nicht reproduzieren!

**Comment by Mmtrx** [comment]
Ja, wär mal interessant, ob du ohne BC Ernteaufträge auf der Mao erfolgreich abschließen kannst.

**Comment by LSMT-elMatador** [comment]
Ich kann bei nem neuen Spielstand die Aufträge abschließen. V1.2.8.5a

Sollte der Fehler noch einmal auftauchen, werde ich hier die Log und alles senden

**Comment by Mmtrx** [comment]
Ok, wenns wieder auftaucht, kannst du diesen Issue ja wieder öffnen.
