### ISSUE TITLE
Höhe der Belohnung

### ISSUE THREAD

**Issue by foreverls19** [Mmtrx/FS22_BetterContracts#182]
Hallo,
wäre es möglich die Belohnung für jede Arbeit(dreschen, grubbern..........) einzeln anzupassen

mfg

**Comment by Mmtrx** [comment]
Da hätte ich einen kleinen Minimod. Die Werte kannst du dann selbst editieren..
[missionRewards.zip](https://github.com/Mmtrx/FS22_BetterContracts/files/13235695/missionRewards.zip)
