### ISSUE TITLE
Bettercontracts not working on dedicate server

### ISSUE THREAD

**Issue by LeklaRyba** [Mmtrx/FS22_BetterContracts#183]
Hello i have problem with this mod in game work perfect but on dedicate server dont show detail of contract. Same save mods everithing. Some one have the same problem?

**Comment by Mmtrx** [comment]
Hi, please try this updated version of [ChaffMissions](https://github.com/Mmtrx/FS22_ChaffMission/releases/tag/v1.0.2.0). The modHub (chaff missions) version is not really MP ready yet.

**Comment by LeklaRyba** [comment]
Hello thx i will try it ;)

čt 2. 11. 2023 v 8:37 odesílatel Mmtrx ***@***.***> napsal:

**Comment by LeklaRyba** [comment]
Hello i thing i am a idiot and andi dosnt know hot to dowload this mod ...
dedicate server show me this mod is corrupted and not workong


čt 2. 11. 2023 v 13:28 odesílatel Milan Karasek ***@***.***>
napsal:

**Comment by LeklaRyba** [comment]
Problem solved thx a lot!

**Comment by LeklaRyba** [comment]
New problem product cant by delivery

**Comment by Mmtrx** [comment]
Could you explain the problem a liitle further?

**Comment by LeklaRyba** [comment]
While completing the task on the cut when I harvested it and was
supposed to take it to the destination. so she didn't go to explain.
so the job could not be completed. I'm sorry for my bad english



so 4. 11. 2023 v 9:15 odesílatel Mmtrx ***@***.***> napsal:

**Comment by LeklaRyba** [comment]
Last version work perfekt thx
