### ISSUE TITLE
Fields not completed with stubble destruction

### ISSUE THREAD

**Issue by Pollie777** [Mmtrx/FS22_BetterContracts#184]
When using Global crop destruction the field progress bar is not completed. As if the stubble destruction area is deducted from the field completed area.

**Comment by Gordon-Dry** [comment]
I only use one mod with the word "destruction" in its file name: FS22_cropDestructionPlus
This one seems to be okay. But I still need to investigate it.

**Comment by Pollie777** [comment]
The same problem occurs when using the for example the mod  FS22_JD_612FC which is a corn header from JHHG in modhub. These headers can be configurated with a stalk stomper that cuts the stubble.

**Comment by Mmtrx** [comment]
Can you upload the log please? And maybe 1 or 2 screen shots. So that I can try to reproduce your situation.

**Comment by Mmtrx** [comment]
..expired.
