### ISSUE TITLE
Neue Früchte, falsche Geräte

### ISSUE THREAD

**Issue by cl1nq** [Mmtrx/FS22_BetterContracts#186]
Bei den neuen Früchten (Pastinaken, Karotten, Rote Beete) tauchen die falschen Geräte zum Ausleihen auf, bei mir ein Mähdrescher mit Schneidwerk und Abfahrerzug.

**Comment by Mmtrx** [comment]
Jo - muss ich noch auf den neuen Premium DLC anpassen, Is in Arbeit ..

**Comment by Mmtrx** [comment]
Hm, bei meinen ersten Tests passiert das nicht. Hast du die DynamicMIssionVehicles Mod aktiv? Die könnte auch noch inkompatibel sein.
Ansonsten bitte mal die log.txt hier posten.

**Comment by cl1nq** [comment]
Ja, die war aktiv. Habe diese deaktiviert, leider ohne Veränderung.

[log.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/13419598/log.txt)

**Comment by Mmtrx** [comment]
Denn is ja gut😀
