### ISSUE TITLE
Even Lazier NPC's

### ISSUE THREAD

**Issue by AutumnGamer** [Mmtrx/FS22_BetterContracts#187]
I have set Lazy NPC's to true, and all of its sub options too, but I still get far many less contracts then there are fields on my map. Take Baling for example, on one occasion all of about 8-10 fields with grass were noted as ready for harvest on my map, but only 2 of them offered a baling contract. Is it possible to add an option the NPC's so lazy that they will simply outsource every single thing that needs to be done on their fields? Thank you very much for this amazing mod!

Edit: I'm using Better Contracts 1.2.8.5a. (Also, the game keeps asking me to 'upgrade' to 1.2.7.9)

**Comment by Mmtrx** [comment]
Hi,
NPCs (and BC) don't affect mowing/ baling missions. That is, an NPC will never mow one of their own fields. MowBale missions are only generated by the game, if the field is set to "allow missions" by the mapper. So it could be that only 2 of your maps grass fields have this  "allow missions" setting. Also, mowBale missions are only generated if the grass has the max growth state (ingame map shows yellow "harvest ready" also for one growh state below ("forage harvest")). And they are not generated in winter.

The ingame mod updater knows only the modHub versions, it doesn't know gitHub. So you can ignore the upgrade message. 😄

**Comment by AutumnGamer** [comment]
Ah, then I guess it will be that the grass is 'ready to harvest' without having the maximum growth stage, as I've had missions for those fields in other saves. I am playing on Elmcreek, I think that all fields should be able to have missions there.

As for lazier npc's, I've been playing for a couple of hours on this fresh save and the amount of available contracts went down from 52 to 16 (with extra types of mission mods) and 51 to 9 (without extra types of mission mods). I did 2 of those, but that leaves 34 to 40 contracts that just disappeared. Is it possible to make NPC's so lazy that the contracts don't disappear, or at least not so fast?

Last question, does LazyNPC's also influence the availability of other mission mods from the modhub, like Lime Contracts, Forage Contracts, Roller Missions, and the likes of those? Thank you very much for your clarifications!

**Comment by Mmtrx** [comment]
Hi,
the list of contracts is validated every ingame day by the base game, contracts can disappear when
- the new month doesn't allow sowing / harvesting any longer (see growth calendar)
- an NPC does the work

So to verify your situation, we'd need to know the contracts list and month before and after the "vanishing" of 34 to 40 contracts.
And, you can always try to generate additional contracts by hitting X on the contracts page.

Answer to 2nd question is yes, lime contracts go with lazyNPC setting for fertilize, forage go with harvest setting.

**Comment by AutumnGamer** [comment]
This happened after approximately 6 hours, still on the first day as I had time on the slowest scale. And the count I gave was after repeatedly pressing X on the contracts page untill nothing new emerged even after 10 or more clicks. This makes me think that the NPC still did the job after all. An hour further in to the game even more contracts had disappeared. But maybe what I had in mind is simply not possible due to how the game is set up and I just have to let it go.

**Comment by Gordon-Dry** [comment]
I already had the suspicion that on starting a new game the default settings make the NPCs do a lot of stuff - especially when using a start in spring mod.
Is there a timeout after game start to have the time to change the settings for a couple of minutes?
If not, the only solution would be to have the default settings changed before starting a new game.
Could this be?

**Comment by AutumnGamer** [comment]
As for when I lost the contracts, it could very possibly be sooner then a couple of hours, because I am still kind of a farming sim noob and I was working a silage baling contract on field 71, so I never checked in between. I just kind of liked the idea of having a very slow timescale and having to do all the work myself! But it seems that setting the time settings so that you actually have time to do the lazy NPC's work for them is the biggest factor in them not being lazy, thats a bit of a disappointment.

Thank you very much for looking into this and taking the time to explain the mechanics!

**Comment by Mmtrx** [comment]
In my last [update](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.8.7) NPC farmers will not start any field work before noon of 1st day of month, if lazyNPC is active. I wonder if this gives you some more contracts when playing on slow (1,2) time scales.

**Comment by AutumnGamer** [comment]
That sounds like it might work, I will test it as soon as my PC is back up and running! Just one question, in the patchnotes it says:

> "npc should not work before noon of first day in month (https://github.com/Mmtrx/FS22_BetterContracts/issues/187): should increase available (sow) missions for games with slow time scales"

Does the (sow) part mean this only goes for sowing missions? Or will all missions that are set to lazy not be started before noon? Thank you very much!

**Comment by Mmtrx** [comment]
All NPC field work (if a mission avail or not) will not start before noon. So yes, applies to all missions, regardless of the specific lazy settings. 😉

**Comment by MeRida2104** [comment]
> when playing on slow (1,2) time scales.

Thanks for the last update; we will test it promptly on our dedicated server. Regarding the mentioned quote: Did you also consider the time scale of 0.5? For example, we run our server continuously during the day with a time scale of 0.5 and at night with 2. This ensures that we always have daytime during peak playing hours.

**Comment by Mmtrx** [comment]
No NPC work before noon means all missions generated between 0:00 and 12:00 are safe for you to take. Both, 12 h with time scale 1, or your setting (provided you switch scales at 6:00 😉) mean: 12 hours safe from NPC doing any field work.

**Comment by Gordon-Dry** [comment]
Who gets up at midnight?

**Comment by MeRida2104** [comment]
I don't ;) we use the FastNight mod and modified it to allow 0.5 timescales. This means we run the time at 0.5x speed from 9 AM to 5 PM (in-game, real-time it would be 9 AM to 1 AM), and at 2x speed from 5 PM to 9 AM (in-game, real-time it would be 1 AM to 9 AM). So, you can play from early morning to late at night with Ingame daylight ;)

**Comment by MeRida2104** [comment]
That looks very, very good! Huge thanks for this change to BC!!

![image](https://github.com/Mmtrx/FS22_BetterContracts/assets/96819380/1b4364a1-c083-4403-9976-7b3ac3af7376)

**Comment by AutumnGamer** [comment]
Works even better then I expected. I have completed 17 contracts on my new save (freezing time at 8 in the morning) and instead of losing contracts new ones are actually generated on the harvested fields! This is amazing!
