### ISSUE TITLE
Missionen schließen nicht ab.

### ISSUE THREAD

**Issue by Dwarfbare** [Mmtrx/FS22_BetterContracts#189]
Servus Zusammen,
Ich habe auf der March die Missionen gemacht. Am Anfang Ohne leihGeräte. Läuft wunderbar.
Noch um mehr Aktion zu haben, habe ich nun mit Leihgeräte gemacht und ich kann die Missionen nicht abschließen obwohl sie abgeschlossen sind. Die Geräte verschwinden, aber der Vertag bleibt im Menü. Ich habe kein Geld bekommen. Und auch nicht beim Neustart des Spieles tritt folgender Fehler auf
Chronik
Gleich direkt nach dem Spielstart
![image](https://github.com/Mmtrx/FS22_BetterContracts/assets/64143352/84bbf065-3f56-4bac-a693-15429b4c2ea7)
1-2 Minuten Später
![image](https://github.com/Mmtrx/FS22_BetterContracts/assets/64143352/2a2232fc-897c-4cf0-9ead-69dd78c77842)
Ansicht im Manager nach den 1-2 Minuten
![image](https://github.com/Mmtrx/FS22_BetterContracts/assets/64143352/b116edd4-651c-472c-b7f1-1aba5b8eb5ce)

Uhrzeit ca 2:45
[log.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/13420914/log.txt)

in einem anderen Logfile, wo ich im Manager die Liste gelöscht habe und neue Aufträge erzeugt habe kam folgenden fehler. Hat dies ggf was damit zu tun?

wenn ich auf das Feld drücke kommt folgender Fehler in der LOG
C:/Users/User/Documents/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/scripts/options.lua:576: attempt to index field 'conf' (a nil value)
2023-11-21 02:56 Error: Running LUA method 'update'.

[log.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/13420960/log.txt)

Wenn noch fragen sind gerne melden :)

VG Dwarf

**Comment by Mmtrx** [comment]
Am besten probierst du mal die neuste Version von BC: 1.2.8.5a. Den Fehler mit „conf“ hatte ich leider selbst eingebaut 😬.

**Comment by Dwarfbare** [comment]
OK, hat funktioniert. Super Danke dir

**Comment by Mmtrx** [comment]
Na, dann ist ja gut.
