### ISSUE TITLE
Is it possible instead of repeating "Harvesting" the name of the crop on the field?

### ISSUE THREAD

**Issue by vitalii2011** [Mmtrx/FS22_BetterContracts#19]
![fsScreen_2022_07_27_21_44_36](https://user-images.githubusercontent.com/41552153/181350017-f8aff444-72d7-4f17-af8d-93b3cb521cef.png)

**Comment by Mmtrx** [comment]
Fixed in latest [Relese](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.4.0)

**Comment by vitalii2011** [comment]
> Fixed in latest [Relese](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.4.0)

https://github.com/vitalii2011/FS22_BetterContracts/blob/patch-2/l10n/l10n_ru.xml

**Comment by throsten** [comment]
Great feature that helps! Is it possible to add the fruit type at sow missions too? Thx.

**Comment by vitalii2011** [comment]
> Fixed in latest [Relese](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.4.0)

1.2.4.0 - no, as it was:
![0011](https://user-images.githubusercontent.com/41552153/188093096-0568f9db-32ea-495d-985c-cada2d9cb1e3.jpg)
![fsScreen_2022_09_02_11_02_54](https://user-images.githubusercontent.com/41552153/188093103-d3d94e27-2cb5-42df-8523-3c07485c5bae.png)

**Comment by Mmtrx** [comment]
Hi @vitalii2011,

works only if [D]etails button is on. 😉

**Comment by vitalii2011** [comment]
> Hi @vitalii2011,
> 
> works only if [D]etails button is on. 😉

Hi.
Understood, but in the letter, probably, this question has reached.
There are probably reasons why you did not make it enabled by default, but I would really like such a setting - I turn it on every restart anyway.

**Comment by vitalii2011** [comment]
> …

Translation for lines 16-17:
https://github.com/vitalii2011/FS22_BetterContracts/blob/patch-4/l10n/l10n_ru.xml

**Comment by Mmtrx** [comment]
Thanks, 
just committed that to main.
