### ISSUE TITLE
On Elm Creek every field wanted to be seeded with cotton, but no contracts to harvest the cotton ever exist?

### ISSUE THREAD

**Issue by TheJoe1990** [Mmtrx/FS22_BetterContracts#191]
Two years in a row I have planted cotton on nearly every field for the NPCs, but then its never harvested.  Is this because I play with a mod for starting in Spring?

**Comment by Mmtrx** [comment]
Ja, StartInSpring could really disturb the normal growth (and NPC harvest) of a  map. 

How do you "plant cotton on nearly every field for the NPCs"? Using EDC? Then you could also try and set the growth state on the cotton fields to "harvest-ready".

**Comment by Mmtrx** [comment]
..probably no longer valid.
