### ISSUE TITLE
GUI von anderen MODS verschwindet wenn Transportauftrag angenommen wird

### ISSUE THREAD

**Issue by Dwarfbare** [Mmtrx/FS22_BetterContracts#193]
Servus Miteinand,

Folgender Sachverhalt.
Es laufen natürlich mehrere MODs parallel und das auch sehr gut. 
(Better Contracts, Vehicle Inspector, Production Information HUD)

AUSSER ich nehme einen Transportauftrag an. (bei allen anderen Aufträgen tritt dieses Verhalten nicht auf)

Szene 1:
![image](https://github.com/Mmtrx/FS22_BetterContracts/assets/64143352/267592e9-53a8-4812-ba18-5dd1ff114ec6)

dann nehme ich einen Transportauftrag an:

![image](https://github.com/Mmtrx/FS22_BetterContracts/assets/64143352/409aa058-606f-4937-b8f1-48f03b8f216e)

Szene 2:
Gui sieht dann so aus
![image](https://github.com/Mmtrx/FS22_BetterContracts/assets/64143352/fe24b0ed-0529-49c3-b684-a4e120d679b9)

Szene 3:
Wenn ich Auftrag abgeschlossen habe, ist die GUI wieder wie in Szene 1 zu sehen:

Vielen Dank für eure Hilfe.

BR Dwarfbare

**Comment by Dwarfbare** [comment]
Hier noch das Log file, das ist LUA 65 Fehler drinne
[log.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/13505346/log.txt)

**Comment by Mmtrx** [comment]
Die lua Fehler kommen von VehicleInspector und ContractHud:

VehicleInspector/scripte/viSetGet.lua:1388: attempt to index field 'specs' (a nil value)

FS22_ContractHUD/ContractHUD.lua:65: attempt to index field 'field' (a nil value)

Schätze mal, dass diese beiden sich mit dem Transportaufträge Mod nicht so gut vertragen.

**Comment by Mmtrx** [comment]
Wie, was geb ich aus? BC macht keine Änderungen am F1 Menu. Nimm doch mal BC raus, ob das Problem dann weg ist. Wenn ja, können wir hier gern weitermachen. 😉
