### ISSUE TITLE
Instant Fermentierung abstellen?

### ISSUE THREAD

**Issue by betjal** [Mmtrx/FS22_BetterContracts#194]
Hallo,

gibt es eine Möglichkeit bei den Better Contracts die sofortige Fermentierung gewickelter Grasballen ausserhalb von Missionen abzustellen? Der Mod als solches ist sehr gut gelungen, nur diese Funktion sorgte bei unseren Server-Admins für Unstimmigkeiten.

Vielen Dank schonmal.

VG

**Comment by Gordon-Dry** [comment]
Ist seit v1.2.8.4 drin.

**Comment by betjal** [comment]
Ah, danke. Mein Kenntnisstand war noch von der farming-simulator-Homepage. Dort wurde Version 1.2.7.9 zuletzt hochgeladen.
