### ISSUE TITLE
Frage zu Mod Bale ID Manager

### ISSUE THREAD

**Issue by MeRida2104** [Mmtrx/FS22_BetterContracts#196]
Hi @Mmtrx ,

Entschuldige zuerst einmal, dass ich Better contracts für ein Issue bzgl Bale ID Manager missbrauche, aber ich habe keinen anderen Weg gefunden dich hierzu zu kontaktieren. 

Wir spielen auf der 4fach Map Achtern Diek. Diese nutzt das Script moreNumFarms. Es ist also möglich mehr als 8 FarmIDs zu erstellen. Wir haben versucht mit dem Eigentum übertragen Mod die größere der beiden Göweil Pressen auf einen Hof mit der FarmID 9 (also höher 8) zu transferieren. Das funktioniert allerdings nicht, weil sich das Spiel mit LUA Fehlern aufhängt, sobald man in die Nähe der Presse geht. Könntest du dir ggf einmal ansehen? Kann dir später gerne auch Logfiles bereitstellen. 

Viele Grüße
MeRida

**Comment by Mmtrx** [comment]
Moin Merida,

du hast recht (und danke für den Hinweis): hab BaleIdManager noch gar nicht als Repo hier angelegt, kommt demnächst..

Das mit moreNumFarms lässt sich leicht korrigieren, wenn du FS22_moreNumFarms vom modHub meinst.
Ich muss in meinem mod nur statt der hard-coded "8" die Variable `FarmManager.MAX_NUM_FARMS` benutzen. Update ist in Arbeit..

**Comment by MeRida2104** [comment]
Hi @Mmtrx ,

Kannst du schon eine Zeitaussage treffen wann das Update von dir kommt? 

Beste Grüße und danke für deine Arbeit :)

**Comment by MeRida2104** [comment]
Kleine Rückmeldung: Funktioniert :) danke für die Umsetzung
