### ISSUE TITLE
Frage zu den "Faulen Farmern"

### ISSUE THREAD

**Issue by Cassy-Blair** [Mmtrx/FS22_BetterContracts#197]
Gibt es die Möglichkeit den "Faulen Farmern" eine Zeitbegrenzung hinzuzufügen? 
z.b. wenn ein Auftrag innerhalb von wahlweise 6, 12, 18 oder 24h nicht angenommen wird, daß dieser dann von den NPC's übernommen wird? Aktuell ist es ja so, daß bei aktivierten faulen Farmern die Aufträge dauerhaft stehen bleiben und nicht automatisch erledigt werden. Wäre meiner Meinung nach eine tolle Erweiterung, damit man z.b. nur die Aufträge mit hoher Gewinnspanne annehmen kann und die kaum rentablen Aufträge von den NPC's erledigen lassen kann

Aktuell nutze ich noch die aktuelle Modhub Version

**Comment by Mmtrx** [comment]
Moin,
die Aufträge haben ja ein gewisses "Verfallsdatum" und bleiben nicht ewig stehen. Sä-, Mäh-, Ernteaufträge verschwinden spätestens im Winter. Alle anderen auch mit der Zeit.

Der ursprüngliche Sinn dieser Mod war ja, mehr Aufträge zu haben und nicht weniger. Daher werd ich diese Idee erst mal nicht weiter verfolgen. Trotzdem danke für die Anregung!

**Comment by Cassy-Blair** [comment]
@Mmtrx 
Naja da ich ohne Seasons spiele verschwinden die Aufträge eben nicht so einfach (außer dann im Winter), aber den Rest des Jahres bleiben die Aufträge erhalten. Daher hatte ich die Idee, daß man eben die Verfallszeit variabel selbst einstellen kann. Keine Verfallszeit, 6h Verfallszeit, 12h Verfallszeit, 24h Verfallszeit oder 48h Verfallszeit für noch nicht angenommene Verträge.
