### ISSUE TITLE
[Feature] Reward ratio per type

### ISSUE THREAD

**Issue by acesyde** [Mmtrx/FS22_BetterContracts#198]
Hi @Mmtrx 

Is it planned to implement a reward reation per type

Today the mow_bale mission reward is too high in the other hand the fertilizer mission reward is too low, I would to set the reward ratio foreach type.

Thks

**Comment by Mmtrx** [comment]
Your 1st pr was just [released](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.8.7).
I will now test and merge your 2nd one. Thanks for collaborating!
