### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by winn69** [Mmtrx/FS22_BetterContracts#2]
Hello i had active bailing contract and I go look  how bales need sell for contcarct finish but when i Exit from menu and after 30 I want check field status this happend. I cant nothing I can only force close game https://imgur.com/a/4AuNxch
Here is log
[log.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/7962452/log.txt)
I am not sure is this mod problem or refresh contract. I put both mod and then problem start .

**Comment by HurrycaneBE** [comment]
clean up your mod dir , then try again i think

**Comment by winn69** [comment]
![20220129134217_1](https://user-images.githubusercontent.com/98623764/151661861-091976b0-a902-47c5-9353-edd5d8eae376.jpg)
I am not sure why I cant upload log again but i have new problem after some time  i cant see all contract and I cant disable menu

**Comment by winn69** [comment]
[log.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/7963711/log.txt)

**Comment by Mmtrx** [comment]
There is a new [Release](https://github.com/Mmtrx/FS22_BetterContracts/releases/latest) today. Please try if the error still occurs with this.

**Comment by HurrycaneBE** [comment]
also fixed with the actual release !
