### ISSUE TITLE
Adminmenü lässt sich nur einmalig aufrufen

### ISSUE THREAD

**Issue by MeRida2104** [Mmtrx/FS22_BetterContracts#204]
Hi, ich hab versucht das Adminmenü über Taste M innerhalb des Missionsmenü aufzurufen. Das klappt einmalig, beim ausblenden und wieder einblenden wird es nicht mehr angezeigt. Im Log ist folgendes zu sehen:

`2024-01-12 12:45 Error: Running LUA method 'mouseEvent'.
dataS/scripts/fieldJobs/HarvestMission.lua(421) : attempt to index field 'completionModifier' (a nil value)
2024-01-12 12:45 Error: Running LUA method 'mouseEvent'.
dataS/scripts/fieldJobs/HarvestMission.lua(421) : attempt to index field 'completionModifier' (a nil value)
2024-01-12 12:45 Error: Running LUA method 'mouseEvent'.
dataS/scripts/fieldJobs/HarvestMission.lua(421) : attempt to index field 'completionModifier' (a nil value)
2024-01-12 12:46 Error: Running LUA method 'mouseEvent'.
dataS/scripts/fieldJobs/HarvestMission.lua(421) : attempt to index field 'completionModifier' (a nil value)
2024-01-12 12:46 Error: Running LUA method 'mouseEvent'.
dataS/scripts/fieldJobs/HarvestMission.lua(421) : attempt to index field 'completionModifier' (a nil value)
2024-01-12 12:48 dataS/character/animals/wild/deer/deerAdult.i3d (23.42 ms)
`

vollständiges Log ist anhängig
[log.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/13918655/log.txt)

**Comment by Mmtrx** [comment]
Moin,
das könnte ein Folgefehler von anderen Problemen sein. Die log hat ja vor diesem Fehler andere lua callstacks.

Frage wäre, ob du den Fehler auch mit einer minimalen mod-Liste erzeugen kannst.

**Comment by MeRida2104** [comment]
Moin,

scheint wohl tatsächlich so gewesen zu sein. Konnte den Fehler nicht mehr nachstellen.

Würde das Issue daher schließen.

**Comment by MeRida2104** [comment]
Moin,

ich hatte das Problem gerade wieder. Diesmal waren zuvor keine anderen LUAs oder Errors zu finden.


[log.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/14222364/log.txt)
