### ISSUE TITLE
Forage Contracts and New version of BetterContracts

### ISSUE THREAD

**Issue by zakoattak0** [Mmtrx/FS22_BetterContracts#207]
When running the latest of Forage Contracts and Better Contracts on the mod map Vidhostice Map. There is a conflict during loading and the game gets stuck at 85%. I removed Forage Contracts and the game loads.

**Comment by Mmtrx** [comment]
Hi, there is a newer [version ](https://github.com/Mmtrx/FS22_ChaffMission/releases/tag/v1.0.3.0) here on github. Please try that.
