### ISSUE TITLE
Probleme auf Multiplayer Server

### ISSUE THREAD

**Issue by BthatKing** [Mmtrx/FS22_BetterContracts#208]
Hallo,

seitdem ich die Better Contracts Mod auf meinem Nitrado Server und PC geupdatet habe, habe ich ziemliche Probleme.
Die entsprechende Seite im Menü spinnt, wie auf den Screenshots zu sehen.

![20240113194712_1](https://github.com/Mmtrx/FS22_BetterContracts/assets/156541112/e327c915-5259-4742-8b4f-e3c19b5ea620)
![20240113194556_1](https://github.com/Mmtrx/FS22_BetterContracts/assets/156541112/56de06f8-3c21-4ceb-a6f8-aa981051b527)

Log:

[LOG-13.01.23.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/13929219/LOG-13.01.23.txt)

**Comment by BthatKing** [comment]
Wenn ich den Mod Forage Contracts rausnehme, dann funktioniert alles einwandfrei.

**Comment by Mmtrx** [comment]
Ja, HäckselMissionen von modhub ist noch nicht wirklich MP fähig. Ihr könnt solange den FS22_ChaffMission hier von GitHub nehmen.

**Comment by BthatKing** [comment]
Merci, 

Dann probiere ich das mal aus 👍
