### ISSUE TITLE
Harvest contracts stop at delivering crops

### ISSUE THREAD

**Issue by TierreAsh** [Mmtrx/FS22_BetterContracts#209]
Harvest contracts cannot be completed because then you deliver it it will say that 100% of contract is delivered (and start selling the leftovers) but in reality only 97-99% are delivered. And you can't deliver anything after that. I tried doing three contracts on wheat simultaneously - i ended up with 3 unfinished contracts after i delivered everything (and a lot of wheat leftovers which you can't deliver). I tried a HeutBeileron without mods at all - made 1 contract on oat and saved with a trailer full of oat right before the drop point. I deliver it and contract is fulfilled.  I reload the save with ONLY this mod - and the contract stops on 97% of delivery.

**Comment by TierreAsh** [comment]
It seems the problem is with the numbers which are required and are actually delivered - i tested this with 1 contract on Oat on HeutBeileron. I had 8000 liters in the truck and i was required to deliver 7200 without the mod and it successfully completed. Then i enabled BetterContracts (without changing any setting at all) - i was required to deliver 8100 liters. But then i delivered 7200 i had a message that i delivered 100% on the contract but in the contract menu i saw that it is not finished, i have still 800 liters to deliver BUT IT WOULD NEVER ACCEPT OAT again.

**Comment by Mmtrx** [comment]
Thank you for the detailed analysis. I'll try to reproduce that. Can you enable Debug mode on the BC Settings page, before delivery of contract? And upload your log.txt?

**Comment by TierreAsh** [comment]
[logs.zip](https://github.com/Mmtrx/FS22_BetterContracts/files/13994910/logs.zip)
OK. So the log1 - no mods BUT bettercontracts. I need to deliver 8100 liters of oats and have only 8000 in a trailer. I deliver it and actually get contract done (strange).
log2 - all mods on ( i have a lot but others shouldn't touch this part of contracts) - all the same - i need to deliver 8100 and have only 8000. Deliver 7200 and 800 leftover are sold. Can't add any oat to this contract. I can lower the requirements for a contract from 94% in the settings and then i get the threshold through 7200 liters the contract marks as completed.....

**Comment by DeeDeeRanged** [comment]
This can also happen without BC on some maps. I think something has changed from the FS19 to FS22 that you have to clear the field completely before you can finish with the delivery (I might be wrong). I make sure the get the field cleared for 100% before I deliver the final amount. Noticed that if the field is not 100% cleared you will never be able to finish. In FS19 if you deliver the harvest even if you have not cleared the field yet it would say completed, in other words the rest of the field you can harvest for your own as long as you have not collected the payment yet or log out as that would clear the contract.

**Comment by Mmtrx** [comment]
.. expired. Please re-open, if the situation still can be reproduced.
And thank you @DeeDeeRanged for supporting some of these issues 😃
