### ISSUE TITLE
Fix Harvest Contracts

### ISSUE THREAD

**Issue by Cassy-Blair** [Mmtrx/FS22_BetterContracts#21]
Is it possible to make a standalone Fix for the Harvest Contracts, cause i won't use Better Contracts, but i need a Fix

**Comment by Mmtrx** [comment]
Hi,
if you only need the fix, you could install BetterContracts without actually using it during gameplay. I.e. do not use the "D" button on the contracts page.

**Comment by Cassy-Blair** [comment]
> Hi, if you only need the fix, you could install BetterContracts without actually using it during gameplay. I.e. do not use the "D" button on the contracts page.

Unfortunately, this is not a solution, since the Better Contracts Mod is still active and affects the contracts

**Comment by cwattyeso** [comment]
In what way does Better Contracts Mod affect Contracts? Besides making more available and making it possible to clear and refresh the contracts screen? It let's you activate and have multiple contracts running at the same time, which is very hand to have. I have been using it since it released and can't see any negatives or reasons why anyone would not want to use it.

**Comment by Cassy-Blair** [comment]
> In what way does Better Contracts Mod affect Contracts? Besides making more available and making it possible to clear and refresh the contracts screen? It let's you activate and have multiple contracts running at the same time, which is very hand to have. I have been using it since it released and can't see any negatives or reasons why anyone would not want to use it.

Order sorting and order prices are adjusted by Better Contracts. And you can accept more than 3 orders at the same time

I play without any Contracts Mods, but wish to have a fix for the Giants KI harvest bug

**Comment by Mmtrx** [comment]
Giants will fix the harvest missions with their next patch, probably next week.
So I close this here.
