### ISSUE TITLE
Missing crop name in the harvest missions

### ISSUE THREAD

**Issue by cert23** [Mmtrx/FS22_BetterContracts#213]
Since update from Sep 25, 2023 v1.2.8.2 there is missing crop name in the list of harvest contract. In the former version form Aug 3, 2023 v1.2.8.0 its working without problems. Any other version till the latest from Jan 4 v1.2.8.7 didnt fix this problem. I tried it on new game without any mods (just better contract). I just hope its not new feature, because ability to see which crop i have to harvest on the list is really helpful. I am using czech language but that shoudnt be a problem.

![20240204101112_1](https://github.com/Mmtrx/FS22_BetterContracts/assets/34834709/6c35d141-fc32-410e-bd4a-5ae55bc37d1e)
![20240204100941_1](https://github.com/Mmtrx/FS22_BetterContracts/assets/34834709/08360d4a-6329-4e41-828b-6aa775947a4a)

**Comment by DeeDeeRanged** [comment]
I can confirm it is the same with me. Reverted back to the version which shows the crop name. Would be nice if that gets fixed or if there is a settings we can change to have it back.

**Comment by Mmtrx** [comment]
Will be fixed in next release. Or you could fix it yourself, see #222

**Comment by DeeDeeRanged** [comment]
Thanks.
