### ISSUE TITLE
Probleme mit Premium Expansion 

### ISSUE THREAD

**Issue by Cassy-Blair** [Mmtrx/FS22_BetterContracts#217]
Seit der Premium Expansion erhalte ich bei Dünge Aufträgen immer wieder folgende Warnings

`2024-03-12 13:56   Warning: **[FS22_BetterContracts]:getFromVehicle() - could not get workingWidth for 'es/Steam/steamapps/common/Farming Simulator 22/pdlc/premiumExpansion/vehicles/bednar/cs5000/cs5000.xml'`

**Comment by Mmtrx** [comment]
Ok, das kann igoriert werden.
