### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by judg393** [Mmtrx/FS22_BetterContracts#22]
So using your latest github version (that prevents harvesting by AI owners) can I check what happens if I don't complete all the harvesting contracts? Will this effect other contracts or will fields wilt as normal ?

**Comment by Mmtrx** [comment]
Yes, fields wither (and harvest contract offers remove), if they are not harvested during the appropriate months. Withered fields my offer plow/ cultivate contracts on a 50:50 chance.

**Comment by judg393** [comment]
Brilliant thank you :) I presumed it would be ok
