### ISSUE TITLE
The list previously seemed to show the culture for "Harv."

### ISSUE THREAD

**Issue by vitalii2011** [Mmtrx/FS22_BetterContracts#222]
![fsScreen_2024_05_01_13_09_34](https://github.com/Mmtrx/FS22_BetterContracts/assets/41552153/90f9aefd-9e01-4668-a25f-4b3c7adb9eaf)
![fsScreen_2024_05_01_13_09_43](https://github.com/Mmtrx/FS22_BetterContracts/assets/41552153/08350d5a-13f7-472c-85ca-d54d5c7b472f)
![fsScreen_2024_05_01_13_10_46](https://github.com/Mmtrx/FS22_BetterContracts/assets/41552153/0d5f967a-94d6-4870-b7d5-0cf43726fe04)
There are no errors in log.txt from BetterContracts, but maybe I didn’t understand it) :
[log.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/15176219/log.txt)

**Comment by Mmtrx** [comment]
was a small error in the l10n files.
```
<text name="bc_harvest" text="Собр. %s" />
```
Somehow the %s got missing. Will be repaired in next release. You can fix it yourself in the meantime 😉

**Comment by DeeDeeRanged** [comment]
Such a simple thing, but I could not fix/find it rotfl. Otherwise would have let you know.
Thanks for the update.
