### ISSUE TITLE
Multiplayer - Kein Fortschritt bei Pflügen und Grubbern

### ISSUE THREAD

**Issue by VatriXxX** [Mmtrx/FS22_BetterContracts#227]
Hallo,
wir spielen im Multiplayer die Niedersachsen 2022 Map und dort funktionieren hauptsächlich die Grubber Aufträge nicht. Beim Pflügen war es bis jetzt nur ein Auftrag, der nicht funktionierte.
Ich leihe mir das Gerät/Geräte aus, fahre zum Feld und lege los. Auf der Karte wird Saatbett angezeigt, aber kein Fortschritt zugebucht zum Auftrag. Ich habe die Mod schon deinstalliert und neu installiert, aber kein Unterschied.
Jetzt ist meine Frage, liegt das jetzt eher an der Map, das die Felder nicht richtig generiert werden oder ist Better Contract das Problem?
Denn ich versuch schon alles mögliche, das die wieder funktionieren.

![image](https://github.com/Mmtrx/FS22_BetterContracts/assets/2685763/d15a50fa-6d00-4e2c-8eee-deefb5793ec0)
![image](https://github.com/Mmtrx/FS22_BetterContracts/assets/2685763/571ebd97-2c14-4149-8ef8-f831b408b80e)

Ich habe auch den Debug angeschaltet, nur wirft der leider beim Abarbeiten des Auftrags keine Fehlermeldung oder sonstiges aus.

Mit freundlichen Grüßen
VatriXxX

**Comment by VatriXxX** [comment]
So wie es ausschaut, kann man die Grubber Aufträge nicht machen, wenn der Boden schon bearbeitet ist. Dann frage ich mich, wieso solche Aufträge dann für diese Felder generiert werden.

**Comment by Mmtrx** [comment]
Hi,
wenn das noch akut ist, kannst du mal eine log.txt hochladen, mit BC setting debug = aktiviert? Zum Zeitpunkt des aktiven Grubber-Auftrags.

**Comment by Mmtrx** [comment]
..expired
