### ISSUE TITLE
Wann werden die Feldzuordnungen zu den NPC's gespeichert?

### ISSUE THREAD

**Issue by exercise42** [Mmtrx/FS22_BetterContracts#228]
Hallo mmtrx,
vielen Dank, daß Du auch im 22er BC umgesetzt hast und laufend aktualisierst und ausbaust!
Zur aktuellen Version (1.2.8.7) hätte ich mal 'ne Frage (da ich oben keinen Discussion-Button gefunden habe, hab' ich's unter Issue gepostet):
Wann wird die Zuordnung NPC -> Feld gespeichert?
Folgende Konstellation:
Bevor ich ein Spiel beende, speichere ich den Spielstand. Dann beende ich das Spiel über den Button "Spiel beenden".
Nun kommt es manchmal vor, daß das Spiel dann hängen bleibt (den Verursacher hab' ich noch nicht gefunden), statt ins Hauptmenü zurück zu gehen. Dann muss ich das Spiel hart beenden. Starte ich dann den LS neu und lade den Spielstand, hab' ich bei den Verträgen ganz andere Eigentümer eingetragen, so als wären diese beim letzten Speichern nicht finalisiert worden. Ganz so, als ob BC hier nicht erkennt, daß es einen bestehenden Spielstand lädt.
Und ergänzend noch die Frage: Welche Konsequenzen hätte es, wenn ich nach dem Speichern das Spiel mit ALT+F4 beende? (Falls BC Daten ersten beim "Spiel beenden" finalisiert)

Schon mal vielen Dank für eine Rückmeldung

**Comment by Mmtrx** [comment]
Moin,
die NPC Zuordnungen werden beim Speichern des Spiels in der Datei farmlands.XML gespeichert. Du könntest im Savegame Ordner mal diese Datei ansehen. Es kann sein, dass der Speichervorgang nicht komplett durchgelaufen ist. Denn beim Speichern des Spielstands werden ja doch einige Dateien erzeugt. 

Ein Tip: zum Verlassen des Spiels kann man auch den kurzen Befehl "q" auf der Konsole eingeben.
