### ISSUE TITLE
Bug - NPC discount resets back to 0

### ISSUE THREAD

**Issue by ThndrDev** [Mmtrx/FS22_BetterContracts#229]
BC Settings:
Hard mode: Enabled
NPC Discount: Enabled
Discount per contract completed: 1%
Max Contracts: 20

With those settings, the mod correctly increased the discount after completing contracts with the same NPC, until reaching 20%. But after making one additional contract with the NPC, the discount reverted to 1%.

**Comment by Mmtrx** [comment]
interesting, will look into this. (assuming you didn't use the discount, i.e. by a field 😉)

**Comment by Mmtrx** [comment]
I could not reproduce that with your settings. If you can, pls upload your savegame. I.e. the situation before error occurs (20 contracts complete, 21st contract active).
