### ISSUE TITLE
Feature Request: specify for which field work type the AI is lazy

### ISSUE THREAD

**Issue by rohne83** [Mmtrx/FS22_BetterContracts#23]
With latest version you made the AI lazy not only for harvesting but also for all other contract types. But if I understand correctly this in return means that you have to accept and work on all contracts if you don't want more and more fields lying around unworked and no more progress. 
So would it be possible to configure it manually (and be it via an xml config file) for which types of field work exactly the AI is lazy? I.e. for me it's enough to get all harvesting, spraying and fertilizing contracts offered, while I don't have the equipment to do plowing, cultivating. Even for sowing it'd be enough to have the old 50:50 chance of getting the contract offered.

**Comment by Mmtrx** [comment]
Moin Rohne,
Hab deine Anfrage neulich auch schon im Giants Forum gesehen. Aber noch nicht beantwortet, weil es diese XML Config-datei natürlich noch nicht gibt. Hab aber angefangen drüber nachzudenken, sollte wohl machbar sein. Könnte was für das nächste Release sein😉.

**Comment by Mmtrx** [comment]
Done. See [v1.2.4.1](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.4.1)

**Comment by PanikPitty** [comment]
Habe ich das richtig verstanden, dass die KI jetzt wieder alles bearbeitet und ich das in den modSettings umstellen kann auf Stand V1.2.4.0?
Oder muss ich die "Faulheit" der KI in den Settings deaktivieren?

**Comment by Mmtrx** [comment]
Ja, richtig verstanden 😉. Beim ersten Start des Mods erzeugt er die Config Datei FS22_BetterContracts.xml in modSettings/. Darin steht als default `lazyNPC="false"`, heißt: KI Bauern werden nur durch Giants gesteuert.

Wenn du noch mehr Aufträge brauchst, kannst du lazyNPC auf true stellen, sowie einen oder mehrere der Arbeitstyp-Schalter, z.B. `<lazyNPC harvest="true" plowCultivate="false" sow="false" fertilize="false"/>`.

**Comment by PanikPitty** [comment]
Vielen Dank für die Antwort! Dann habe ich das der Community richtig erklärt.

Damit lohnt sich deine Mod wieder richtig! Sehr viele User werden begeistert sein.

**Comment by rohne83** [comment]
> Ja, richtig verstanden 😉. Beim ersten Start des Mods erzeugt er die Config Datei FS22_BetterContracts.xml in modSettings/. Darin steht als default `lazyNPC="false"`, heißt: KI Bauern werden nur durch Giants gesteuert.
> 
> Wenn du noch mehr Aufträge brauchst, kannst du lazyNPC auf true stellen, sowie einen oder mehrere der Arbeitstyp-Schalter, z.B. `<lazyNPC harvest="true" plowCultivate="false" sow="false" fertilize="false"/>`.

kurze Frage dazu. Die obigen Parameter sind ja ziemlich selbsterklärend. Aber weißt du zufällig in welche Kategorie die Unkrautbekämpfung (Spritzen und seit der vorletzten LS-Version gibts neu auch hacken/striegeln)? Um meine Spritzen ordentlich auszulasten will ich nämlich verhindern dass die KI selbst auf die Idee kommt das Unkraut zu bekämpfen, und vor Allem dass keine mechanische Bekämpfung stattfindet ;)

**Comment by Mmtrx** [comment]
Tja, da muss ich dich vorerst enttäuschen: weeding, herbicide behandelt meine mod gar nicht. Eigentlich auch die fertilizer  Aufträge nicht, der Schalter is future use (nächstes Release)😬

**Comment by rohne83** [comment]
wie ich sehe hast du jetzt auch weeding und spraying mit aufgenommen. Frage dazu: ich will möglichst viele Spritzaufträge bekommen, Striegeln/Hacken hingegen will ich überhaupt nicht machen. Wie bekommt man das am besten bewerkstelligt? lazyNPC für spraying auf true, das ist klar. Aber wie geht man mit weeding um? Wenn die NPCs dafür auch faul sind, verschwinden die Aufträge nie aus der Liste, wenn sie nicht faul sind hingegen, dann macht die KI das alles selbst und man bekommt wahrscheinlich ebenfalls keine Spritzaufträge...
