### ISSUE TITLE
Unable to complete the contract.

### ISSUE THREAD

**Issue by cwLOLcom** [Mmtrx/FS22_BetterContracts#231]
So the problem here is, that when you finish a "larger" contract like harvesting you can't really complete it. All of the leased vehicles disappear and the field stats change when you press the button, but the contract itself just stays in the list as "Completed" and doesnt disappear, nor gives me the money? What is the cause/solution for this issue?

**Comment by Mmtrx** [comment]
if this is still valid, do you have a log file / screenshot of the situation?
I could then try to analyze it.

**Comment by cwLOLcom** [comment]
i reinstalled the mod and disabled/enabled it a few times. I looked at the log file and seems like there was an error with a different mod anyway. Now its in full working order. Thanks for the mod!
