### ISSUE TITLE
Compatibility with Kommunal Services

### ISSUE THREAD

**Issue by FuryDee** [Mmtrx/FS22_BetterContracts#233]
SMI released a script Kommunal Services today in Modhub
Would be nice to see Better Contracts be compatible with that

**Comment by FirenzeIT** [comment]
Hi  @Mmtrx, yes i have received also an error message with this and Kommunal Services mods both not compatible, I hope this to be fixing asap, thank you for attention.

![1248130_20240705125859_1](https://github.com/Mmtrx/FS22_BetterContracts/assets/113168067/8faaf29a-b7e1-462b-97e9-de8112a8b93c)

**Comment by Mmtrx** [comment]
I'm in contact with Nikola from SMI. Next versions of KommunalServices and BC will be compatible.

**Comment by FirenzeIT** [comment]
Ok, so need to wait some time for having fixed and updated both mods,
right?

Il Mer 10 Lug 2024, 14:52 Mmtrx ***@***.***> ha scritto:

**Comment by Mmtrx** [comment]
Si.

**Comment by FirenzeIT** [comment]
> Si.

Ok, i wait and i hope asap 👍🏻

**Comment by Mmtrx** [comment]
here it [is ](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.8.8). Will also submit to modHub soon.

**Comment by le-Vinyl** [comment]
Hallo. Ich erhalte leider immer noch die Meldung das es nicht kompatibel ist.

**Comment by ChrisKeng** [comment]
Ich erhalte mit dieser Version trotzdem die Meldung, sobald ich unseren Dedi-Server betrete, dass der Mod mit Kommunal Services nicht kompatibel ist sowie deaktiviert wird?

**Comment by ChrisKeng** [comment]
Mit der neusten Version des KommunalService aus dem Modhub und deiner Version 1.2.8.8, verschwindet zwar die Meldung bzgl. der Kompatibilität, jedoch erscheinen keine Missionen mehr. Sobald ich Better Contracts deaktiviere, erscheinen die Missionen der kommunalen Dienstleistungen

**Comment by FirenzeIT** [comment]
> Mit der neusten Version des KommunalService aus dem Modhub und deiner Version 1.2.8.8, verschwindet zwar die Meldung bzgl. der Kompatibilität, jedoch erscheinen keine Missionen mehr. Sobald ich Better Contracts deaktiviere, erscheinen die Missionen der kommunalen Dienstleistungen
> 
> Auch mit X um neue Missionen zu generieren, passiert nichts.

Yes, for me too..

**Comment by Mmtrx** [comment]
Das ist leider ein Problem von Kommunal. Wenn sie die Version von BC checken, gibts n lua Fehler und der Missionstyp "kommunal" wird nicht geladen.
Hab sie grad drauf hingewiesen.

Wenn ihr nicht auf den nächsten modHub update warten wollt: im file` FS22_KommunalServices/scripts/kommunalMission.lua`
Zeile 120:
`if g_modManager:getModByName(bcName).version < bc_Ver then` 
`bcName `ersetzen durch `bc_ModName`

**Comment by FirenzeIT** [comment]
Hi Mmtrx, have you a plan for publishing new versions of ChaffMissions and LimeMissions on Modhub??

**Comment by Mmtrx** [comment]
Yes for ChaffMissions, since the modhub version still has some bugs.

**Comment by Mmtrx** [comment]
Should finally work with today's modHub update versions 😉

**Comment by FirenzeIT** [comment]
> Should finally work with today's modHub update versions 😉 

So now not needed change variables on xml right?

**Comment by Mmtrx** [comment]
Si Signor!

**Comment by FirenzeIT** [comment]
Ah bene, parli anche italiano 🙃😎 grazie.

Buon ferragosto! 😎

Il Gio 15 Ago 2024, 09:41 Mmtrx ***@***.***> ha scritto:
