### ISSUE TITLE
Problem when using years to unlock vehicles

### ISSUE THREAD

**Issue by Tomas-ody** [Mmtrx/FS22_BetterContracts#238]
When using this mod with mods: 
Through the years: https://www.farming-simulator.com/mod.php?lang=en&country=gb&mod_id=280989&title=fs2022
Vehicle years: https://www.farming-simulator.com/mod.php?lang=en&country=it&mod_id=280988&title=fs2022
then it's not working. Starting game with this mods, then better contracts doesn't work. When generating new contracts, it gives errors and will not work. Same for delete contracts function.
![image](https://github.com/user-attachments/assets/fe1d1042-fed5-49bb-9e3f-5af551bfa17c)
We tried it in multiplayer and singleplayer, but it was same. We tried to set year on 2022, so all vehicles are unlocked, finally it worked but when we changed year less then 2022 it broke and only way to fix it was to delete missions.xml, but it was only temporary because it broke again. And in multiplayer host had it from start like on screenshot broken and others normally and later broken as host.

**Comment by Thalley** [comment]
Also posted here: https://gitlab.com/thalley/fs22_through_the_years/-/issues/31

Sounds like @Mmtrx can provide at fix for this, as it's this mod that is missing a check before accesing a value (granted that in normal circumstances, that value is never `nil` and only when https://www.farming-simulator.com/mod.php?lang=en&country=ro&mod_id=280989&title=fs2022 is used

**Comment by Mmtrx** [comment]
should work with [last update](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.8.9)

In early years, some vehicle combos for contracts don't really work. @Thalley and me are thinking of a better solution in the meantime.
