### ISSUE TITLE
Better Contracts don't work

### ISSUE THREAD

**Issue by BalthasarDE** [Mmtrx/FS22_BetterContracts#239]
2024-08-23 18:19 Error: Running LUA method 'update'.
C:/Users/*user*/OneDrive/Dokumente/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/scripts/userint.lua:176: bad argument #1 to 'lower' (string expected, got nil)
![Screenshot 2024-08-23 183506](https://github.com/user-attachments/assets/8a461c99-95db-47fe-aa7b-97dda1aac582)

**Comment by Mmtrx** [comment]
Probably same as #238. Fixed in next [update ](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.8.9)
