### ISSUE TITLE
BetterContracts button incrementally adding up

### ISSUE THREAD

**Issue by mathdons** [Mmtrx/FS22_BetterContracts#243]
Each time I open the contracts menu/contracts settings, the Refresh/Add contracts buttons are added an extra time. See screenshot after multiple openings. Logs attached. 
![image](https://github.com/user-attachments/assets/a0d5b1d5-b5b1-4180-a352-7148219555bf)
[log fs.txt](https://github.com/user-attachments/files/16766424/log.fs.txt)

**Comment by Mmtrx** [comment]
I think the scripts harvestMissionFix and multiple_missions are not compatible with BC. Please try to disable those two mods.

**Comment by mathdons** [comment]
Ah yes, Harvest Mission Fix was the culprit! Thanks!
