### ISSUE TITLE
Compatibility query

### ISSUE THREAD

**Issue by judg393** [Mmtrx/FS22_BetterContracts#245]
https://www.farming-simulator.com/mod.php?lang=en&country=jp&mod_id=245521&title=fs2022

Does anyone have any experience running these together anything I should be concerned about as both mods reduce land price

**Comment by Mmtrx** [comment]
Hi,
not sure what will happen. But I don't think that running BC with FarmlandAuctions will break a game. Just try it out!

**Comment by judg393** [comment]
Hi I have tried it and it seems to be ok though I must admit I've not seen any auctions yet 🤣
