### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by RoberT162v** [Mmtrx/FS22_BetterContracts#247]
<?xml version="1.0" encoding="utf-8" standalone="no"?>
    <l10n>
	  <texts>
		
		<text name = "input_MENU_EXTRA_3" text = "Contratos mejorados: Detalles on/off"/>
		<text name = "input_BC_MTOGGLE" text = "BC: Alternar visualización de contratos agrícolas activos"/>
		<text name = "bc_actionFerment" text = "Paca fermentada"/>
		
		<text name="bc_hidden" text="Ocultar: %d" />
		<text name="bc_other" text="Otro" />
		<text name="bc_new_contracts" text="Nuevos Contratos" />
		<text name="bc_clear_contracts" text="Limpiar contratos" />
		<text name="bc_detailsOff" text="Detalles off" />
		<text name="bc_detailsOn" text="Detalles on" />

		
		<text name="bc_mowed" text="Segar:" />
		<text name="bc_tomow" text="Para segar:" />
		<text name="bc_chaff" text="Segar %s" />
		<text name="bc_jobType_chaff" text="Forraje" />
		<text name="bc_harvest" text="Cosecha " />
		<text name="bc_leased" text="/ Arrendado " />
		<text name="bc_enoughMissions" text="Su granja ya tiene el número máximo de contratos." />
		<text name="bc_jobsCompleted" text="Trabajos completados: %d" />
		<text name="bc_monthlyLimit" text="Tu granja ha alcanzado el número máximo de contratos para este mes." />

		
		<text name="bc_penalty" text="Penalización" />
		<text name="bc_warnTimeout" text="Complete su(s) %d contrato(s) antes de la medianoche para evitar penalizaciones." />
		<text name="bc_warnCancel" text=" La penalización del contrato será de al menos " />
		<text name="bc_leaseNotEnough" text="Debe completar %d trabajos más para %s con su propio equipo, antes de poder tomar prestadas las máquinas." />

		
		<text name="bc_maxJobs" text="Ha alcanzado el descuento máximo para %s." />
		<text name="bc_discount" text=" (%d%% descuento)" />
		<text name="bc_discValue" text="%s le otorga %d %% de descuento para futuras compras de campo." />
		<text name="bc_owner" text="Dueño:" />

		
		<text name="SC_widhei" text="Ancho/ Largo Max.:" />
		<text name="SC_worktim" text="Tiempo estimado:" />
		<text name="SC_price" text="Precio:" />
		<text name="SC_profpmin" text="Beneficio/min:" />
		<text name="SC_sort" text="Clasificar" />

		<text name="SC_field" text="Campo %d / %s" />
		<text name="SC_fillType" text="Tipo de mercancía:" />
		<text name="SC_worked" text="Campo trabajado:" />
		<text name="SC_delivered" text="Entregado:" />
		<text name="SC_deliver" text="Debe entregar:" />
		<text name="SC_keep" text="Puede quedarse con:" />
		<text name="SC_profit" text="Beneficio por la cosecha:" />
		<text name="SC_profitSupply" text="Beneficio:" />
		<text name="SC_usage" text="Necesario:" />
		<text name="SC_cost" text="Coste del material:" />
		<text name="SC_togo" text="Falta por entregar:" />
		<text name="SC_timeleft" text="Tiempo restante:" />

		
		<text name="bc_progField" text="Progreso en campo" />
		<text name="bc_progDeliver" text="Progreso de la entrega" />

		
		<text name="SC_sortCat" text="tipo de misión" />
          <text name="SC_sortRev" text="beneficio" />
		<text name="SC_sortNpc" text="granjero" />
		<text name="SC_sortProf" text="beneficio neto" />
		<text name="SC_sortpMin" text="beneficio por minuto" />

		
		<text name="bc_settingsPage_title" text="Configuración de contratos" />

		<text name="bc_baseSettings" text="Configuración básica" />
		<text name="bc_rewardMultiplier" text="Recompensa" />
		<text name="bc_rewardMultiplier_tooltip" text="Ajuste las recompensas para los contratos ofrecidos." />
		<text name="bc_rewardMultiplierMow" text="Recompensa por segar y empacar" />
		<text name="bc_rewardMultiplierMow_tooltip" text="Ajuste las recompensas por segar y empacar según los contratos ofrecidos." />
		<text name="bc_leaseMultiplier" text="Coste de alquiler" />
		<text name="bc_leaseMultiplier_tooltip" text="Ajustar el coste de alquiler de equipos para los contratos." />
		<text name="bc_maxActive" text="Contratos activos simultáneamente" />
		<text name="bc_maxActive_tooltip" text="Número máximo de contratos activos simultáneamente." />
		<text name="bc_toDeliver" text="Entrega en contratos de cosecha" />
		<text name="bc_toDeliverBale" text="Entrega para contratos de empacado" />
		<text name="bc_toDeliver_tooltip" text="Porcentaje del rendimiento total estimado que debe entregar para completar un contrato de cosecha." />
		<text name="bc_fieldCompletion" text="Trabajo de campo completo" />
		<text name="bc_fieldCompletion_tooltip" text="Porcentaje mínimo del área de campo trabajada, para contar como trabajo de campo completo." />
		<text name="bc_refreshMP" text="Lista de permisos para contratos" />
		<text name="bc_refreshMP_tooltip" text="Quién puede eliminar/actualizar contratos en un juego MP." />
		<text name="bc_ferment" text="Fermentación instantánea" />
		<text name="bc_ferment_tooltip" text="Permite al jugador fermentar instantáneamente una paca envuelta desde el menú F1." />
		<text name="bc_forcePlow" text="Arado de cultivos de raíces" />
		<text name="bc_forcePlow_tooltip" text="Cada cosecha de maíz/patata/remolacha azucarera requiere un arado posterior." />
		<text name="bc_debug" text="Debug Modus" />
		<text name="bc_debug_tooltip" text="Registra mensajes de información en el registro si está activo. Puede ayudar a encontrar errores." />

		<text name="bc_lazyNPC" text="Agricultores perezosos" />

		<text name="bc_mainSwitch" text="Activado" />
		<text name="bc_active" text="Activado" />
		<text name="bc_lazyNPC_tooltip" text="Si está activo, los agricultores NPC a menudo se saltan el trabajo en sus campos. Así se pueden ofrecer más contratos." />
		<text name="bc_lazyNPCHarvest_tooltip" text="Si está activo, los agricultores NPC no cosechan nada. Podría resultar en mucho trabajo para usted." />
		<text name="bc_lazyNPCSow_tooltip" text="Si está activo, los agricultores NPC realizan trabajos de siembra con menos frecuencia y los ofrecen como contratos en su lugar." />
		<text name="bc_lazyNPCPlow" text="Arar y cultivar" />
		<text name="bc_lazyNPCPlow_tooltip" text="Si están activos, los agricultores NPC aran o cultivan con menos frecuencia por su cuenta." />
		<text name="bc_lazyNPCFertilize_tooltip" text="Si está activo, el agricultor NPC realiza el trabajo de fertilización con menos frecuencia y lo ofrece como contratos en su lugar." />
		<text name="bc_lazyNPCWeed_tooltip" text="Si está activo, los agricultores NPC combaten las malas hierbas en sus campos con menos frecuencia y, en cambio, ofrecen contratos de fumigación y desherbado." />

		<text name="bc_hardMode" text="Dificultad alta" />
		<text name="bc_hardMode_tooltip" text="Si está activo, todos los contratos activos deben completarse a fin de mes a más tardar. Cancelar un contrato tendrá un coste de penalización. El equipo alquilado para el contrato solo se desbloquea después de completar algunos trabajos." />
		<text name="bc_hardPenalty" text="Penalización" />
		<text name="bc_hardPenalty_tooltip" text="Importe de la penalización por contrato cancelado (en % de la recompensa del contrato)." />
		<text name="bc_hardLease" text="Desbloquear equipo de alquiler" />
		<text name="bc_hardLease_tooltip" text="Número de trabajos exitosos para un agricultor NPC, antes de que te presten su equipo." />
		<text name="bc_hardExpire" text="Fecha límite" />
		<text name="bc_hardExpire_tooltip" text="Al final de qué período de tiempo deben completarse todos los contratos activos." />
		<text name="bc_hardLimit" text="Contratos por mes" />
		<text name="bc_hardLimit_tooltip" text="Número máximo de contratos que se pueden aceptar durante un mes. (-1: sin límite, 0: sin contratos)" />

		<text name="bc_discountMode" text="Descuento en la compra de un campo" />
		<text name="bc_discountMode_tooltip" text="Si está activo, un agricultor NPC otorga un descuento en las compras de tierras de cultivo. El descuento aumenta con el número de trabajos completados para este agricultor." />
		<text name="bc_discPerJob" text="Descuento por contrato completado" />
		<text name="bc_discPerJob_tooltip" text="Un agricultor NPC aumenta su descuento en esta cantidad por cada trabajo completado. El descuento máximo no puede superar el 50%." />
		<text name="bc_discMaxJobs" text="Número de trabajos completados para el descuento máximo" />
		<text name="bc_discMaxJobs_tooltip" text="Puede reducir el descuento máximo, p. descuento por contrato = 11%, número de trabajos = 3 -> descuento máximo = 33%. Precaución: el número actual de trabajos completados disminuirá en este valor en la compra de tierras de cultivo." />
				
		<text name="bc_missionGeneration" text="Generación de contratos" />
		<text name="bc_generationInterval" text="Intervalo de generación" />
		<text name="bc_generationInterval_tooltip" text="Cantidad de horas en el juego para esperar antes de generar nuevos contratos." />
		<text name="bc_missionGenPercentage" text="Porcentaje de generación" />
		<text name="bc_missionGenPercentage_tooltip" text="Porcentaje de contratos máximos que se generarán cada vez." />
	  </texts>
    </l10n>

**Comment by RoberT162v** [comment]
Hi, I'm sending you the Spanish translation, in case you want to add it.
Regards

**Comment by Mmtrx** [comment]
Thank you, will update that in next release.
