### ISSUE TITLE
Can't accept more than 2 Contracts - Better Contracts

### ISSUE THREAD

**Issue by greekfire-223** [Mmtrx/FS22_BetterContracts#251]
I don't seem to be able to accept more than two active contracts at a time despite playing with the 'Concurrently Active Contracts' setting to up to '10' 

I also have 'Higher Difficulty' disabled and just to make sure I enabled it and changed 'Contracts per Month' from '-1' to '5'

I'm going to uninstall Better Contracts through FS22 and ensure the file is removed from the 'Mods' folder and will try reinstalling it here from Github. 
Will update as to how this went.

**Comment by greekfire-223** [comment]
I've found the issue. I have another Mod called Challenge Mode where the default setting for 'Max Missions' was 2

Please ignore my previous post there is no issue with Better Contracts. Thank you for the great Mod!

**Comment by Mmtrx** [comment]
Thank you for clearing this😀.
