### ISSUE TITLE
[Question] FS25 ideas?

### ISSUE THREAD

**Issue by rohne83** [Mmtrx/FS22_BetterContracts#252]
Es gibts ja jetzt auch erste Videos zum Missionssystem im LS25. Leider in meinen Augen eine absolute Verschlimmbesserung was Giants da gemacht hat. BetterContracts wird da also definitiv noch nötiger sein als zuvor, und so einige neue Funktionen brauchen.
Was mir da direkt auffällt:
- man kann ein Feld im LS25 nicht mehr bis zum Ende bearbeiten. Sobald 100% erreicht sind, scheint der Auftrag automatisch abgeschlossen zu werden. Das sollte unbedingt wieder beseitigt werden, so dass man vernünftig zu Ende arbeiten kann.
- Ballenmissionen werden leider in alle einzelnen Schritte aufgeteilt (aber davon gibts dann scheinbar nur Mähen und Ballen pressen), und das Spiel schreibt unnötigerweise sogar vor welcher Ballentyp zu pressen ist. Sollte wenn möglich zurückgebaut werden aufs alte System, dass man einfach auch die komplette Kette von Mahd über Wenden/Wickeln/Schwaden/Pressen/Häckseln bis zur Ablieferung mit seiner vorhandenen Grünlandtechnik abarbeiten und Ballen seiner Wahl pressen kann. Und ganz wichtig natürlich für anstatt Presse wieder mit Ladewagen bzw für Grassilage auch mit Häcksler angerückt werden kann, ohne dass jeder Furz da vorgeschrieben wird.
- Die Statusleisten am rechten Bildschirmrand, find ich ultra nervig. Sofern die nicht vanilla-mäßig ausgeblendet werden können, müsste das wohl auch betterContracts übernehmen. Bei Erntestart hab ich nicht selten mehr als 20 offene Missionen, das HUD wäre dann überhaupt nicht mehr nutzbar, weil voll mit diesen Statusleisten.

**Comment by coatsy35** [comment]
agreed. I can't believe they allow a field to be finished before it is 100% covered. That is very poor.

**Comment by Oberlump** [comment]
Stimme voll und ganz zu. Vermutlich hat man das so gelöst, damit eben keine Erträge über dem Auftrag hinaus generiert werden können.

Weitere Idee:

- Strohsammeln auf Auftragsfeldern ermöglichen (sofern BetterContracts da überhaupt irgendwie eingreifen kann).
