### ISSUE TITLE
Will the mod also be implemented by you in FS25? 

### ISSUE THREAD

**Issue by ImperialTex** [Mmtrx/FS22_BetterContracts#253]
Will the mod also be implemented by you in FS25? 
I really like your work!

**Comment by Mmtrx** [comment]
Yes, I will start work on that soon, but since the contract system has undergone a major redesign, upgrading my mod will take some time🤓.

**Comment by ImperialTex** [comment]
Thats great to hear! 

My Main Problem is the max Contracts.. its only 3 and i play with 8 friends on a server. But this could do a easy lua script to increase the max number to maybe 5? Or do you think for smth like this we need to wait for the giants editor 10 upgrade

**Comment by atothadam** [comment]
@Mmtrx I'm a developer myself, so if i can help you with upgrading, or reviewing the code, etc, just let me know! :) In the fs22 i already modified your mod for my friends.
