### ISSUE TITLE
Probleme mit V1.2.4.0

### ISSUE THREAD

**Issue by MeRida2104** [Mmtrx/FS22_BetterContracts#26]
Hi,

ich habe gestern Abend auf die 1.2.4.0 aktualisiert. Seitdem verhält sich BetterContracts m.M.n. fehlerhaft.

Hier mal was mir aufgefallen ist:

Beim ersten Aufruf des Missionsmenüs sieht das Menü folgendermaßen aus:
![image](https://user-images.githubusercontent.com/96819380/185360335-de01edf7-fe23-4ffa-adfe-8f9a874c1707.png)

Einmal bspw. ins Tiermenü und zurück geklickt siehts dann so aus: (es fehlen die Buttons am unteren Rand (Neue Verträge, Liste löschen etc.)
![image](https://user-images.githubusercontent.com/96819380/185360500-bd61427d-d6f6-458f-a417-3e92d9a15dd4.png)

Außerdem wird bis auf Ballenmissionen nichts anderes angezeigt, obwohl Felder erntereif sind.

Kannst du dir das bitte ansehen? :) Hier noch das Log:

[log.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/9372235/log.txt)

**Comment by vitalii2011** [comment]
```
Error: Running LUA method 'mouseEvent'.
C:/Users/…/Documents/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/betterContracts.lua:383: attempt to compare nil with number
```

**Comment by Mmtrx** [comment]
Sorry, durch das update gestern hatte mein mod das Bewusstsein für die Liefer- und Transportaufträge (FS22_SupplyTransportContracts) verloren. Sollte jetzt wieder gehen, bitte das gleiche Release [1.2.4.0](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.4.0) nochmal laden.

**Comment by MeRida2104** [comment]
Probiere ich gleich mal aus 👍 Danke für deine Arbeit in diesem tollen Mod 🙃

**Comment by MeRida2104** [comment]
Funktioniert wieder :)
