### ISSUE TITLE
Felder kommen nicht als Ernteauftrag sondern direkt als Pflug Auftrag

### ISSUE THREAD

**Issue by Chaosfamily1207** [Mmtrx/FS22_BetterContracts#27]
Hallo

leider haben wir das Problem das teileweise Felder nicht als Ernteauftrag kommen sondern direkt ein Pflugauftrag für das Erntereife Feld. Selbst wenn noch einige Tage Erntezeit übrig sind wird das Feld dann bei Annahme des Pflugauftrags auf verdorrt gesetzt

**Comment by MeRida2104** [comment]
Habe auch mit der neuen Version große Probleme (was sie eigentlich komplett unbrauchbar macht). Siehe https://github.com/Mmtrx/FS22_BetterContracts/issues/26

**Comment by BJ262** [comment]
Hallo,
ich kann mit der v1.2.4.0 auch nichts mehr machen. Habe das selbe wie in #26 gepostet wurde. Zudem erscheinen bei mir überhaupt keine Aufträge mehr.
Das Problem das Erntereife Felder als Pflugaufträge erscheinen, ist auch mit der v1.2.3.2 schon. Neuen Spielstand angefangen, wo einige Felder geerntet werden konnten, werden zum Teil als Pflug und zum Teil zum Ernten gelistet. Macht man nichts und lässt den Auftrag stehen verdorren die Felder zum Pflügen mit dem Tageswechsel oder wie oben genannt bei Annahme sofort. Ob es danach sich so verhält, das es nur bei einem neu angefangen Spielstand so ist oder später auch noch passiert, kann ich derzeit noch nicht sagen.

**Comment by Mmtrx** [comment]
Problem #26 sollte gelöst sein, einfach Release v.1.2.4.0 hier nochmal runterladen.

Dass erntereife Felder als Pflug-Auftrag erscheinen, ist wohl ein nicht so einfach zu lösendes Thema. Daher empfehle ich euch zunächst auf [v1.2.3.1](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.3.1) zurückzugehen.

@BJ262, bevor du das machst, kannst du mir bitte noch eine log.txt hochladen, wo das Problem auftritt?

**Comment by Chaosfamily1207** [comment]
Mach dir jetzt nicht zuviel Arbeit bei der Fehlersuche. Dienstag kommt ein Patch wo das Auftragsproblem allgemein gelöst sein soll. Hab eben bei Giants im DC nachgefragt

**Comment by BJ262** [comment]
Habe jetzt die v1.2.4.0 noch mal geladen und dies funtioniert wieder wie gewohnt. Allerdings habe ich bemerkt das Saisonale Wachstum bei mir aktiv ist. Habe es normaler Weise ausgeschaltet, was erklären würde, warum die Frucht verrottet. Werde erst einmal weiter testen und in der Log habe ich keine Fehler angezeigt bekommen. Bis zum Patch kann ich damit leben, die Hauptsache es kommen Aufträge und dafür bin ich dankbar das wenigstens einer sich dem Problem angenommen hat.

**Comment by cwattyeso** [comment]
Am kinda wondering what effects of conflicts there may be now we have Patch 1.7 from Giants with their attempt to fix and improve contracts and Better Contracts Version 1.2.4.0?

One thing I maybe noticed yesterday for me is that contract prices seem to have gone down massively, not sure if that means another mod I use for multiplying and increasing contract price multipliers is not working with update 1.7 or whether something in Better Contracts conflicts with that mod now.

**Comment by Mmtrx** [comment]
Denke, hat sich erledigt, spätestens mit Patch 1.7.1. Sicherheitshalber kann man in meinem neuesten Release [v1.2.4.1](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.4.1) alle Eingriffe des Mods in die NPC Aktivitäten abschalten: `lazyNPC="false"` in der xml config file in modSettings/.
