### ISSUE TITLE
Feature request: Marking which active jobs were with leased equipment and which not

### ISSUE THREAD

**Issue by throsten** [Mmtrx/FS22_BetterContracts#28]
Sometimes I forget which one of multiple active jobs was with the equipment. I prefer to do them at the end. In rare cases finished jobs were closed at a game restart and then I loose the equipment (sometimes together with grain).  Today you could see equipment equiped  jobs only before start and after finishing (for the fee). Maybe you are interested in programming a special marking or so.  It's just an idea. Thx.

**Comment by Mmtrx** [comment]
Done. See [v1.2.4.1](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.4.1)
