### ISSUE TITLE
Frage für kleine Änderungen 

### ISSUE THREAD

**Issue by sCorporation2022** [Mmtrx/FS22_BetterContracts#29]
Hallo

Erstmal vielen Dank für diesen tollen Mod

1.  Ist es möglich, die Löschen oder Erneuern der Aufträge zu entfernen oder zumindest diese nur für den Admin zugänglich zu machen?
2. Ich hätte gerne die Beschränkung auch wieder, dass man nur max. 3 Aufträge machen kann. Wäre das möglich?
Vielleicht könntest du mir sagen, wie ich das verändern könnte oder ist das doch ein größerer Aufwand, als ich denke?

Vielen Dank für die Hilfe. Mir reicht auch, wenn du mir evtl. sagst, wo ich was ändern müsste?

LG

**Comment by Mmtrx** [comment]
Done. See [v1.2.4.1](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.4.1)

**Comment by sCorporation2022** [comment]
Vielen Dank für die schnelle Umsetzung. Kannst du mir aber nun sagen, wo oder in welcher Datei ich die max ANzahl der Aufträge anpassen kann?

**Comment by Mmtrx** [comment]
Moin,
der Mod liest die Einstellungen aus modSettings/FS22_BetterContracts.xml. Da müsstest du deine Änderungen machen. 
config.xml ist nur die Vorlage, die nach modSettings kopiert wird, wenn dort noch keine  FS22_BetterContracts.xml vorhanden ist.

**Comment by sCorporation2022** [comment]
Achso das wusste ich nicht :) Vielen Dank. 

Noch evtl. eine andere Bitte... Für Aufträge die man ablehnt... gibt es da ne Möglichkeit eine Vertragsstrafe einzubauen, so wie bei den Lieferaufträgen?
