### ISSUE TITLE
feature request: enable pdlc for requiredMod or create requiredPDLC

### ISSUE THREAD

**Issue by sashaman** [Mmtrx/FS22_BetterContracts#30]
greetings, 

could you possibly enable parsing for pdlc to be able to have the DLCs recognized in userDefined.xml ? 
like in `requiredMod="kubotaPack"` or `required(P)Dlc="kubotaPack"`

thx in advance!

**Comment by sashaman** [comment]
p.s.: 
since dlcs (as well as maps, meanwhile also mods iirc) are adding themselves into missions, how is the current behaviour if 
```
                 You can delete any base game or map-defined mission vehicles (and thus use only those
                 that you defined) by setting overwrite="true" in the <missionVehicles> tag.  

```
? are those overwritten as well? that'd make it almost a requirement to be able to add them back in :P

**Comment by sashaman** [comment]
so far i come to the conclusion, that DLC's are gone from the list - obviously lol 
i can't find a way to have it properly recognize $pdlc/$pdlc$/whatever

**Comment by sashaman** [comment]
was noch helfen könnte wäre, wenn man das equip welches aus maps/dlc etc. geladen wird als ausnahme hinzufügen könnte, damit es nicht überschrieben wird

**Comment by Mmtrx** [comment]
..expired
