### ISSUE TITLE
Train Contracts Being Created for Silage, Grass, Hay Bales when not accepted at Station

### ISSUE THREAD

**Issue by ajFarmerModding** [Mmtrx/FS22_BetterContracts#33]
Hello, 
I am the Author of Griffin Indiana 22 map.
I have had several feedback post about Contracts wanting the player to deliver silage, grass, or hay to the maps off map train station "Mt Vernon, Illinois"  via the train.
However the Train Selling station does not accept those the way I have it set up. It only happens to players using the Better Contract Mod and I believe when they refresh contracts is when the bug appears. If you feel there is not a fix on your end or do not have the time to look into let me know, as I may have a work around for users of Better Contracts that may work on my map.

The Griffin Indiana 22 Support Thread has a on going conversation about the bug if that helps. After more consideration it may be a Giants bug and Better Contracts just exposes it more. Train contracts to ElmCreek were removed several updates ago, This may have been the reason.

https://forum.giants-software.com/viewtopic.php?f=963&t=193247&p=1535376#p1535376

Thank You
 ajFarmer

**Comment by Mmtrx** [comment]
Hi ajFarmer,
I was busy with a new Release [v1.2.4.1](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.4.1), and now have some time to look into this. I think you're right that BetterContracts is just exposing the problem, since it lets the engine generate more contracts more often.

When the game generates a mow-bale (or a harvest) contract, it checks all unloading stations 
- if they allow missions
- if they accept the corresponding filltype (hay or silage)

and then picks the one with the highest price for the filltype.
So the erroneous contracts to deliver bales to Mt Vernon are a consequence of somehow the game determined that this unloading station accepts hay/ silage/ cotton..

You may also want to check @cwattyesos comment about Giants patch 1.7.1 in #32.

Meanwhile, congrats to your map, and to your lively support thread! We don't see many modders who are such responsive to their users 😉 .

**Comment by sashaman** [comment]
this is the same way it was working in fs19, 
if you have a selling station and put a filltype in it, that is available as a bale - grass, hay, silage - the game will generate mow missions to that specific sales point - you have to make sure you either add baleTrigger or remove those filltypes

regards :)

**Comment by ajFarmerModding** [comment]
@sashaman 
STRAW DRYGRASS_WINDROW GRASS_WINDROW SILAGE fill types are not included at the Mt Vernon station yet bailing  contracts are being generated to deliver there. I also have several reports of cotton contracts being generated to be delivered there as well. Open Air Garden I believe is helping to expose the mission.lua bug for cotton.
I have also had few reports of 100% vanilla saves with all bale types plus cotton going there. So I have made the decision to remove the train missions the same as Giants did with Elmcreek.

`<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<placeable type="sellingStation" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../shared/xml/schema/placeable.xsd">
    <storeData>
        <name>$l10n_station_mountVernon</name>
        <image>$data/store/store_empty.png</image>
        <price>0</price>
        <canBeSold>false</canBeSold>
        <showInStore>false</showInStore>
        <lifetime>1000</lifetime>
        <rotation>0</rotation>
        <brand>NONE</brand>
        <species>placeable</species>
        <category>placeableMisc</category>
        <vertexBufferMemoryUsage>0</vertexBufferMemoryUsage>
        <indexBufferMemoryUsage>0</indexBufferMemoryUsage>
        <textureMemoryUsage>0</textureMemoryUsage>
        <instanceVertexBufferMemoryUsage>0</instanceVertexBufferMemoryUsage>
        <instanceIndexBufferMemoryUsage>0</instanceIndexBufferMemoryUsage>
        <audioMemoryUsage>0</audioMemoryUsage>
    </storeData>

    <base>
        <filename>$data/placeables/mapUS/sellingStationTrain/sellingStationTrain.i3d</filename>
    </base>

    <placement useRandomYRotation="false" useManualYRotation="true" />

    <clearAreas></clearAreas>

    <leveling></leveling>

    <indoorAreas></indoorAreas>

    <ai>
        <updateAreas></updateAreas>
    </ai>

    <hotspots>
      <hotspot type="UNLOADING_TRAIN" worldPosition="-1030 426.987" />
    </hotspots>

    <sellingStation fillTypeCategories="TRAINWAGON" supportsExtension="false" litersForFullPriceDrop="400000" fullPriceRecoverHours="48" allowMissions="false">
        <fillType name="WHEAT"            priceScale="1" supportsGreatDemand="true" disablePriceDrop="false" />
        <fillType name="BARLEY"           priceScale="1" supportsGreatDemand="true" disablePriceDrop="false" />
        <fillType name="OAT"              priceScale="1" supportsGreatDemand="true" disablePriceDrop="false" />
        <fillType name="CANOLA"           priceScale="1" supportsGreatDemand="true" disablePriceDrop="false" />
        <fillType name="SORGHUM"          priceScale="1" supportsGreatDemand="true" disablePriceDrop="false" />
        <fillType name="GRAPE"            priceScale="1" supportsGreatDemand="true" disablePriceDrop="false" />
        <fillType name="OLIVE"            priceScale="1" supportsGreatDemand="true" disablePriceDrop="false" />
        <fillType name="SUNFLOWER"        priceScale="1" supportsGreatDemand="true" disablePriceDrop="false" />
        <fillType name="SOYBEAN"          priceScale="1" supportsGreatDemand="true" disablePriceDrop="false" />
        <fillType name="MAIZE"            priceScale="1" supportsGreatDemand="true" disablePriceDrop="false" />
        <fillType name="POTATO"           priceScale="1" supportsGreatDemand="true" disablePriceDrop="false" />
        <fillType name="SUGARBEET"        priceScale="1" supportsGreatDemand="true" disablePriceDrop="false" />
        <fillType name="WOODCHIPS"        priceScale="1" supportsGreatDemand="true" disablePriceDrop="false" />
        <fillType name="SUGARCANE"        priceScale="1" supportsGreatDemand="true" disablePriceDrop="false" />
        <fillType name="SEEDS"            priceScale="0.38" supportsGreatDemand="true" disablePriceDrop="false" />
    </sellingStation>
</placeable>`

**Comment by sashaman** [comment]
ok, i dare to affirm this can be "fixed" by replacing filltypeCategories= with its respective filltypes= 
kinda incomplete script :P

**Comment by ajFarmerModding** [comment]
@sahaman
I have made the following changes as you suggested, No errors and no conflicts in my testing. However I think it needs to be fully tested by the masses to see if it fixes the bug. Thank you!

` <sellingStation fillTypes="WHEAT BARLEY OAT CANOLA SORGHUM GRAPE OLIVE SUNFLOWER SOYBEAN MAIZE POTATO SUGARBEET WOODCHIPS SUGARCANE SEEDS" supportsExtension="false" litersForFullPriceDrop="400000" fullPriceRecoverHours="48" allowMissions="true">
        <fillType name="WHEAT"            priceScale="1" supportsGreatDemand="true" disablePriceDrop="false" />
        <fillType name="BARLEY"           priceScale="1" supportsGreatDemand="true" disablePriceDrop="false" />
        <fillType name="OAT"              priceScale="1" supportsGreatDemand="true" disablePriceDrop="false" />
        <fillType name="CANOLA"           priceScale="1" supportsGreatDemand="true" disablePriceDrop="false" />
        <fillType name="SORGHUM"          priceScale="1" supportsGreatDemand="true" disablePriceDrop="false" />
        <fillType name="GRAPE"            priceScale="1" supportsGreatDemand="true" disablePriceDrop="false" />
        <fillType name="OLIVE"            priceScale="1" supportsGreatDemand="true" disablePriceDrop="false" />
        <fillType name="SUNFLOWER"        priceScale="1" supportsGreatDemand="true" disablePriceDrop="false" />
        <fillType name="SOYBEAN"          priceScale="1" supportsGreatDemand="true" disablePriceDrop="false" />
        <fillType name="MAIZE"            priceScale="1" supportsGreatDemand="true" disablePriceDrop="false" />
        <fillType name="POTATO"           priceScale="1" supportsGreatDemand="true" disablePriceDrop="false" />
        <fillType name="SUGARBEET"        priceScale="1" supportsGreatDemand="true" disablePriceDrop="false" />
        <fillType name="WOODCHIPS"        priceScale="1" supportsGreatDemand="true" disablePriceDrop="false" />
        <fillType name="SUGARCANE"        priceScale="1" supportsGreatDemand="true" disablePriceDrop="false" />
        <fillType name="SEEDS"            priceScale="0.38" supportsGreatDemand="true" disablePriceDrop="false" />
    </sellingStation>`

**Comment by ajFarmerModding** [comment]
Turns out Auger With Lime was perhaps responsible with the contracts Sashamans suggestion should fix it.

Auger With Lime
`<fillTypeCategories>
        <fillTypeCategory name="AUGERWAGON" >LIME PIGFOOD</fillTypeCategory>
        <fillTypeCategory name="TRAINWAGON" >WHEAT BARLEY OAT CANOLA SUNFLOWER SOYBEAN MAIZE POTATO SUGARBEET SUGARBEET_CUT MANURE SEEDS FORAGE FORAGE_MIXING CHAFF WOODCHIPS SILAGE STRAW GRASS_WINDROW DRYGRASS_WINDROW SUGARCANE FERTILIZER PIGFOOD LIME SNOW ROADSALT SORGHUM OLIVE STONE MINERAL_FEED</fillTypeCategory>
    </fillTypeCategories>`
GRIN22 1.0 and 1.1 sellingStationTrain.xml same as vanilla Elmcreek
`<sellingStation fillTypeCategories="TRAINWAGON" supportsExtension="false" litersForFullPriceDrop="400000" fullPriceRecoverHours="48" allowMissions="true">`
GRIN22 1.2 Fixed
`<sellingStation fillTypes="WHEAT BARLEY OAT CANOLA SORGHUM GRAPE OLIVE SUNFLOWER SOYBEAN MAIZE POTATO SUGARBEET WOODCHIPS SUGARCANE SEEDS" supportsExtension="false" litersForFullPriceDrop="400000" fullPriceRecoverHours="48" allowMissions="true">`

**Comment by Mmtrx** [comment]
Ok I think this can be closed here, since another Mod was the culprit. Messing up fillType categories, and thus leading to an overwritten fillType list for the train selling station. See https://forum.giants-software.com/viewtopic.php?f=963&t=193247&start=525
