### ISSUE TITLE
LUA Callstacks mit aktueller Version

### ISSUE THREAD

**Issue by Gecko774** [Mmtrx/FS22_BetterContracts#34]
Hallo,

ich habe vorhin einmal die neue Version getestet aber es treten leider LUA´s auf und dabei hängt sich das komplette Menü auf.

MfG

>2022-09-10 16:51 Error: overwrittenFunction 'newFunc' cannot be nil
2022-09-10 16:51 LUA call stack:
  =C:/Users/Flo/Documents/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/scripts/Utility.lua (21) : printCallstack
  =C:/Users/Flo/Documents/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/betterContracts.lua (197) : overwrittenFunction
  =[C] (4294967295)
  =C:/Users/Flo/Documents/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/scripts/RoyalMod.lua (234) : xpcall
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/gui/MPLoadingScreen.lua (778) : validateTypes
  dataS/scripts/misc/AsyncTaskManager.lua (41) : lambda
  dataS/scripts/misc/AsyncTaskManager.lua (120) : runLambda
  dataS/scripts/misc/AsyncTaskManager.lua (146) : runTopTask
  dataS/scripts/main.lua (1162) : update
2022-09-10 16:51 Error: appendedFunction 'newFunc' cannot be nil
2022-09-10 16:51 LUA call stack:
  =C:/Users/Flo/Documents/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/scripts/Utility.lua (54) : printCallstack
  =C:/Users/Flo/Documents/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/betterContracts.lua (198) : appendedFunction
  =[C] (4294967295)
  =C:/Users/Flo/Documents/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/scripts/RoyalMod.lua (234) : xpcall
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/gui/MPLoadingScreen.lua (778) : validateTypes
  dataS/scripts/misc/AsyncTaskManager.lua (41) : lambda
  dataS/scripts/misc/AsyncTaskManager.lua (120) : runLambda
  dataS/scripts/misc/AsyncTaskManager.lua (146) : runTopTask
  dataS/scripts/main.lua (1162) : update
2022-09-10 16:51 Error: appendedFunction 'newFunc' cannot be nil
2022-09-10 16:51 LUA call stack:
  =C:/Users/Flo/Documents/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/scripts/Utility.lua (54) : printCallstack
  =C:/Users/Flo/Documents/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/betterContracts.lua (199) : appendedFunction
  =[C] (4294967295)
  =C:/Users/Flo/Documents/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/scripts/RoyalMod.lua (234) : xpcall
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/gui/MPLoadingScreen.lua (778) : validateTypes
  dataS/scripts/misc/AsyncTaskManager.lua (41) : lambda
  dataS/scripts/misc/AsyncTaskManager.lua (120) : runLambda
  dataS/scripts/misc/AsyncTaskManager.lua (146) : runTopTask
  dataS/scripts/main.lua (1162) : update
2022-09-10 16:51 Error: appendedFunction 'newFunc' cannot be nil
2022-09-10 16:51 LUA call stack:
  =C:/Users/Flo/Documents/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/scripts/Utility.lua (54) : printCallstack
  =C:/Users/Flo/Documents/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/betterContracts.lua (200) : appendedFunction
  =[C] (4294967295)
  =C:/Users/Flo/Documents/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/scripts/RoyalMod.lua (234) : xpcall
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/gui/MPLoadingScreen.lua (778) : validateTypes
  dataS/scripts/misc/AsyncTaskManager.lua (41) : lambda
  dataS/scripts/misc/AsyncTaskManager.lua (120) : runLambda
  dataS/scripts/misc/AsyncTaskManager.lua (146) : runTopTask
  dataS/scripts/main.lua (1162) : update
2022-09-10 16:51 Error: overwrittenFunction 'newFunc' cannot be nil
2022-09-10 16:51 LUA call stack:
  =C:/Users/Flo/Documents/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/scripts/Utility.lua (21) : printCallstack
  =C:/Users/Flo/Documents/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/betterContracts.lua (201) : overwrittenFunction
  =[C] (4294967295)
  =C:/Users/Flo/Documents/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/scripts/RoyalMod.lua (234) : xpcall
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/gui/MPLoadingScreen.lua (778) : validateTypes
  dataS/scripts/misc/AsyncTaskManager.lua (41) : lambda
  dataS/scripts/misc/AsyncTaskManager.lua (120) : runLambda
  dataS/scripts/misc/AsyncTaskManager.lua (146) : runTopTask
  dataS/scripts/main.lua (1162) : update
2022-09-10 16:51 Error: overwrittenFunction 'newFunc' cannot be nil
2022-09-10 16:51 LUA call stack:
  =C:/Users/Flo/Documents/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/scripts/Utility.lua (21) : printCallstack
  =C:/Users/Flo/Documents/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/betterContracts.lua (202) : overwrittenFunction
  =[C] (4294967295)
  =C:/Users/Flo/Documents/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/scripts/RoyalMod.lua (234) : xpcall
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/gui/MPLoadingScreen.lua (778) : validateTypes
  dataS/scripts/misc/AsyncTaskManager.lua (41) : lambda
  dataS/scripts/misc/AsyncTaskManager.lua (120) : runLambda
  dataS/scripts/misc/AsyncTaskManager.lua (146) : runTopTask
  dataS/scripts/main.lua (1162) : update
2022-09-10 16:51 Error: appendedFunction 'newFunc' cannot be nil
2022-09-10 16:51 LUA call stack:
  =C:/Users/Flo/Documents/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/scripts/Utility.lua (54) : printCallstack
  =C:/Users/Flo/Documents/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/betterContracts.lua (203) : appendedFunction
  =[C] (4294967295)
  =C:/Users/Flo/Documents/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/scripts/RoyalMod.lua (234) : xpcall
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/gui/MPLoadingScreen.lua (778) : validateTypes
  dataS/scripts/misc/AsyncTaskManager.lua (41) : lambda
  dataS/scripts/misc/AsyncTaskManager.lua (120) : runLambda
  dataS/scripts/misc/AsyncTaskManager.lua (146) : runTopTask
  dataS/scripts/main.lua (1162) : update
2022-09-10 16:51 Error: appendedFunction 'newFunc' cannot be nil
2022-09-10 16:51 LUA call stack:
  =C:/Users/Flo/Documents/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/scripts/Utility.lua (54) : printCallstack
  =C:/Users/Flo/Documents/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/betterContracts.lua (204) : appendedFunction
  =[C] (4294967295)
  =C:/Users/Flo/Documents/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/scripts/RoyalMod.lua (234) : xpcall
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (460) : oldFunc
  dataS/scripts/utils/Utils.lua (472) : oldFunc
  dataS/scripts/gui/MPLoadingScreen.lua (778) : validateTypes
  dataS/scripts/misc/AsyncTaskManager.lua (41) : lambda
  dataS/scripts/misc/AsyncTaskManager.lua (120) : runLambda
  dataS/scripts/misc/AsyncTaskManager.lua (146) : runTopTask
  dataS/scripts/main.lua (1162) : update

> 2022-09-10 16:51 Error: overwrittenFunction 'newFunc' cannot be nil
2022-09-10 16:51 LUA call stack:
  =C:/Users/Flo/Documents/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/scripts/Utility.lua (21) : printCallstack
  =C:/Users/Flo/Documents/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/betterContracts.lua (245) : overwrittenFunction
  =[C] (4294967295)
  =C:/Users/Flo/Documents/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/scripts/RoyalMod.lua (263) : xpcall
  dataS/scripts/menu.lua (33) : setMissionInfo
  dataS/scripts/misc/AsyncTaskManager.lua (41) : lambda
  dataS/scripts/misc/AsyncTaskManager.lua (120) : runLambda
  dataS/scripts/misc/AsyncTaskManager.lua (146) : runTopTask
  dataS/scripts/main.lua (1162) : update
2022-09-10 16:51 Error: overwrittenFunction 'newFunc' cannot be nil
2022-09-10 16:51 LUA call stack:
  =C:/Users/Flo/Documents/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/scripts/Utility.lua (21) : printCallstack
  =C:/Users/Flo/Documents/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/betterContracts.lua (246) : overwrittenFunction
  =[C] (4294967295)
  =C:/Users/Flo/Documents/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/scripts/RoyalMod.lua (263) : xpcall
  dataS/scripts/menu.lua (33) : setMissionInfo
  dataS/scripts/misc/AsyncTaskManager.lua (41) : lambda
  dataS/scripts/misc/AsyncTaskManager.lua (120) : runLambda
  dataS/scripts/misc/AsyncTaskManager.lua (146) : runTopTask
  dataS/scripts/main.lua (1162) : update

> 2022-09-10 16:51   Error: RoyalMod caught error from FS22_BetterContracts (1.2.4.1)
2022-09-10 16:51   Error: C:/Users/Flo/Documents/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/betterContracts.lua:292: attempt to call method 'loadGUI' (a nil value)

**Comment by Gecko774** [comment]
Seit 
dem Update oder Commit von 17.13 Uhr läuft es wieder.

Das ging aber fix

**Comment by Mmtrx** [comment]
Ja, war beim vorletzten upload etwas zu hastig😬
