### ISSUE TITLE
Frage zum LazyNPC Modus 

### ISSUE THREAD

**Issue by MeRida2104** [Mmtrx/FS22_BetterContracts#35]
Hi,

Du hast in deiner neusten Version folgendes Changelog geschrieben:

"lazyNPCs" (leave more work for contracts) can be configured on/off

Verstehe ich es richtig, dass in ModSettings/FS22_BetterContracts der Parameter lazyNPC="true" sein muss, damit deine Änderungen aus dem Mod aktiv werden? 
Wenn er auf false steht, ist der Giants Standard aktiv? 

Beste Grüße 
MeRida

**Comment by Mmtrx** [comment]
Moin,
hast du genau richtig verstanden! 
Wenn lazyNPC="false", werden natürlich auch die anderen Schalter `harvest="true" plowCultivate="true" ...` ignoriert.
