### ISSUE TITLE
Wrong Mission Vehicles

### ISSUE THREAD

**Issue by Cassy-Blair** [Mmtrx/FS22_BetterContracts#37]
The new Modhub version of Better Contracts selects the wrong mission vehicles to borrow
![fsScreen_2022_10_02_01_45_50](https://user-images.githubusercontent.com/87262647/193432213-17bb8b03-8d91-4726-9614-a8446537e0df.png)
![fsScreen_2022_10_02_01_45_36](https://user-images.githubusercontent.com/87262647/193432216-be7d91ed-b47e-49d7-8466-a7430a57635d.png)
![fsScreen_2022_10_02_01_45_45](https://user-images.githubusercontent.com/87262647/193432218-684d9d09-a79e-4d64-bd08-3f6079820a71.png)
![fsScreen_2022_10_02_01_45_48](https://user-images.githubusercontent.com/87262647/193432219-ca90fa8d-95bb-4a18-a121-64d13978f36f.png)

**Comment by Cassy-Blair** [comment]
I think I found the bug when I install the Better Contracts v1.2.4.2 directly from the Giants Modhub then I have the wrong vehicles for the missions. On the other hand, if I install v1.2.4.2 here from github, then I have the right vehicles

**Comment by Cassy-Blair** [comment]
Ich hatte davor noch die Version 1.2.3.1 und dann aus dem Modhub auf die neue Version aktuallisiert

**Comment by Mmtrx** [comment]
Falls das nochmal auftritt: die Datei `missions.xml` aus dem savegame Ordner löschen, dann werden alle Aufträge (und damit auch die Fzg-Kombos) vom Spiel neu generiert.

**Comment by Mmtrx** [comment]
Tritt wohl nicht mehr auf, oder?

**Comment by Cassy-Blair** [comment]
> Tritt wohl nicht mehr auf, oder?

Nein da ich ja nun die Github Version nutze. Ob die Version im Ingame Modhub von Giants noch Fehler macht, hab ich nun nicht mehr getestet
