### ISSUE TITLE
Mod conflicts with newly released Lime and Rolling missions

### ISSUE THREAD

**Issue by JukeStuff** [Mmtrx/FS22_BetterContracts#41]
![image](https://user-images.githubusercontent.com/113805245/196780990-b2bb2aa8-39c6-4389-8630-1d452263b9ba.png)
![image](https://user-images.githubusercontent.com/113805245/196782665-d1cf37c3-d509-43cd-a3b4-6dbcd51695d8.png)

**Comment by Mmtrx** [comment]
You could try the rel 1.2.4.4 here, that handles roller and lime missions. 
IBC fix mod compatibility I will implement asap.

**Comment by Mmtrx** [comment]
fixed in [1.2.4.4](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.4.4)
