### ISSUE TITLE
Mod conflicts with newly released IBC Tank Fix

### ISSUE THREAD

**Issue by Cassy-Blair** [Mmtrx/FS22_BetterContracts#42]
Better Contract is causing issues with the new IBC Tank Fix Mod

> 2022-10-19 20:06   Error: RoyalMod caught error from FS22_BetterContracts (1.2.4.2)
> 2022-10-19 20:06   Error: I:/LS22/FS22_Gnadenthal/FS22_BetterContracts/betterContracts.lua:274: attempt to index field 'data/objects/pallets/liquidtank/fertilizertank.xml' (a nil value)
> 2022-10-19 21:05 Error: Running LUA method 'update'.
> I:/LS22/FS22_Gnadenthal/FS22_BetterContracts/scripts/gui.lua:234: attempt to index field 'filterState' (a nil value)
> 2022-10-19 21:05 Error: Running LUA method 'update'.
> I:/LS22/FS22_Gnadenthal/FS22_BetterContracts/scripts/gui.lua:234: attempt to index field 'filterState' (a nil value)

![fsScreen_2022_10_19_21_06_49](https://user-images.githubusercontent.com/87262647/196789838-4ae91f2f-8d9a-4790-9355-88f50eb161fb.png)

**Comment by Mmtrx** [comment]
Ok,
seh ich mir morgen gleich an😉

**Comment by Mmtrx** [comment]
fixed in [1.2.4.4](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.4.4)

**Comment by Cassy-Blair** [comment]
> fixed in [1.2.4.4](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.4.4)

Danke, lag wohl vermutlich daran, daß der IBC Tank Fix die Vanilla IBC Tanks aus dem Shop entfernt und durch die neuen ersetzt werden. Laut BlueDragon ist es Absicht, daß die Vanilla IBC Tanks aus dem Spiel entfernt werden durch den Fix, damit man nicht ausversehen die flaschen IBC Tanks im Shop kauft, welche man nicht in Produktionen und Silos entladen kann
