### ISSUE TITLE
Error Lua 78

### ISSUE THREAD

**Issue by Demolder** [Mmtrx/FS22_BetterContracts#45]
![20221020174138_1](https://user-images.githubusercontent.com/47314044/196995604-0b506dc1-7191-4eeb-acae-cca67d983de9.jpg)

is there a fix for this ??

**Comment by Mmtrx** [comment]
Could anyone of you post their log.txt with the error here please? Could be that this is a follow-on error of some previous one (that also should show in the log).

In any case, you could try the [v1.2.4.4](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.4.4) version that I just updated.

**Comment by NovaZeroX** [comment]
I can try the new version when I get home later on or post the the log

**Comment by NovaZeroX** [comment]
Update: it works now, log throws a warning but it's only for a field that doesn't have equipment available. I can work with this. Do you still need my game log?

**Comment by Mmtrx** [comment]
Ok fine. No, I don't need the log then. For the warning, you could check my comments on #46. 
I will close this now.
