### ISSUE TITLE
Lua: attempt to index field 'mtype' (a nil value)

### ISSUE THREAD

**Issue by rohne83** [Mmtrx/FS22_BetterContracts#46]
Only with the latest version 1.2.4.4 I get a severe error resulting the game to hang completely when opening the missions menue:
2022-10-21 14:47 Error: Running LUA method 'update'.
D:/rohne/Documents/My Games/FarmingSimulator2022/pdlc/FS22_BetterContracts/scripts/userint.lua:176: attempt to index field 'mtype' (a nil value)

![fsScreen_2022_10_21_14_47_12](https://user-images.githubusercontent.com/71030138/197200133-4e3be5b9-3888-4346-8f53-f65a88575c3f.png)

I had several harvest and one fertilizer missions still open when saving the game. Problem is not related to the Warning about the vehicles. Could resolve that one by simply changing the vehicle group id in savegame's missions.xml to a lower value, as I am using my own equipment for that field anyway - but the error remains.
When going back to version 1.2.4.3 the error disappears.

[log.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/9839098/log.txt)

**Comment by rohne83** [comment]
bemerkenswert zudem, dass laut missions.xml überhaupt kein Auftrag für Feld 14 existiert, anders als die zerschossene Anzeige im Screenshot suggeriert

**Comment by ddierki** [comment]
Bei mir der gleiche Fehler,

**Comment by Narcal** [comment]
Same issue here. 
[log.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/9840336/log.txt)
![20221021171757_1](https://user-images.githubusercontent.com/116371229/197230700-959c6cc1-ecd8-4182-af8b-3580968d9a13.jpg)

**Comment by Mmtrx** [comment]
Sorry, I apparently didn't test this thoroughly enough. 
I just repaired [v1.2.4.4](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.4.4), so please download again..

**Comment by 60erjonny** [comment]
![Screenshot (40)](https://user-images.githubusercontent.com/63659182/197253026-bc2178be-9006-41d7-8676-8763813019ca.png)
[log.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/9841095/log.txt)
Fehler immer noch vorhanden...

**Comment by MeRida2104** [comment]
> Sorry, I apparently didn't test this thoroughly enough. 
> I just repaired [v1.2.4.4](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.4.4), so please download again..

Warum änderst du bereits veröffentlichte Releases, ohne eine neue Version zu erstellen? Das machts schwer immer die aktuellste Version deines Mods im Blick zu haben. Schöner wäre es, wenn du nicht die zip tauscht, sondern einen neue Release Version anlegst.

**Comment by Mmtrx** [comment]
@MeRida2104,
hast recht. Sollte gestern schnell gehen und wird die Ausnahme bleiben 😉.

@60erjonny,
das ist noch ein kleiner Konflikt zwischen den Mods DynamicMissionVehicles und LimeMission. Abhilfe:
in der xml Datei `FS22_LimeMission.zip\missionVehicles\limeMissions.xml` eine Zeile `<variants/>` einfügen:
```
<missionVehicles overwrite="false">
	<variants/>
	 
	<mission type="lime">
```

**Comment by criss20ster** [comment]
And version 1.2.4.2  i Have error log this 

Error: RoyalMod caught error from FS22_BetterContracts (1.2.4.2)
Error: E:/ModyFS22/FS22_BetterContracts/betterContracts.lua:274: attempt to index field 'data/objects/pallets/liquidtank/fertilizertank.xml' (a nil value)

And game in menu :
Error: Running LUA method 'mouseEvent'.
E:/ModyFS22/FS22_BetterContracts/scripts/gui.lua:78: attempt to index local 'inGameMenu' (a nil value)

**Comment by Mmtrx** [comment]
@criss20ster,
please download [Rel 1.2.4.4](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.4.4). That fixes incompat with mod FS22_IBCtankfix.

**Comment by criss20ster** [comment]
> 

Ok thx
