### ISSUE TITLE
Lua: attempt to compare nil with string causing hang during map loading

### ISSUE THREAD

**Issue by OniKoneko** [Mmtrx/FS22_BetterContracts#47]
The mod throws the following when attempting to load a map. It freezes at about 60% and the error is present in the logfiles. Removing just Better Contracts solves the issue.

I'm not sure how to best report it so here's the relevant logfile segment.

`2022-10-21 11:47   Error: RoyalMod caught error from FS22_BetterContracts (1.2.4.2)
2022-10-21 11:47   Error: C:/users/steamuser/Documents/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/betterContracts.lua:342: attempt to compare nil with string
2022-10-21 11:47 Error: Running LUA method 'loadSharedI3DFileFinished'.
C:/users/steamuser/Documents/My Games/FarmingSimulator2022/mods/FS22_BetterContracts/scripts/missionVehicles.lua:58: attempt to index a nil value`

**Comment by Mmtrx** [comment]
Please try again with the [latest version](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.4.4).
If error persists, please attach your complete log.txt

**Comment by OniKoneko** [comment]
Looks like the new version fixed the issue I was having as well! I really love working from $0 and your mod is a huge part of that. Thanks for the hard work and the awesome mods.
