### ISSUE TITLE
ERROR lua:78 with Patch 1.8

### ISSUE THREAD

**Issue by mrPassion78** [Mmtrx/FS22_BetterContracts#50]
Hi there , i have notised and lua error with the latest patch..:
2022-10-26 20:23 Error: Running LUA method 'mouseEvent'.
C:/Users/pasca/Documents/My Games/FarmingSimulator2022/mods/GAMEPLAY FS22/FS22_BetterContracts/scripts/gui.lua:78: attempt to index local 'inGameMenu' (a nil value)

I`ll hang the log on here to.. 
Wopster had the same thing, at least a LUA error sins the patch. he updated his mod on modhub today.

Thnx for the awesome mod, and hope you can fix it when you have spare time. 
[log.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/9872736/log.txt)

**Comment by Mmtrx** [comment]
Hi,
that was probably corrected already, see #46 . Please download [Rel 1.2.2.4](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.4.4) again. I updated that Rel without changing the version number. Sorry, should not happen again..

**Comment by mrPassion78** [comment]
no problem :D.. do not worry, i`m happy that you created this, and shared it with the world.. 
And my fould that i did not check the closed issues, before reporting. 
Again, thnx a lot for all the work.
