### ISSUE TITLE
Better Contracts - WilsonTrailer

### ISSUE THREAD

**Issue by Marko230** [Mmtrx/FS22_BetterContracts#51]
hallo , ich habe das Problem das es bei mir eine Warnung mit dem WilsonTrailer gibt. Fs22_BetterContracts v1.2.4.4

![Better](https://user-images.githubusercontent.com/51233639/198302574-0b3cd346-41b1-4e97-bbb4-06b06807d2e7.png)
[log.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/9880065/log.txt)

**Comment by Marko230** [comment]
[log.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/9880054/log.txt)

**Comment by Mmtrx** [comment]
Hi,
kannst du aus dem savegame Ordner noch mal die` missions.xml` hier hochladen? Kann sein, dass mein mod den "Zwiebelernter" nicht kennt.
Ist allerdings nur ne Warnung, dass er für die Zwiebelernte-MIssion auf Feld 55 kein passendes Leih-Equipment gefunden hat. Die Mission kannst du trotzdem machen (mit eigenem Gerät).

**Comment by Marko230** [comment]
[missions1.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/9881280/missions1.txt)

**Comment by Mmtrx** [comment]
Ja, liegt aber nicht am Wilson Trailer. Der ist nur das letzte Fzg der für diese Mission geplanten Leihgeräte-Gruppe. `(getFromVehicle() could not find appropriate vehicle in mission 1472. Last vehicle: TRAILERS wilsonTrailer/pacesetter/pacesetter.xml)`

Vorher kommt wahrscheinlich ein Rübenernter, der auch Zwiebeln kann. Das versteht mein mod noch nicht so ganz. Weißt du. ob die FS22_NF_Marsch_4fach_oG eine eigene missionVehicles.xml hat? Wenn ja, müsst ich da mal reingucken.

**Comment by Marko230** [comment]
Nein soweit ich gesehen hab hat sie keine mission xml

**Comment by AK-Baldow** [comment]
Hi,
spiele auf der MountenHill2022_V5
dort habe ich auch fehler mit einem anhänger "module4"
diese Map hat seine eigene missionVehicles.xml
auch bei normalen Baumwollmissis meckert er über den Trailer. Die Erntemaschine holt er aus der Map_missi

[missionVehicles.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/9895156/missionVehicles.txt)

**Comment by Mmtrx** [comment]
Hi,
MountainHill2022_V5 sollte keine Warnungen mehr bringen. FS22_NF_Marsch_4fach_oG wahrscheinlich auch nicht. Bitte mal die neue Version [1.2.5.0beta](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.5.0beta) testen.

**Comment by AK-Baldow** [comment]
Hi,
Also auf der MountenHill2022_V5 kommen keine Warnings mehr. Perfekt.

Dankeschön

**Comment by Marko230** [comment]
hi, warnings hab ich auch keine mehr auf der NFMarsch. Vielen Dank :)

kann jetzt dann gern geschlossen werden
