### ISSUE TITLE
Probleme mit Multifruit auf der DonDiego

### ISSUE THREAD

**Issue by Cassy-Blair** [Mmtrx/FS22_BetterContracts#53]
Hy anscheinend hat Better Contracts Probleme mit manchen Aufträgen (Mapeigne Fahrzeuge sind eigentlich vorhanden bzw für die Vanilla Geräte eingetragen)  auf der Dondiego Map v1.1, wäre toll wenn man das vielleicht fixen könnte. Log hänge ich an
[log.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/9894516/log.txt)

**Comment by Mmtrx** [comment]
Hi,
das Problem (Ernte-/ Säh-Missionen ohne Leihfahrzeuge) tritt auch ohne BetterContracts auf:
![fsScreen_2022_10_30_18_04_34](https://user-images.githubusercontent.com/86842734/198891638-628b390d-7da2-4691-ba02-b0bc68749cb3.png)
Damit die in der map enthaltenen Mod-Fahrzeuge angeboten werden, müsste man eine erweiterte `missionVehicles.xml` in die map einbauen. U.a. im mod [Dynamic Mission Vehicles](https://github.com/tn4799/DynamicMissionVehicles) könntest du (oder die Mapper) nachsehen, wie das geht.

Dank deiner Log hab ich aber das Warnverhalten meines mods verbessert: Die Meldungen kommen jetzt nur noch einmal pro Mission.

**Comment by Cassy-Blair** [comment]
Könnte man die Warnungen zu den fehlenden Missionsfahrzeugen nicht sogar ganz abschalten?

**Comment by Mmtrx** [comment]
Würde ich gern drin lassen. Denn eine Feldmission ohne angebotene Leihfahrzeuge ist im Grundspiel nicht vorgesehen, also eigentlich eine Fehler-Situation.

**Comment by Cassy-Blair** [comment]
Was mir etwas unklar ist, ist warum ich Warnings bekomme und mir keine Missionsfahrzeuge bei Hopfen (HOPS) angezeigt werden mit Better Contracts, obwohl diese in der ,aps_fruitTypes.xml definiert sind 

        <fruitTypeCategory name="MAIZEHEADER" >MAIZE SUNFLOWER **HOPS**</fruitTypeCategory>
        <fruitTypeCategory name="SOWINGMACHINE" >WHEAT BARLEY OAT CANOLA SOYBEAN SORGHUM OILSEEDRADISH GRASS ALFALFA CARROT LAVENDER ONION **HOPS** POPPY REDCABBAGE WHITECABBAGE RYE CLOVER</fruitTypeCategory>
