### ISSUE TITLE
Active contract no Showing

### ISSUE THREAD

**Issue by yann-mrt** [Mmtrx/FS22_BetterContracts#54]
Good day to all,

Not sure what happen but after updating to the version 1.8.0.0 i don't see any more the active contract on the contract screen but still appear on the progression bar.
As well every time i restart the game, no one contract appear until I double click on one of the top tab to selection the category.
<img width="1269" alt="Screenshot 2022-10-30 112601" src="https://user-images.githubusercontent.com/74056604/198876197-8c20e116-f2ce-4124-aa37-5bf3cc9e0bab.png">
<img width="1266" alt="Screenshot 2022-10-30 112710" src="https://user-images.githubusercontent.com/74056604/198876198-6902a4c3-e1ab-4b3e-98f9-3a40f752036f.png">
[log.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/9895690/log.txt)

Thanks

**Comment by Mmtrx** [comment]
`FS22_BetterContracts/scripts/userint.lua:269: attempt to perform arithmetic on local 'speed' (a nil value)`
Hm - that definitely should not happen.
Can you try to delete `missions.xml` from the corresponding savegame folder, and start the savegame again?
You could also try the latest Version [1.2.5.0beta](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.5.0beta), although I didn't change anything in that area of the code..

**Comment by yann-mrt** [comment]
I try it to delete mission.xml, all mission was deleted, but vehicle (borrowed) was still on the field. and can't do anything with them.
Then I start a new save game.
Thanks any way
