### ISSUE TITLE
Calculation

### ISSUE THREAD

**Issue by Johanansl** [Mmtrx/FS22_BetterContracts#59]
The to deliver amount of product is to big. The keep amount is -… but showed as 0. I try to modify the script and it shows ok now but now I need to deliver in to -… where do I need to change the amount to deliver?

**Comment by Johanansl** [comment]
Exaplme: missions.xml shows expectedliters 22.500, Depositedliters 0, the mod says to keep 0 and to deliver 23.200. The script says (m.expectedLiters *(1 - HarvestMission.SUCCESS_FACTOR)) when I make this line (m.expectedLiters/5) it shows ok in the menu but I can’t find the right script line to take the transportation with it so the to deliver amount says 0 at some point but thecontract is not done can you tell me which line I need to change?

**Comment by Mmtrx** [comment]
Moin,
Hört sich so an, als ob du deutsch sprichst. Vielen Dank für den Hinweis, vielleicht hat sich mit Giants Version 1.8.1 da etwas geändert, muss ich mir nachher gleich ansehen🤓

**Comment by Johanansl** [comment]
Meine Deutsch ist nicht so gut…. Welcher script file hatte das berechnung? Ich liebe das um selbst zu andern. Und who von kommst das harvestmission.succesfactor?

**Comment by Mmtrx** [comment]
First I need to understand:
- what version of game (1.8.1?) and mod (1.2.5.0beta ?) are you using?
- does the error (keep amount shows as 0) occur on a std map, without any changes to the mod script?

I have used the Giants debugger [Giants debugger](https://gdn.giants-software.com/download.php?downloadId=104) to find out how the game calculates the minimum amount to deliver on harvest missions. 
In the current version that is 93% of `expectedLiters` as shown in the missions.xml savegame file.

**Comment by Mmtrx** [comment]
Can this still be reproduced?

You could try the latest version [v1.2.6.1](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.6.1) here.

**Comment by Mmtrx** [comment]
... expired 😉

**Comment by Johanansl** [comment]
Yes we will try this but the version you mention is not available until now, in the main time we deleted your mod and do it without, but!!! Now we can not complete normal contracts also. So now I don’t know if it is your mod or FS22 who isn’t correct.

**Comment by Johanansl** [comment]
Can I reopen this or need to start new issue? We have installed version 1.2.6.3 and still have problems. Almost 4000Litre short on contract. Field is 100% done, everything delivered. 
![Uploading 38BEA26B-8DAA-4956-9313-AC1F5EBF2013.jpeg…]()

**Comment by Johanansl** [comment]
![9EDE2211-EA11-4413-B69A-4485F9ACF5DD](https://user-images.githubusercontent.com/117602728/212196262-19c40bc2-b87c-4ebb-89e3-0897e5d774e2.jpeg)

**Comment by Johanansl** [comment]
![Uploading 96723D60-803F-4273-81F1-E76CAFCF0263.jpeg…]()

**Comment by Mmtrx** [comment]
I will try to help. 
Can you activate Debug, save and restart (so that Debug is on when mod initializes),
then enter „bcprint“ on console. And upload the log here please.

**Comment by Mmtrx** [comment]
It could also be a sloppy field definition on the Back Roads County map. You can verify that when trying to harvest with BetterContracts disabled.
See also: [Giants Forum](https://forum.giants-software.com/viewtopic.php?f=963&t=194158&hilit=harvest+large+fields&start=30)

**Comment by Johanansl** [comment]
Yes I think this is also the problem, when we do contracts “normal” it can be completed but not much left. Can you add a future in the menu where you can choose how much percentage needs to be delivered and how much you can keep, Then we can set it low and all problems will be over on every map.

**Comment by Johanansl** [comment]
I still need to log, but because we play on server it is not always possible to restart and log. But if still necessary we can do it one time!

**Comment by Mmtrx** [comment]
No, log not needed any more. I will think about your suggestion to make the % to keep on harvest a parameter you can set. 
Meanwhile, you could try this little mod that reduces the amount to deliver from harvest from 93% to 85%: [Mission Completition Fix (modhub.us)](https://www.modhub.us/farming-simulator-22-mods/mission-completition-fix-v1000)

**Comment by judg393** [comment]
So I'm using the latest GitHub version 1.2.6.5 and running into problems with this on the oaks I'm missing 1000s of litres in some case :/ maybe still an issue (tried to turn down percentage but even at 85% still not enough crop)

**Comment by Mmtrx** [comment]
Hi @judg393,
what field / crop was that? I just downloaded The Oaks map, and will try to reproduce the error.

**Comment by judg393** [comment]
All crops I tried had an issue. canola oat and wheat I remember field 3 field  is the only no I remember. I can tell you that rolling back to MH release (2.6.2 I believe) fixed it. I posted on my suggestion too sorry! 

Cheers R

**Comment by judg393** [comment]
So I've just checked my github folder apparently I was running 2.6.5 did you fix something with 2.6.7 :/ it may be my fault

**Comment by judg393** [comment]
Although it's weird I definitely got the option to adjust the values in the screenshot. I'll keep testing 1.2.7 :D

**Comment by Johanansl** [comment]
For us the problem was still there on the first better contracts contract with the extra mod for 85%. But!! It was raining and I think that was the case. 

After that we did 2 contracts sunflowers and that was ok. But not much over. Still hard work for a very little bit to keep. 

I’m wondering what happens when you set the game or contracts difficulty higher… and I’m asking myself, why can a contract not be done when it is raining? 

But I found an other “issue”. I was busy (finished but still open because of hay) with a contract and stopped gaming, the next time I came on the farm the contract was gone and I don’t know if we received the money. Only thing what maybe has caused this is that server was restarted due to lost connection whit FS. Other contracts who where accepted but not started where still open.

**Comment by Mmtrx** [comment]
Harvesting grain while it's raining is not a good idea, because the yield decreases (own fields as well as contract fields). In earlier versions (FS17, FS19) a combine would not even move/ harvest during rain. Helpers will also stop harvesting in rain. So: 
`Do Not Harvest During Rain!`

Your other issue seems to be a known Giants problem: Finished but not dismissed (reward paid) contracts do not survive a server restart, sometimes not even a client logout / logon. So: 
`Cash in all your complete contracts before you leave he server!`

**Comment by Mmtrx** [comment]
Hm, I just tested a harvest mission on The Oaks field 3. Worked fine. But I found following:

When the game generates a harvest mission, it takes into account the current field status (limed, fertilized, weed) to estimate the expected yield. (You can see that number also with the Additional Field Info mod, when standing on the field.)
Now you accept that mission, and if nothing changes in the meantime, you will get the expected yield (93% you deliver t othe contracts destination, 7% you keep).

But what could change the field yield status over time? Lime/ Fertilizer - no, a field doesn't loose its lime/ fertilizer unless you harvest it. Weed - absolutely! If you wait long enough (say until next day), weed will grow to next state (small, medium, large), and that decreases your fields yield by approx 5%, 7%, 10% (small, med, large weed).

So, with medium weed you are at the brink, with large you will not get enough from the field to fulfill the contract.

**Comment by Mmtrx** [comment]
Will close, since no new errors reported since @judg393 s remarks on #94
