### ISSUE TITLE
Fails to load new save game

### ISSUE THREAD

**Issue by goldenshoes** [Mmtrx/FS22_BetterContracts#60]
Seems that better contracts mod fails to load new save game.

2022-11-07 18:21 Error: Running LUA method 'update'.
C:/Users/Antanas/Desktop/mods/FS22_BetterContracts/scripts/options.lua:263: attempt to index local 'farm' (a nil value)
2022-11-07 18:21   Error: Failed to find farmland in center of field '1'
2022-11-07 18:21   Error: Failed to find farmland in center of field '2'

Attaching log file, if nobody gets this issue that my be on me.
[log.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/9953559/log.txt)

**Comment by Mmtrx** [comment]
Hi,
hm - I cannot reproduce that on a standard map. The other errors (`Failed to find farmland`) indicate that there maybe s.th. wrong with the maps farmland.xml.

**Comment by goldenshoes** [comment]
I tried starting new save game in mod map first then in standard ingame map and both went up to 85% and stopped with same error in log. Log file I attached is from starting new save game with standard map

**Comment by Iwan1803** [comment]
In the log there are a lot of mods listed. There is also an error for Pumps and Hoses DLC listed...
Please move all mods out of the mods folder and then try again.

**Comment by goldenshoes** [comment]
[log.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/9998623/log.txt)

Deleted pumps and hoses and put only Better contract in. Same outcome sadly

**Comment by Mmtrx** [comment]
Hi,
just updated `options.lua`. Can you try this hotfix please?
[FS22_BetterContracts.zip](https://github.com/Mmtrx/FS22_BetterContracts/files/10020296/FS22_BetterContracts.zip)

**Comment by goldenshoes** [comment]
[log.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/10020507/log.txt)

Fresh save game loaded up fine, thanks. Added log file anyway

**Comment by Mmtrx** [comment]
Cool, can be closed then.
