### ISSUE TITLE
Mod needs update for new contract types

### ISSUE THREAD

**Issue by Timmeey86** [Mmtrx/FS22_BetterContracts#61]
To no surprise, GIANTS broke your mod by adding new contract types ;-)

This only affects maps where you can get those contract types which is probably only the new one.

After generating a couple of new contracts for a bit (does not always happen on first attempt) you'll get this:

![grafik](https://user-images.githubusercontent.com/10223149/202004449-b30d9d28-585a-40ab-8362-22bfa5ce461f.png)

If you don't own the DLC, I can maybe assist you

**Comment by Mmtrx** [comment]
Hm - I thought I had taken care of that. (Because Giants were so kind to alert me 3 months ago about new contract types :)
- Is that mod version 1.2.5.0beta you are using? Because line 509 of `betterContracts.lua` in that version is `self.missionUpdTimer = self.missionUpdTimer + dt`, so no compare.
- Can you upload the log.txt pls?

Thx for the offer with the DLC, I'm just downloading it..

**Comment by Timmeey86** [comment]
I'm using the current version from the official mod hub (1.2.4.4), therefore it's this passage:

`function BetterContracts:addMission(m)
	-- add mission m to the corresponding BetterContracts list
	local cont = {}
	local dim, wid, hei, dura, wwidth, speed, vtype, vname, vfound
	local cat = self.typeToCat[m.type.typeId]
	local rew = m:getReward()
// ->if cat < SC.TRANSP then`

**Comment by Timmeey86** [comment]
Log didn't contain anything interesting so I added some more:

![grafik](https://user-images.githubusercontent.com/10223149/202273289-4950df1d-a30f-4bb2-a4bf-d9fa6c91707c.png)

**Comment by JukeStuff** [comment]
it gave me the same error and didn't show contracts, turned off BetterContracts and it works normally

**Comment by JukeStuff** [comment]
i forgot, i had the Modhub version 1.2.4.4 since the newest one had some issue with Mp don't remember anymore what was it exactly tho

**Comment by Jayshua83** [comment]
Getting this error

2022-11-22 19:19   Warning: [FS22_BetterContracts] ignoring new mission type destructibleRocks (id 12)
2022-11-22 19:19   Warning: [FS22_BetterContracts] ignoring new mission type treeTransport (id 13)

**Comment by Jayshua83** [comment]
> Ok, mission type `destrcutibleRocks` was not contained in my early info from Giants. You can fix this in in modhub version 1.2.4.4 by inserting following in `betterContracts.lua` after `addMapping("lime", SC.SPREAD) -- lime mission`:
> 
> ```
> 	for _, missionType in pairs(g_missionManager.missionTypes) do
> 		if self.typeToCat[missionType.typeId] == nil then
> 			addMapping(missionType.name, SC.OTHER) -- default category for not registered mission types
> 		end
> 	end
> ```
> 
> Since I am just testing and preparing Release v1.2.6.0 (with UI for config params), I will rather not publish another release for this bug.

This fixed my issue for now!

**Comment by MimirDroid** [comment]
Thank you for the fix snippet.  I have been driving myself crazy trying to figure out what was causing this error.  I had even started over my save game thinking it was something I did that caused the save to get corrupted.

**Comment by Mmtrx** [comment]
Is fixed in latest version [v1.2.6.1](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.6.1) here. Modhub submit / testing will still take a while..
