### ISSUE TITLE
PT-BR Translation - Insert

### ISSUE THREAD

**Issue by Myiamoto86** [Mmtrx/FS22_BetterContracts#62]
Dear,

Goodnight.

PT-BR translation follows. I am grateful to be able to contribute.
[l10n_br.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/10017644/l10n_br.txt)
[modDesc.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/10017645/modDesc.txt)

**Comment by Mmtrx** [comment]
Thanks a lot! Will be incorporated in upcoming release 1.2.6.0.

**Comment by Myiamoto86** [comment]
Goodnight.

It has.
