### ISSUE TITLE
For barley?

### ISSUE THREAD

**Issue by vitalii2011** [Mmtrx/FS22_BetterContracts#63]
![fsScreen_2022_11_20_21_56_47](https://user-images.githubusercontent.com/41552153/202920721-e5d0492b-c0a2-45f4-b7be-f5ffcc7cb69a.png)
![fsScreen_2022_11_20_21_57_00](https://user-images.githubusercontent.com/41552153/202920725-006b0a3a-e920-4b31-9931-68ccb633b76f.png)
![fsScreen_2022_11_20_21_59_11](https://user-images.githubusercontent.com/41552153/202920726-e04ead35-17ff-4faf-b52d-8dcf1329eca5.png)

**Comment by Mmtrx** [comment]
This can happen when s.th. changes to the list of possible mission vehicles between saving time  and reloading of a savegame, like
- enable/ disable a contracting mod (BetterContracts, RollerMissions, ContractsPlus, etc)
- enable/ disable a DLC, like platinum (they add new vehicles to missionVehicles.xml)

You can fix such a situation by deleting the missions.xml from the savegame directory.
