### ISSUE TITLE
Issues with discounted land

### ISSUE THREAD

**Issue by judg393** [Mmtrx/FS22_BetterContracts#64]
Hi mate 

I love this mod especailly when it implemented a discount field price for contracts completed :) unfortunately this doesn't seem to work on SilverRun (DLC map) (I must admit i havent tried it on any other map atm)

it seems like the game ignores the  price that is displayed (the reduced price) and still needs the none reduced price to enable purchase unless im doing something wrong of course :)

![20221126101321_1](https://user-images.githubusercontent.com/55981682/204084048-51af45fd-dab0-4b45-974b-06c2650c1470.jpg)
![20221126101315_1](https://user-images.githubusercontent.com/55981682/204084050-3e61c1ad-692c-447e-a3d0-cddb1c3ae0f2.jpg)

**Comment by Mmtrx** [comment]
That‘s a True bug you found!
Happens when discountPrice < your budget < normalPrice. 

Will provide a fix as soon as I‘m back home.

**Comment by judg393** [comment]
At least it's not me! Thanks buddy

**Comment by judg393** [comment]
just seen your update am testing

**Comment by judg393** [comment]
i have no contracts popping up on the Fields now

**Comment by Mmtrx** [comment]
@MarkusTheRed,
discounts are measured/ saved per NPC, not per field. Base is the number of completed jobs for a given NPC farmer. 
Example:
- Farmer A has fields 10, 11, 12. You do 3 jobs for farmer A (could be one on each of his fields, or 3 all on field 10, or any combo). 
- Now your discount for any purchase from A is, say 33% (if discount per field set to 11%).
- When you do buy a field (a farmland) from A, your job count goes down to 0 (more precisely: is decreased by `Number of discount-effective Jobs`). You have just used up your discount from farmer A.

So, if you want to have some discount (i.e. jobs completed) left after a field purchase, you must complete more than `Number of discount-effective Jobs` before the purchase. `Number of discount-effective Jobs` can be changed (last entry on the settings page).

**Comment by Mmtrx** [comment]
..should be fixed with [v1.2.6.2](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.6.2)

**Comment by mechanicFS** [comment]
> ..should be fixed with [v1.2.6.2](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.6.2)

Hello friend! In the new update, the purchase of fields at a discount also does not work.

**Comment by judg393** [comment]
@Mmtrx still not had any field contracts to test this on not sure if my save is borked or it's just only 3 fields and long seasons feel free to close this if you want I can reopen if required 😅

**Comment by SniperKittenCZ** [comment]
Discounted land unfortunatelly does not work in [v1.2.6.2](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.6.2)

**Comment by Mmtrx** [comment]
@SniperKittenCZ,
can you describe your error situation in more detail? Maybe screen shots and log.txt?

**Comment by Melegari** [comment]
Hi, same things happens to me with the new version , the discount is not working 
![Screenshot 2022-12-28 143541](https://user-images.githubusercontent.com/67880202/209828459-7f40a94c-4c31-4715-8f3f-6e39a51fdfae.png)
![Screenshot 2022-12-28 143613](https://user-images.githubusercontent.com/67880202/209828466-19fb08eb-9f92-499b-8317-878a307f4b46.png)

**Comment by Mmtrx** [comment]
Ah - Precision Farming. I need to test compatibility with that dlc.

**Comment by judg393** [comment]
That might be my issue too 😂

**Comment by Mmtrx** [comment]
There was an issue with the mod not intercepting the mouse-click on the Buy-Land button. Is fixed with [v1.2.6.3](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.6.2.3)

**Comment by Mmtrx** [comment]
looks like solved.
