### ISSUE TITLE
Crowdin for translations

### ISSUE THREAD

**Issue by vitalii2011** [Mmtrx/FS22_BetterContracts#65]
Try, for translation files, Crowdin:
https://github.com/CitiesSkylinesMods/TMPE/wiki/Localisation
One of the mod authors whose mods I did translations for:
https://crowdin.com/project/fsg-mod-assistant
Just to show what the modder will have on the site. 
For translators, too, it is very convenient - they receive email messages about added texts for translation.

**Comment by Mmtrx** [comment]
Thanks, I will try that out.

I put all new texts at the end of `l10n_ru.xml`, but probably you didn't work from that file?

**Comment by vitalii2011** [comment]
> Thanks, I will try that out.
> 
> I put all new texts at the end of `l10n_ru.xml`, but probably you didn't work from that file?

Everything is in the places where you placed it. )

**Comment by Mmtrx** [comment]
Thanks, will try Crowdin next time.
