### ISSUE TITLE
[Update] BR Translation

### ISSUE THREAD

**Issue by Myiamoto86** [Mmtrx/FS22_BetterContracts#69]
Dear friend.

Once again I really like your mod.

Here are the BR translation additions.

I'm still checking if my translation is good for my language. If any changes occur, I will send the update file as soon as possible.

Hugs.
[l10n_br.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/10147615/l10n_br.txt)

**Comment by Mmtrx** [comment]
Thank you! Will be in Version 12.6.1.
