### ISSUE TITLE
It is not possible to finish the contract

### ISSUE THREAD

**Issue by ArtV-Nef** [Mmtrx/FS22_BetterContracts#70]
Harvest contracts count strangely. It can not be completed, judging by the menu with the details show that brought all the right amount of corn, but the field is not harvested yet. (grain brought from their own supplies) But the progress of the task at 0%.
![2022-12-05_12-07-20](https://user-images.githubusercontent.com/59769343/205598909-c1dc126f-ae18-45ba-8c5a-96b9760d5d44.jpg)

Better Contract 1.2.6.0
[log.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/10152951/log.txt)

**Comment by Mmtrx** [comment]
To complete a harvest contract you need both:
1. completely harvest the field (shown on the "field complete" value in details section) -->`field completion`
2. deliver the requested amount to the unload station specified -->`delivery completion`

Goal 1 counts as 80%, goal 2 as 20% of total contract completion

**Comment by ArtV-Nef** [comment]
Yes, that's right, the problem is that by fulfilling either condition 1 or condition 2, the total is always 20%. And the column "field completion" is always at 0.0%. As I understand it, the harvesting process is going on, but the delivery is not counted. It is not clear why this happens.

**Comment by Mmtrx** [comment]
Hm, I cannot see any errors related to BetterContracts in your log. Two other mods bring up errors;
- FS22_TrailerJointBlock
- FS22_Volvo_pack

Can you test without these 2?

And do you have a screenshot of a field completely harvested, but nothing delivered yet? Normally, that should show 80% contract completion (with or w/o my mod).

**Comment by ArtV-Nef** [comment]
![image](https://user-images.githubusercontent.com/59769343/205725844-a654af5f-16b7-414b-b2cf-a9bdf0badb2e.png)
![image](https://user-images.githubusercontent.com/59769343/205725979-48d1fd47-f105-4cfb-8169-ccbbab7a14c8.png)
Removed mods with bugs. The problem remains. It's like cleaning is blocked. Hmm, I don't understand.

**Comment by ArtV-Nef** [comment]
![image](https://user-images.githubusercontent.com/59769343/205758648-bb9c51ba-0108-4225-8298-3a5d68079294.png)
![image](https://user-images.githubusercontent.com/59769343/205758798-8002a357-fc90-4aa8-a0f5-07274c59ae19.png)

Corn not work. Others cultures in tests.
![image](https://user-images.githubusercontent.com/59769343/205758969-9c0313e5-0a88-481f-981b-c34558d7b352.png)

I not use maize plus)

**Comment by ArtV-Nef** [comment]
Sunflower not worked
![image](https://user-images.githubusercontent.com/59769343/205943689-dda39c1c-d10b-42d1-86d4-ac7fe9a10f41.png)

**Comment by ArtV-Nef** [comment]
![image](https://user-images.githubusercontent.com/59769343/205948138-5d043ade-7754-4062-8ac7-4103a2dcca89.png)
Yes, I changed the cutterbar to a mod, but a different one - everything worked. Here is a screenshot of the cutterbar with which there were problems.
