### ISSUE TITLE
Probleme mit Platinum DLC und Silverrun Map

### ISSUE THREAD

**Issue by Cassy-Blair** [Mmtrx/FS22_BetterContracts#74]
Sobald ich Better Contracts auf der Silverrun Forrest Map nutze, werden die neuen Baum Missionen und Felsen Missionen nicht mehr angezeigt und wirft LUA Fehler

**Comment by Mmtrx** [comment]
Moin,
welche Version?
Log.txt?

**Comment by Cassy-Blair** [comment]
> Moin, welche Version? Log.txt?

Aktuelle Modhub Version, Log.txt hab ich leider nicht mehr, da ich Better Contracts direkt wieder entfernt hatte, nachdem die neuen Baum und Felsen Missionen Probleme machten

**Comment by Mmtrx** [comment]
Hi,
die modhub Version ist noch nicht Platinum ready. Du kannst entweder 
- die Datei betterContracts.lua selbst fixen:
```
for _, missionType in pairs(g_missionManager.missionTypes) do
	if self.typeToCat[missionType.typeId] == nil then
		addMapping(missionType.name, SC.OTHER) -- default category for not registered mission types
	end
end
```
einfügen nach Zeile
`addMapping("lime", SC.SPREAD) -- lime mission`

oder
- die aktuelle github Version [1.2.6.1](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.6.1) hier runterladen.

Siehe auch #61 Mod needs update for new contract types

**Comment by Mmtrx** [comment]
Funktionierts jetzt auf Silverrun? V1.2.6.2 ist seit Montag auch im modhub.
