### ISSUE TITLE
Clear / New Contracts for everyone

### ISSUE THREAD

**Issue by TasnadiAttila** [Mmtrx/FS22_BetterContracts#75]
Hi,
I just read the description of the mod and it says only the master user can clear and accept new contracts. Is there any way to rewrite it in the scripts somewhere?

**Comment by TasnadiAttila** [comment]
I play in Multiplayer with one of my friends. The server is just the two of us but he is hosting it from his pc. So i can't log in as admin and even if he gives me farm manager i still cant delete the contracts or create new ones. So if there is any option i would be very greatful.

**Comment by TasnadiAttila** [comment]
I installed the 1.6.2.1 from your github and as soon as started the game in the mod install menu it requires an update and if a update it, it goes back to v1.2.4.4. And if I not updating it the mod doesnt shows up in installed mods. I play in hungarian but in the bottom left corner you can see FRISSÍTÉS which means UPDATE.
![2](https://user-images.githubusercontent.com/70896019/207410511-2079ac47-6d5f-40de-9092-7a3ada726a17.png)
![1](https://user-images.githubusercontent.com/70896019/207410518-318b1084-39ef-46dc-bb98-d5bc7b878d71.PNG)

**Comment by Mmtrx** [comment]
Ja, that's kind of a problem with github versions newer than modhub. What you should do is this
- download FS22_BetterContracts.zip (v1.2.6.1) from here to your /mods Folder
- ignore the "update" request from the ingame mod menu (the mod menu doesn't know about github)
- start the game

**Comment by TasnadiAttila** [comment]
Just can't find where can i ignore the update.
If i rename the zip with the new version can it be an update?
![Uploading Névtelen.png…]()

**Comment by goldenshoes** [comment]
Just don't update. Mods still works in the game even when showing available updates...
