### ISSUE TITLE
Probleme mit Silage Aufträge mit Mais Plus

### ISSUE THREAD

**Issue by Sascha2707** [Mmtrx/FS22_BetterContracts#77]
Moin

Ich habe einen Anzeigefehler mit Silage Ballen unter Mais plus. Zuerst wird es mir als Silage Auftrag angezeigt wenn man die 1. Ladung Ballen ablädt wird der Auftrag zu Heu. In der Missions.xml steht aber Silage Auftrag drin sprich grass_fermented also Grassilage. Das Problem besteht aber seit der aktuellen Release. Ich habe mal ein Screenshot aus dem Spiel sowie die Log und die Missions XML in ein Zip gepackt.
[missions.zip](https://github.com/Mmtrx/FS22_BetterContracts/files/10252862/missions.zip)

**Comment by Mmtrx** [comment]
Moin,

liegt vielleicht daran, dass er den neuen filltype GRASS_FERMENTED nicht kennt. Kannst du den screenshot noch mal mit "Details" an machen, und auch vom Original-Auftrag, also Silage? Und auch mal BetterContracts debug anmachen, bitte.

Vielleicht passiert das sogar auch ohne BetterContracts?

PS. v1.2.6.2 ist seit heute auch schon im modhub. Die haben nur einen Tag für Testen und Veröffentlichen gebraucht (weiß noch nicht, ob ich mich darüber jetzt wirklich freuen soll  😏).

**Comment by Sascha2707** [comment]
[aufträge.zip](https://github.com/Mmtrx/FS22_BetterContracts/files/10269538/auftrage.zip)
Also ich hab neues Save gemacht Silage Auftrag ausgewählt. Da Steht Ganzpflanzesilage. Lade ich ein Ballen ab switcht er zu Grassilage um in den Details aber im Auftrag selber zu einem Heu Auftrag. Nun weiss ich nicht ob das ein Problem seitens M+ ist oder an deinem Mod. Ich weiss das es in einer vorderen M+ oder BC Version mal geklappt hat.
Laut M+ Mod muss er Switchen auf Grasssilage das ist richtig aber das er dann im Auftrag Anzeige auf Heu geht das ist komisch. Ich hab mal beide Screenshots also vor dem Ballen abkippen und nach dem mit Details im Zip sowie die Log mit Debug an

**Comment by Mmtrx** [comment]
Falls das noch akut ist - bitte re-open.

**Comment by MeRida2104** [comment]
Wir haben bei uns auf dem Server das gleiche Problem. In https://github.com/Mmtrx/FS22_BetterContracts/issues/109 wurde das Verhalten ja ebenfalls beschrieben. Sprich Text ist Heu-Auftrag, Maschinen sind aber Silage. Frage ist nun, ob das Problem auch ohne MaizePlus auftritt.

**Comment by Timmeey86** [comment]
Wir hatten das Problem bereits, bevor wir BetterContracts aktiviert hatten. MaizePlus war aber aktiv.

**Comment by MeRida2104** [comment]
Ich habe mich dazu im MaizePlus Discord informiert. Das Problem liegt im MaizePlus und wird in den nächsten Tagen per Modupdate behoben!

**Comment by MeRida2104** [comment]
Update ist da

https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=253528&title=fs2022
