### ISSUE TITLE
Would Better Contracts conflict with a Map's Contract Generation?

### ISSUE THREAD

**Issue by cwattyeso** [Mmtrx/FS22_BetterContracts#78]
This is more of a query then an actual bug report or issue. I have recently installed and started a new map on my dedicated server. Map is Maypole Farm from the Giants ModHub. Have currently played through 3 months in game, with 5 day months and the only contracts ever appearing are Baling Contracts for all the Grass Fields. All the other Fields on the Map are just blank dirt and so far I have not seen the AI offer any kind of contract for any of them. I have spoke to the Map Author about this and the only answer he could give me is that the issue is being caused by a mod conflict. I sent him a copy of the server log file so he could see what mods are installed and active on the server and the only two he thinks could be causing an issue are this one and also the start in spring mod. However the start in spring mod was only installed and active when the save was first created so the game could start in March instead of the normal August of the vanilla game. After starting the save, the mod was removed and deleted from the server as the author instructs you to do that as it's not needed after initial start. So only mod still active and in place is Better Contracts.

**Comment by Mmtrx** [comment]
Hi,
which version of the mod are you using? Have you activated the lazyNPC option, and also the sub-options plowCultivate, sow, fertilize?
Maypole uses "Disturbed Simulations UK growth calendar", when is the first month you can sow anything in that calendar?

So it could well be within normal that AI farmers don't offer any fieldwork contracts between March and May. If the situation does not change further down the year, I'd need a log file (client or server) for further analysis.

**Comment by cwattyeso** [comment]
I'm currently using v1.2.6.1 of Better Contracts on the Server. I have the LazyNPC Option enabled but only for Fertilising/Spraying and leaving everything else to the AI, however at the moment the AI is doing nothing.
The Growth Calendar allows for most crops to be sown in March, with a couple only allowed to be sown from April. However Seasonal Growth is turned off on the server, so sowing/harvesting can be done at any stage of of the year ignoring the growth calendar, so again I would expect to see all variety of contracts on offer.
We're in July now as of last night and the only thing that has changed is now the AI has popped up offering a few sowing contracts for fields but weirdly is asking for us to sow "Grass". This made the Map Author very confused who was watching me play last night as he's never seen grass seeding contracts. Also there seems to be 18 fields on the map already designated as GrassMission Fields and they are offering baling contracts all the time, so it seems weird the AI is trying to turn more fields into grass which when checking the map with Giants Editor are not marked as GrassMission allowed.

Interestingly have just created a single player save with the same mods and map, without the start from spring mod activated and game starts in August as Giants Default and instantly all the fields on the map have various crops planted on them, the AI is offering a variety of contracts across the map and strangely this time it seems there are only 5 Baling/Grass Contract fields.

**Comment by Mmtrx** [comment]
Probably an issue with Start-in-Spring mod.
