### ISSUE TITLE
Feature Request: No DLC vehicles

### ISSUE THREAD

**Issue by DisturbedSimulations** [Mmtrx/FS22_BetterContracts#79]
When you select overwrite in the user defined contract vehicles is there a way of getting the game to also ignore PDLC vehicles?  I have a custom set up with old equipment but if I enable a PDLC about half the missions end up using vehicle sets from the base game / PDLC.

**Comment by Mmtrx** [comment]
Yes, I've seen your tut video about the old-timer equipment setup - very nice!

I fixed a quick change (not yet tested) that you could try out: 
[FS22_BetterContracts.zip](https://github.com/Mmtrx/FS22_BetterContracts/files/10262527/FS22_BetterContracts.zip)

If you set debug on, it prints to the log whenever it starts to read a mission vehicles file (vanilla, map, your user defined, dlc,..) It should ignore all other, if you set overwrite="true".

**Comment by DisturbedSimulations** [comment]
Glad you like it,  I'll give this a test today.   Thanks for looking at this

**Comment by DisturbedSimulations** [comment]
No joy, its still pulling in the DLC vehicles.

**Comment by Mmtrx** [comment]
You can now give it another try: [v1.2.6.3](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.6.2.3)

**Comment by DisturbedSimulations** [comment]
Just tested, looks like you've nailed it.  Thanks for adding that feature in
