### ISSUE TITLE
Latest GitHub Version Warning

### ISSUE THREAD

**Issue by Jayshua83** [Mmtrx/FS22_BetterContracts#8]
Warning: Duplicate l10n entry 'SC_sort' in 'C:/Games/Farming Simulator 22 Mods/FS22_BetterContracts/l10n/l10n_en.xml'. Ignoring this definition.

I know this isn't that important but for those of us that like clean logs. :)

Or et me know how to fix it myself if you don't plan too? :) Thanks!

**Comment by Mmtrx** [comment]
just repaired. Was duplicate line in l10n_en.xml. Updated [Realease](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.1.0)

**Comment by afmodding** [comment]
Hi All

I need your help please.
I would like to add custom key binding ( l10n entry to F1 menu) to my mod, (it is vehicle).
There is an audio file (siren sound) in mod's folder, has been added as audio source to mod, named: "wail".
I tried the siren on "cover" function. Everything is working well but in the top left menu (F1) there is "open cover" (N), it is ridiculous :)
Is there any chance rename "open cover" - "close cover" to "Siren ON/OFF"?
Any other idea how to add audio file as siren?
