### ISSUE TITLE
Contracts for plowing do not work

### ISSUE THREAD

**Issue by MishanyaKV** [Mmtrx/FS22_BetterContracts#80]
![20221220133020_1](https://user-images.githubusercontent.com/121101290/208664050-d22dbddd-36a0-4764-8186-dcfbe361f7c1.jpg)
When I rent equipment for plowing a field under a contract, I cannot start plowing it on the field with this equipment. The game says that the equipment is rented for work under a contract, but it was rented specifically for this field. If I come with my plow, then the contract progresses.

- 
![2022-12-20_13-40-28](https://user-images.githubusercontent.com/121101290/208663772-3b0575b6-68a2-455f-991c-3d89f74379b5.png)

**Comment by cwattyeso** [comment]
That's Equipment is a Subsoiler and can not be used for Ploughing Contracts. Only Equipment that is clearly defined and catergorised as a 'Plough' in game can be used for Ploughing Contracts.

**Comment by Mmtrx** [comment]
Which map? 
Does this also happen w/o BetterContracts?

The log warnings also say that BetterContracts can't find a plow offered for the plowing jobs on fields 8, 14, 17.

**Comment by MishanyaKV** [comment]
The map is mod Zarya. So far I can’t say contracts for plowing the fields have not appeared. If there is such an error again, I will definitely inform you.

**Comment by Mmtrx** [comment]
please re-open, if error still persists.
