### ISSUE TITLE
Incompatibilidade com o mod Dynamic Field Prices

### ISSUE THREAD

**Issue by Myiamoto86** [Mmtrx/FS22_BetterContracts#83]
Dear friend,

How are you? Belated Merry Christmas.

I've been doing some testing of mods, mainly on compatibility issues. I noticed that your mod for better contracts is having incompatibility with the Dynamic Field Prices mod. In the logs, both do not show any errors, but in the discount parts for purchasing fields on the PDA, the applied discounts of your mod are not assigned. Obs.: The percentage for the discounts is presented in the PDA, but it is not changed in the value. What is retained is the percentage of the Dynamic Field Prices mod.

It would be great to see that both can be used together.

For this occurrence I am not inserting the log, because I did not detect any error message. If you want, I'll make a test match to send it to you. Remembering that in all tests, I use the mods in the latest versions: (Autodrive), (courseplay), (EasyDevControls), (mobileWorkshop) and (paintAndTerraformAnywhere). If you think that one of these can influence, report it, so that I can remove it from the tests to generate the logs.

Hugs.

**Comment by Mmtrx** [comment]
There was an issue with the mod not intercepting the mouse-click on the Buy-Land button. Is fixed with [v1.2.6.3](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.6.2.3)

**Comment by Mmtrx** [comment]
I assume that fixed.
