### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Slain9178** [Mmtrx/FS22_BetterContracts#85]
Hello, I would like to ask few questions about the mod as I am still sometimes experiencing disappearing contracts.

1. After updating the mod to a version with in-game settings, should I remove FS22_BetterContracts.xml file?
2. I have one save since the game came out. Is a new save from certain version of the mod needed to function properly?
3. When I click on New contracts after harvesting NPC fields, there are contracts available (cultivate, sow, after sowing - fertilize or roll), but when I quit the game and load again after a few days, there are no contracts and jobs are done. Is it necessary to "book them" by accepting?
4. Lazy NPC settings in-game - when Lazy NPC for all types is active, NPCs never harvest their fields, but they sometimes do other types of work (sow, cultivate, fertilize etc.), is that correct?

Thank you in advance and of course thank you for amazing job with the mod.

**Comment by Mmtrx** [comment]
Hi, here some answers

1. yes you can remove it from the modSettings/ folder
2. yes I recommend a fresh savegame, whenever you activate / deactivate the BetterContracts mod. Alternatively, you can delete file `missions.xml` from the relevant savegame directory
3. Hm. normally the game should save the offered contracts as well as the active ones (those you accepted). Be sure to "save game" before you quit. If you just quit a MP server game that keeps running, then ok the offered jobs will be re-evaluated each month and may be deleted. Accepting contracts will keep them for you until you come back to the game.
4. Correct

**Comment by Slain9178** [comment]
Thank you very much!
