### ISSUE TITLE
Vorschlag: Hinzufügen von Saatgut und Dünger bei Mission

### ISSUE THREAD

**Issue by 0scarZulu** [Mmtrx/FS22_BetterContracts#86]
Moin :) 

ich bin sehr angetan von deinem Mod und nutze ihn seit dem ersten Release und freue mich was er für eine klasse Entwicklung nimmt. 

Was mir allerdings fehlt ist die Möglichkeit irgendwie Dünger bzw. Saatgut für die jeweiligen Aufträge zu erhalten. 

ALso zB folgende Szenarien:

1. Saat Mission - ich nehme Auftrag an mit der Option die Geräte auszuleihen. Dann  wäre es schön, wenn entweder Saatgut mit gestellt wird oder der Betrag X bei der Bezahlung addiert wird.

Vielleicht ist das auch über das UI möglich umzusetzen. Eigenes Saatgut und Dünger ja/nein oder so. 

Ich finde es schade das wenn man gerade am Anfang Missionen macht um an Geld zu kommen man meist mehr ausgeben muss für die Fillables und dadurch der Gewinn geschmälert wird. 

Vielleicht findest du ja ein coole Umsetzung bzw. Lösung

Cheers

**Comment by Mmtrx** [comment]
Moin,
Idee kann ich nachvollziehen. Eine Erhöhung der Bezahlung kannst du ja jetzt auch schon machen - über Grundeinstellungen/ Basislohn auf der UI Menuseite.

Wenn dir am Anfang Dünger/ Saatgut zu teuer sind, kann ich folgende Mods empfehlen:
- [Animierte Gebäude](https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=236464&title=fs2022) von ALIENJiM , das Pack enthält eine Verkaufsütte für Saatgut und Dünger.
- [Platzierbare Füllstationen](https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=226137), günstiger und braucht wenig Platz 😉

**Comment by Mmtrx** [comment]
Und hier noch eine Idee: wenn du die angehängte Datei (erst mal auspacken:)  im BetterContracts mod (unzipped) ins Verzeichnis `missionVehicles` kopierst, sollten einige der vom Spiel erzeugten Dünge-, Saat- und Spritz-Aufträge das entsprechende Verbrauchsmaterial mit anbieten.
![fsScreen_2023_01_17_19_24_26](https://user-images.githubusercontent.com/86842734/212980767-9d57d87e-f39b-43bf-8abc-34d1b6e8aec1.png)
[userDefined.zip](https://github.com/Mmtrx/FS22_BetterContracts/files/10438263/userDefined.zip)

**Comment by 0scarZulu** [comment]
Stark :) Danke .. ich werde es testen ..

**Comment by Mmtrx** [comment]
Wenn du einen dieser "Spezialaufträge" annimmst (Geräte ausleihen), gibt es 2 Log-Fehler. Die kann man aber ignorieren. 😉

**Comment by DisturbedSimulations** [comment]
This is an awesome addition.  Thank you :)   
Sorry if this is not the place to respond, but it's a very cool idea and implementation

**Comment by Mmtrx** [comment]
Log errors when using this are fixed in [v1.2.6.5](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.6.5)
