### ISSUE TITLE
Odd Mission Issues

### ISSUE THREAD

**Issue by Jayshua83** [Mmtrx/FS22_BetterContracts#9]
So yesterday I installed the version here on GitHub upgrading the version on my servers and clients from the Modhub version which seemed to be working fine!

We had an odd issue yesterday : We had a completed contract that we were leaving and not turning it in. But it kept disappearing. Like it was getting turned in without any payment... I wasn't seeing any errors in the log.

Now today we completed 2 more contracts and when we went to turn them in we got paid and it took most of the lease equipement but NOT ALL! This time the server did throw an error.

Is this something you've seen before?

```
2022-04-02 14:01 LUA call stack:
  dataS/scripts/vehicles/Vehicle.lua (1268) : printCallstack
  dataS/scripts/BaseMission.lua (1145) : delete
  dataS/scripts/FSBaseMission.lua (1974) : update
  dataS/scripts/missions/mission00.lua (583) : update
  dataS/scripts/main.lua (1381) : update
```

**Comment by Mmtrx** [comment]
Thank you for testing! I could only test this on a small dedi server with just one client.
Do you happen to have the complete (server) log?
Is that a dedi or a full server?
For what type of field mission did that happen?

**Comment by Jayshua83** [comment]
I do not have the complete log anymore. But nothing else in the log was related.

This was a Dedicated Server which was Rented and had 2 Clients connected. I am pretty sure Dedicated is a Full server? :)

This was not a hosted from the MP menu server.

This happened on Harvest Missions. Both of my weird issues.
