### ISSUE TITLE
Fehler Missionen

### ISSUE THREAD

**Issue by Bandesss** [Mmtrx/FS22_BetterContracts#91]
wir können keine 100% bei den Missionen machen
Version
1.2.6.5

[log.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/10466089/log.txt)
Hoffentlich kannst du uns Helfen ?
gruß

**Comment by Mmtrx** [comment]
Moin,
kannst du mal die komplette log.txt hochladen?
Wann tritt der Fehler auf, schon beim Aufruf der Vertragsseite im Menu? Bei Start / Abschluss eines Vertrags?

**Comment by Bandesss** [comment]
Geht leider nicht, weil wir den Mod getauscht haben mit dem modhub.
Ich habe 8 Spieler auf dem Server die wollen zocken.
Die jungs haben nichts verstellt, kam einfach beim Missionen machen, schau bei uns im Discord chat intern, gestern Mittag

**Comment by Bandesss** [comment]
Hallo anbei die Log
[log.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/10520075/log.txt)
Gruß Danke

**Comment by Mmtrx** [comment]
Hat sich wohl erledigt, mach ich hier mal zu.
