### ISSUE TITLE
Feature request; available contracts map markers according to filters

### ISSUE THREAD

**Issue by SnakeManPMC** [Mmtrx/FS22_BetterContracts#93]
Idea; mark AVAILABLE contracts using filters, into map view as markers.

What I mean is often times fertilizing contracts are the only things I want to take, so I need to find the closest fertilizer contract field to the dealership (vehicle shop), because contract is accepted with borrowed / leased vehicles (or simply for the product refills) and I don't want to drive half across the terrain if there are any closer contracts available.

Now its important to note that I play on large, absolutely HUGE, terrains where driving distance to possible fields can be 5-10 kilometers or more, one way. Now you probably understand why I'd like to easily find closest contract to the dealership :)

Our workaround for this is to just mass spam accept ALL fertilizing contracts we can, this seems to be limited to 80 which is a lot (no idea if its giants or better contracts limitation), then start to work the closest fields. But this is not a very good solution if you just want to do a few contracts, then you have to cancel tons of them and its just an hassle.

It would be a great feature if currently available contracts which includes filter selection, is shown on map-view. Not sure how this would be done, perhaps a additional button next to the sorting of contracts (number, profit, profit/min) like "show in map" or something. And I'm not talking about accepted but simply AVAILABLE contracts, so you could pick and choose which field ID to take.

Other way would be to sort distance between field and the dealership, closest one first.

Dunno, just throwing ideas around ;)

**Comment by Mmtrx** [comment]
Will think about that. Map markers I like better, since they can also answer other questions. Like: what are the fertilizing jobs in the neighborhood of my own fields / of my farm?

**Comment by Mmtrx** [comment]
Test version done. Will be in the next version update:
![missionIcons](https://user-images.githubusercontent.com/86842734/215271392-9d20ec89-8782-40a7-a1b0-cd512de71550.png)

**Comment by SnakeManPMC** [comment]
Very good work :)

I'm wondering if those icons are too small and too detailed, field number seems huge in comparison, maybe they are not easy to spot and differentiate on zoomed out map view.

And those icons appear according to available contracts with filters? In that case size and details won't matter as if there is a "smudge" next to a field number, you know its a contract you're looking for :)

Cant wait to test it out.

**Comment by Mmtrx** [comment]
Just published [v1.2.7.0](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.7.0).
Of course icons consider the filter settings on contracts page (because that's what you asked for 😉). Also show only if Details is on.

**Comment by SnakeManPMC** [comment]
Just tested in-game, works great, looks great (icons looked much better in my 4k screen, crisp clear and easy to recognize).

Awesome work, very much appreciated :)

**Comment by Carpantus** [comment]
The icons for the field missions are not displayed in multiplayer.

**Comment by SniperKittenCZ** [comment]
In singleplayer icons works, but not in MP. Can You check it, please?

**Comment by Mmtrx** [comment]
should be fixed with [v1.2.7.1](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.7.1)
