### ISSUE TITLE
Future suggestion & possible bug v 1.2.6.7 (i believe)

### ISSUE THREAD

**Issue by judg393** [Mmtrx/FS22_BetterContracts#94]
Would it be possible to keep the images of the rental vehicles visible on the contracts screen (maybe toggleable under detail) so you know what vehicles belong to what contract

**Comment by Mmtrx** [comment]
will think about that..

**Comment by Mmtrx** [comment]
Ready in my test version. Will be in next update. The vehicle info on the menu map also shows the current job for a leased mission vehicle (only if Details on):
![vehicleTag](https://user-images.githubusercontent.com/86842734/215275309-ee40fa61-645d-44b9-b7f4-bc715e355af8.png)
![vehicleActive](https://user-images.githubusercontent.com/86842734/215275321-058672c9-4066-4be3-8275-843dbcf6ad78.png)

**Comment by Mmtrx** [comment]
Just published [v1.2.7.0](https://github.com/Mmtrx/FS22_BetterContracts/releases/tag/v1.2.7.0).

**Comment by judg393** [comment]
Thanks @Mmtrx 

I had some difficulty with 1.2.6.2  as I wasn't getting enough crop to fulfil any harvest contacts even with the lower figure option. 

I rolled back to 1.2.6.2 (MH release) worked perfectly. Slightly nervous to test 1.2.7 but I'll see what I can do

**Comment by judg393** [comment]
I am not sure if it's helpful but I was playing a 4x map maybe that's what screwed with the values 

https://farmsimbrisco.itch.io/brisco-mapping

**Comment by judg393** [comment]
@Mmtrx think the lack of crop issue was due to me being out of date played solidly for the last few days and no contract issues (sorry I can't believe I didn't check the mod was up to date!)

**Comment by Mmtrx** [comment]
Ok I think then this also solves issue #59
