### ISSUE TITLE
Mod conflict

### ISSUE THREAD

**Issue by Michaelj15** [Mmtrx/FS22_BetterContracts#95]
Hello,

I have a problem with better contracts. It worked fine for months but today nothing works anymore. 
It's not a error with the mod, but i think it's a conflict between a few.
When i start a new savegame everything works fine. But in my existing savegame (spend months for a nice farm), the contracts page didn't show the available or accepted contracts anymore. When i click on the filter buttons on top of the page, the new contracts popups, but when i accepted, they disappear. So i don't see any accepted contracts or progress. I could finish the accepted, but when i want the money, i can't earn it. 
When i go to the xml from the missions, everything works fine. It's just a visible problem. 

I changed all settings to standard, deleted all missions in the xml savegame, but nothing works.
I don't want to start a new savegame, because it has bin a lot of work to make the map.
Any solutions what i could try to make it work again?

![image](https://user-images.githubusercontent.com/59195589/214512612-b2a40f8c-d4c3-4bcb-8cfd-e31af45d8e6e.png)
![image](https://user-images.githubusercontent.com/59195589/214512662-87fe635c-7e38-4087-abee-2ffc69df19f3.png)

**Comment by Mmtrx** [comment]
Hi,
I will try to help. Can you please
- activate Debug in the BetterContracts settings page
- attach your log.txt here

When you're saying everything went smooth for a long time, then all of a sudden the error occurred, question obviously is: What did you change? Update or add another mod?

**Comment by Michaelj15** [comment]
Thanks!
I have searched into files and the mod folder, but i can't find anything what is changed. Maybe something updated in the background, but as far i know there is always a popup from farming simulator before starting up.

Here is the log file:
[log.txt](https://github.com/Mmtrx/FS22_BetterContracts/files/10499144/log.txt)

**Comment by Mmtrx** [comment]
Hm,
that is quite a big log file! I found s.th. related to BetterContracts:
`2023-01-25 09:37  Missing filltype GRASS_FERMENTED BGA (1) : Vergister 20 m`
This new filltype is introduced by Maize+, and when BetterContracts asks the selling station (BGA) about the price for this, it doesn't know, and issues an error.

There is also s.th. wrong with the lighting in your map, lots of repeated warnings. Which map is that?

**Comment by Michaelj15** [comment]
Yeah, I know. It's the map banniel breizh with the new lighting mod. Don't know the name at the moment.

I gonna try to solve it, but the vergister is from pump and hoses in a packed file.
________________________________

**Comment by Mmtrx** [comment]
If still a problem - please re-open.
