### ISSUE TITLE
Update, Request and little problem 

### ISSUE THREAD

**Issue by Johanansl** [Mmtrx/FS22_BetterContracts#98]
We installed 1.2.7.0 and all problems are solved. 

We just have some little thing for future. When you open multiple harvest missions with same type like oat. As example field 1 and 2. You start harvest on field 1 and when you deliver, the delivered goods are counting at contract of field 2. Then also goes below 0… so you deliver -10.400 liters on field 2 while you are working on field 1. Please look at this. 

And the request: the to deliver percentage on the option screen is working well and we don’t need missioncomplefionfix anymore! But…. The amount can only be set to minimum 85%. That means we still have a tiny little bit to keep on our map. A big field for example we have only 10.000 liters to keep.  We would like to set this parameter to 50 or 60% so we have more to keep, we like for example: a field with 100.000 liters expected, to deliver about 75.000-80.000 . We hope you can add less percentage in the future. 

Thanks in advance!

**Comment by Mmtrx** [comment]
Hi,
thanks for your report. I'm afraid that is base game mechanics: if more than one contract has the same fruit/ same sellpoint, the game picks one at random to fill first. When 1 is complete, it starts to fill the second (random) contract. This switching takes a millisecond or so, and thus a little overshoot goes to contract 1. And this then shows a negative "To go" value. During my tests I have not seen more than 700 litres:
![fsScreen_2023_02_12_11_14_28](https://user-images.githubusercontent.com/86842734/218305422-c0265c9b-c51f-45d0-abab-bdaf6882a8f9.png)
You're saying you have seen a negative To go of -10.400?

Now for the lower percent for mission completion, you could do that for yourself: Insert new parameter values in file settings.lua:
```
		{name = "toDeliver", 
		values = {.50, .60, .70, .85,.87,.89,.91,.93},
		texts = {"50 %","60 %","70 %","85 %","87 %","89 %","91 %","standard"},
		default = 5,
```

**Comment by Johanansl** [comment]
Don’t know for sure if it is base game. I always do multiple contracts and i never had it. But it is no big deal.
Yes it was going to -10.400. But all contracts could be finished after finishing fieldwork. 

Thanks for the help and modifications on your mod! Very nice how you listen and implement things people asking, have problems with. Good job! 

Are you making more mods?

**Comment by Mmtrx** [comment]
Ok I can probably understand -10.400. The "overshoot" before the sellpoint switches to a second contract is about 1 - 2 % of the expected litres. With your big fields delivery amounts can go way up (maybe 1 million).

You can find my other mods in modHub by clicking on my name (in the display page of BetterContracts mod) 😉.

**Comment by Johanansl** [comment]
Hello, looks like this is no little problem. Had issues again. Found out that the minus amount is due to the delivery discount. The delivered amount goes to the 93%. So, when the discount is set to 70% and the field is not worked on jet, the completion is not triggered and at that point you still need to deliver the 93%. That is why it goes a lot in minus. Please find a solution for this. 
![4AC43CB1-DCA6-4053-A7DD-AD5029B9EC97](https://user-images.githubusercontent.com/117602728/222677378-d3be5a62-aa3f-4790-826b-30d91c385e0d.jpeg)
![6DF9C489-11C1-4FBA-ADE5-3F137FBA2891](https://user-images.githubusercontent.com/117602728/222677481-835101c0-889e-4b62-a848-7d0cd2814a76.jpeg)
