### ISSUE TITLE
Distributing contracts over multiple days

### ISSUE THREAD

**Issue by Timmeey86** [Mmtrx/FS22_BetterContracts#99]
Hi there, great and very helpful mod!

We noticed that when playing on a server with several days per month (in our case 3), all the contracts will appear within the first couple of hours of the first day, and there will be no new contracts on day 2 or 3, even with things like lazy farmer turned off.
Would there be a way to get a more basegame-like distribution of when contracts appear? I wouldn't mind doing this in a fork, if necessary

**Comment by Mmtrx** [comment]
Hi,
base game generates new missions every 4 ingame hours, until max number of missions is reached. The mod changes that to every hour:
```
MissionManager.MISSION_GENERATION_INTERVAL = 3600000 -- every 1 game hour 
```
You can set that back to 14400000 or even a higher value (in betterContracts.lua), so that new mission generation is more distributed over the day.

**Comment by Timmeey86** [comment]
Alright, thanks, will give that a try!

**Comment by Timmeey86** [comment]
@Mmtrx I would add this as a UI option (maybe 1-24h range in 1h steps). Are you fine with me doing that through a pull request?

**Comment by Mmtrx** [comment]
Of course, please go ahead.

**Comment by Timmeey86** [comment]
See #104

**Comment by Mmtrx** [comment]
ok, we can talk over there, at the pull req. Will close this here.
